// GENERATED by scripts/extract-artifloor.py -- do not edit by hand.
//
// ArtiFloor Timberland luxury vinyl plank. 24 colours across two ranges.
//
// THE TWO RANGES DIFFER BY CORE AND BOARD LENGTH, NOT BY WEAR LAYER. Both are
// 0.5mm wear layer -- identical on the surface the customer walks on. The
// 4.5mm range costs $9.00/m2 more (+56.6%) for a thicker core and a longer
// board (1524mm vs 1219mm), and that is ALL it buys. It is not the
// harder-wearing floor and must not be sold as one.
//
// EVERY m2 HERE IS DERIVED FROM THE INTEGER BOARD COUNT. ArtiFloor's printed
// m2/carton rounds UP, and its printed m2/pallet is that rounded carton figure
// multiplied by the box count, so the error compounds: a pallet of 4.5mm is
// 166.78656 m2, not the 167.4 m2 printed -- 0.6134 m2 short, nearly two
// boards. Use `cartonM2True` / `palletM2True` for ordering. The printed figures
// are carried only to check an ArtiFloor invoice against ArtiFloor's own maths.
//
// COLOUR IS NOT A UNIQUE KEY. Coastal Blackbutt, Natural Blackbutt, Weathered Oak, White Washed Oak
// exist in BOTH ranges at different prices. A quote line must name the range.
//
// NOT ON THE LIST, AND NOBODY SHOULD GUESS IT: how these planks are installed
// (glue-down, loose lay or click), whether ArtiFloor deliver and what freight
// costs to Nerang, what date this pricing took effect, and whether ArtiFloor
// supply trims, stair nosings or adhesive. Open questions for the supplier.

export type ArtiFloorRow = {
  code: string;
  range: string;
  colour: string;
  sizePrinted: string;
  lengthMm: number;
  widthMm: number;
  thicknessMm: number;
  /** 0.5mm on BOTH ranges. The dearer range is not the tougher one. */
  wearLayerMm: number;
  piecesPerCarton: number;
  /** m2 of ONE board, from its printed dimensions. */
  pieceM2: number;
  /** pieceM2 x piecesPerCarton. THE ORDERING FIGURE. */
  cartonM2True: number;
  /** ArtiFloor's printed m2/carton, rounded UP. Invoice-checking only. */
  cartonM2Printed: number;
  cartonM2Drift: number;
  boxesPerPallet: number;
  /** cartonM2True x boxesPerPallet. THE ORDERING FIGURE. */
  palletM2True: number;
  /** Printed m2/pallet = printed carton m2 x boxes, so the rounding compounds. */
  palletM2Printed: number;
  palletM2Drift: number;
  pricePerM2: number;
  pricePerPiece: number;
  /** At cartonM2True. What a carton should cost. */
  pricePerCarton: number;
  /** At cartonM2Printed. What ArtiFloor may invoice a carton at -- the gap is the rounding. */
  pricePerCartonIfPrinted: number;
  pricePerPallet: number;
  /** AT1xx / AT2xx / AT3xx (4.5mm) or AT25xx (2.5mm). Meaning unstated by ArtiFloor. */
  codeSeries: string;
  /** This colour name also exists in the other range, at a different price. */
  sharedColour: boolean;
};

export const ARTIFLOOR_SOURCE = "ArtiFloor_Timberland_Runable_Price_List_CURRENT_(1)_905uan.xlsx";
/** NOT STATED on the list. The file is titled "CURRENT" and carries no date. */
export const ARTIFLOOR_EFFECTIVE_FROM = "";
export const ARTIFLOOR_WEAR_LAYER_MM = 0.5;
/** 4.5mm over 2.5mm, per m2, for core and board length only. */
export const ARTIFLOOR_THICK_PREMIUM = 9.00;
export const ARTIFLOOR_THICK_PREMIUM_PCT = 56.6;

/** Picking & packing, per order. The only charge ArtiFloor publishes. */
export const ARTIFLOOR_CHARGE = {"name": "Picking & Packing", "basis": "Per order", "amount": 40.0, "note": "Listed on both supplied price sheets"};

export const ARTIFLOOR_LVP: ArtiFloorRow[] = [
  {"code": "AT101", "range": "Timberland 4.5mm", "colour": "Blackbutt", "sizePrinted": "1524 x 228mm", "lengthMm": 1524.0, "widthMm": 228.0, "thicknessMm": 4.5, "wearLayerMm": 0.5, "piecesPerCarton": 8, "pieceM2": 0.347472, "cartonM2True": 2.779776, "cartonM2Printed": 2.79, "cartonM2Drift": 0.0102, "boxesPerPallet": 60, "palletM2True": 166.78656, "palletM2Printed": 167.4, "palletM2Drift": 0.6134, "pricePerM2": 24.9, "pricePerPiece": 8.65, "pricePerCarton": 69.22, "pricePerCartonIfPrinted": 69.47, "pricePerPallet": 4152.99, "codeSeries": "AT1", "sharedColour": false},
  {"code": "AT102", "range": "Timberland 4.5mm", "colour": "Spotted Gum", "sizePrinted": "1524 x 228mm", "lengthMm": 1524.0, "widthMm": 228.0, "thicknessMm": 4.5, "wearLayerMm": 0.5, "piecesPerCarton": 8, "pieceM2": 0.347472, "cartonM2True": 2.779776, "cartonM2Printed": 2.79, "cartonM2Drift": 0.0102, "boxesPerPallet": 60, "palletM2True": 166.78656, "palletM2Printed": 167.4, "palletM2Drift": 0.6134, "pricePerM2": 24.9, "pricePerPiece": 8.65, "pricePerCarton": 69.22, "pricePerCartonIfPrinted": 69.47, "pricePerPallet": 4152.99, "codeSeries": "AT1", "sharedColour": false},
  {"code": "AT103", "range": "Timberland 4.5mm", "colour": "Weathered Oak", "sizePrinted": "1524 x 228mm", "lengthMm": 1524.0, "widthMm": 228.0, "thicknessMm": 4.5, "wearLayerMm": 0.5, "piecesPerCarton": 8, "pieceM2": 0.347472, "cartonM2True": 2.779776, "cartonM2Printed": 2.79, "cartonM2Drift": 0.0102, "boxesPerPallet": 60, "palletM2True": 166.78656, "palletM2Printed": 167.4, "palletM2Drift": 0.6134, "pricePerM2": 24.9, "pricePerPiece": 8.65, "pricePerCarton": 69.22, "pricePerCartonIfPrinted": 69.47, "pricePerPallet": 4152.99, "codeSeries": "AT1", "sharedColour": true},
  {"code": "AT104", "range": "Timberland 4.5mm", "colour": "Misty Morning", "sizePrinted": "1524 x 228mm", "lengthMm": 1524.0, "widthMm": 228.0, "thicknessMm": 4.5, "wearLayerMm": 0.5, "piecesPerCarton": 8, "pieceM2": 0.347472, "cartonM2True": 2.779776, "cartonM2Printed": 2.79, "cartonM2Drift": 0.0102, "boxesPerPallet": 60, "palletM2True": 166.78656, "palletM2Printed": 167.4, "palletM2Drift": 0.6134, "pricePerM2": 24.9, "pricePerPiece": 8.65, "pricePerCarton": 69.22, "pricePerCartonIfPrinted": 69.47, "pricePerPallet": 4152.99, "codeSeries": "AT1", "sharedColour": false},
  {"code": "AT201", "range": "Timberland 4.5mm", "colour": "Pale Blackbutt", "sizePrinted": "1524 x 228mm", "lengthMm": 1524.0, "widthMm": 228.0, "thicknessMm": 4.5, "wearLayerMm": 0.5, "piecesPerCarton": 8, "pieceM2": 0.347472, "cartonM2True": 2.779776, "cartonM2Printed": 2.79, "cartonM2Drift": 0.0102, "boxesPerPallet": 60, "palletM2True": 166.78656, "palletM2Printed": 167.4, "palletM2Drift": 0.6134, "pricePerM2": 24.9, "pricePerPiece": 8.65, "pricePerCarton": 69.22, "pricePerCartonIfPrinted": 69.47, "pricePerPallet": 4152.99, "codeSeries": "AT2", "sharedColour": false},
  {"code": "AT202", "range": "Timberland 4.5mm", "colour": "Coastal Blackbutt", "sizePrinted": "1524 x 228mm", "lengthMm": 1524.0, "widthMm": 228.0, "thicknessMm": 4.5, "wearLayerMm": 0.5, "piecesPerCarton": 8, "pieceM2": 0.347472, "cartonM2True": 2.779776, "cartonM2Printed": 2.79, "cartonM2Drift": 0.0102, "boxesPerPallet": 60, "palletM2True": 166.78656, "palletM2Printed": 167.4, "palletM2Drift": 0.6134, "pricePerM2": 24.9, "pricePerPiece": 8.65, "pricePerCarton": 69.22, "pricePerCartonIfPrinted": 69.47, "pricePerPallet": 4152.99, "codeSeries": "AT2", "sharedColour": true},
  {"code": "AT203", "range": "Timberland 4.5mm", "colour": "Rainbow Beach", "sizePrinted": "1524 x 228mm", "lengthMm": 1524.0, "widthMm": 228.0, "thicknessMm": 4.5, "wearLayerMm": 0.5, "piecesPerCarton": 8, "pieceM2": 0.347472, "cartonM2True": 2.779776, "cartonM2Printed": 2.79, "cartonM2Drift": 0.0102, "boxesPerPallet": 60, "palletM2True": 166.78656, "palletM2Printed": 167.4, "palletM2Drift": 0.6134, "pricePerM2": 24.9, "pricePerPiece": 8.65, "pricePerCarton": 69.22, "pricePerCartonIfPrinted": 69.47, "pricePerPallet": 4152.99, "codeSeries": "AT2", "sharedColour": false},
  {"code": "AT204", "range": "Timberland 4.5mm", "colour": "Grey River Pine", "sizePrinted": "1524 x 228mm", "lengthMm": 1524.0, "widthMm": 228.0, "thicknessMm": 4.5, "wearLayerMm": 0.5, "piecesPerCarton": 8, "pieceM2": 0.347472, "cartonM2True": 2.779776, "cartonM2Printed": 2.79, "cartonM2Drift": 0.0102, "boxesPerPallet": 60, "palletM2True": 166.78656, "palletM2Printed": 167.4, "palletM2Drift": 0.6134, "pricePerM2": 24.9, "pricePerPiece": 8.65, "pricePerCarton": 69.22, "pricePerCartonIfPrinted": 69.47, "pricePerPallet": 4152.99, "codeSeries": "AT2", "sharedColour": false},
  {"code": "AT205", "range": "Timberland 4.5mm", "colour": "Fraser", "sizePrinted": "1524 x 228mm", "lengthMm": 1524.0, "widthMm": 228.0, "thicknessMm": 4.5, "wearLayerMm": 0.5, "piecesPerCarton": 8, "pieceM2": 0.347472, "cartonM2True": 2.779776, "cartonM2Printed": 2.79, "cartonM2Drift": 0.0102, "boxesPerPallet": 60, "palletM2True": 166.78656, "palletM2Printed": 167.4, "palletM2Drift": 0.6134, "pricePerM2": 24.9, "pricePerPiece": 8.65, "pricePerCarton": 69.22, "pricePerCartonIfPrinted": 69.47, "pricePerPallet": 4152.99, "codeSeries": "AT2", "sharedColour": false},
  {"code": "AT206", "range": "Timberland 4.5mm", "colour": "McKenzie", "sizePrinted": "1524 x 228mm", "lengthMm": 1524.0, "widthMm": 228.0, "thicknessMm": 4.5, "wearLayerMm": 0.5, "piecesPerCarton": 8, "pieceM2": 0.347472, "cartonM2True": 2.779776, "cartonM2Printed": 2.79, "cartonM2Drift": 0.0102, "boxesPerPallet": 60, "palletM2True": 166.78656, "palletM2Printed": 167.4, "palletM2Drift": 0.6134, "pricePerM2": 24.9, "pricePerPiece": 8.65, "pricePerCarton": 69.22, "pricePerCartonIfPrinted": 69.47, "pricePerPallet": 4152.99, "codeSeries": "AT2", "sharedColour": false},
  {"code": "AT301", "range": "Timberland 4.5mm", "colour": "Coral Sands Oak", "sizePrinted": "1524 x 228mm", "lengthMm": 1524.0, "widthMm": 228.0, "thicknessMm": 4.5, "wearLayerMm": 0.5, "piecesPerCarton": 8, "pieceM2": 0.347472, "cartonM2True": 2.779776, "cartonM2Printed": 2.79, "cartonM2Drift": 0.0102, "boxesPerPallet": 60, "palletM2True": 166.78656, "palletM2Printed": 167.4, "palletM2Drift": 0.6134, "pricePerM2": 24.9, "pricePerPiece": 8.65, "pricePerCarton": 69.22, "pricePerCartonIfPrinted": 69.47, "pricePerPallet": 4152.99, "codeSeries": "AT3", "sharedColour": false},
  {"code": "AT302", "range": "Timberland 4.5mm", "colour": "Natural White Oak", "sizePrinted": "1524 x 228mm", "lengthMm": 1524.0, "widthMm": 228.0, "thicknessMm": 4.5, "wearLayerMm": 0.5, "piecesPerCarton": 8, "pieceM2": 0.347472, "cartonM2True": 2.779776, "cartonM2Printed": 2.79, "cartonM2Drift": 0.0102, "boxesPerPallet": 60, "palletM2True": 166.78656, "palletM2Printed": 167.4, "palletM2Drift": 0.6134, "pricePerM2": 24.9, "pricePerPiece": 8.65, "pricePerCarton": 69.22, "pricePerCartonIfPrinted": 69.47, "pricePerPallet": 4152.99, "codeSeries": "AT3", "sharedColour": false},
  {"code": "AT303", "range": "Timberland 4.5mm", "colour": "Sand Light", "sizePrinted": "1524 x 228mm", "lengthMm": 1524.0, "widthMm": 228.0, "thicknessMm": 4.5, "wearLayerMm": 0.5, "piecesPerCarton": 8, "pieceM2": 0.347472, "cartonM2True": 2.779776, "cartonM2Printed": 2.79, "cartonM2Drift": 0.0102, "boxesPerPallet": 60, "palletM2True": 166.78656, "palletM2Printed": 167.4, "palletM2Drift": 0.6134, "pricePerM2": 24.9, "pricePerPiece": 8.65, "pricePerCarton": 69.22, "pricePerCartonIfPrinted": 69.47, "pricePerPallet": 4152.99, "codeSeries": "AT3", "sharedColour": false},
  {"code": "AT304", "range": "Timberland 4.5mm", "colour": "White Washed Oak", "sizePrinted": "1524 x 228mm", "lengthMm": 1524.0, "widthMm": 228.0, "thicknessMm": 4.5, "wearLayerMm": 0.5, "piecesPerCarton": 8, "pieceM2": 0.347472, "cartonM2True": 2.779776, "cartonM2Printed": 2.79, "cartonM2Drift": 0.0102, "boxesPerPallet": 60, "palletM2True": 166.78656, "palletM2Printed": 167.4, "palletM2Drift": 0.6134, "pricePerM2": 24.9, "pricePerPiece": 8.65, "pricePerCarton": 69.22, "pricePerCartonIfPrinted": 69.47, "pricePerPallet": 4152.99, "codeSeries": "AT3", "sharedColour": true},
  {"code": "AT305", "range": "Timberland 4.5mm", "colour": "Natural Blackbutt", "sizePrinted": "1524 x 228mm", "lengthMm": 1524.0, "widthMm": 228.0, "thicknessMm": 4.5, "wearLayerMm": 0.5, "piecesPerCarton": 8, "pieceM2": 0.347472, "cartonM2True": 2.779776, "cartonM2Printed": 2.79, "cartonM2Drift": 0.0102, "boxesPerPallet": 60, "palletM2True": 166.78656, "palletM2Printed": 167.4, "palletM2Drift": 0.6134, "pricePerM2": 24.9, "pricePerPiece": 8.65, "pricePerCarton": 69.22, "pricePerCartonIfPrinted": 69.47, "pricePerPallet": 4152.99, "codeSeries": "AT3", "sharedColour": true},
  {"code": "AT306", "range": "Timberland 4.5mm", "colour": "Smoked European Oak", "sizePrinted": "1524 x 228mm", "lengthMm": 1524.0, "widthMm": 228.0, "thicknessMm": 4.5, "wearLayerMm": 0.5, "piecesPerCarton": 8, "pieceM2": 0.347472, "cartonM2True": 2.779776, "cartonM2Printed": 2.79, "cartonM2Drift": 0.0102, "boxesPerPallet": 60, "palletM2True": 166.78656, "palletM2Printed": 167.4, "palletM2Drift": 0.6134, "pricePerM2": 24.9, "pricePerPiece": 8.65, "pricePerCarton": 69.22, "pricePerCartonIfPrinted": 69.47, "pricePerPallet": 4152.99, "codeSeries": "AT3", "sharedColour": false},
  {"code": "AT307", "range": "Timberland 4.5mm", "colour": "Natural European Oak", "sizePrinted": "1524 x 228mm", "lengthMm": 1524.0, "widthMm": 228.0, "thicknessMm": 4.5, "wearLayerMm": 0.5, "piecesPerCarton": 8, "pieceM2": 0.347472, "cartonM2True": 2.779776, "cartonM2Printed": 2.79, "cartonM2Drift": 0.0102, "boxesPerPallet": 60, "palletM2True": 166.78656, "palletM2Printed": 167.4, "palletM2Drift": 0.6134, "pricePerM2": 24.9, "pricePerPiece": 8.65, "pricePerCarton": 69.22, "pricePerCartonIfPrinted": 69.47, "pricePerPallet": 4152.99, "codeSeries": "AT3", "sharedColour": false},
  {"code": "AT308", "range": "Timberland 4.5mm", "colour": "Nordic Grey Oak", "sizePrinted": "1524 x 228mm", "lengthMm": 1524.0, "widthMm": 228.0, "thicknessMm": 4.5, "wearLayerMm": 0.5, "piecesPerCarton": 8, "pieceM2": 0.347472, "cartonM2True": 2.779776, "cartonM2Printed": 2.79, "cartonM2Drift": 0.0102, "boxesPerPallet": 60, "palletM2True": 166.78656, "palletM2Printed": 167.4, "palletM2Drift": 0.6134, "pricePerM2": 24.9, "pricePerPiece": 8.65, "pricePerCarton": 69.22, "pricePerCartonIfPrinted": 69.47, "pricePerPallet": 4152.99, "codeSeries": "AT3", "sharedColour": false},
  {"code": "AT2501", "range": "Timberland 2.5mm", "colour": "Coastal Blackbutt", "sizePrinted": "1219 x 228mm", "lengthMm": 1219.0, "widthMm": 228.0, "thicknessMm": 2.5, "wearLayerMm": 0.5, "piecesPerCarton": 14, "pieceM2": 0.277932, "cartonM2True": 3.891048, "cartonM2Printed": 3.9, "cartonM2Drift": 0.009, "boxesPerPallet": 56, "palletM2True": 217.898688, "palletM2Printed": 218.4, "palletM2Drift": 0.5013, "pricePerM2": 15.9, "pricePerPiece": 4.42, "pricePerCarton": 61.87, "pricePerCartonIfPrinted": 62.01, "pricePerPallet": 3464.59, "codeSeries": "AT25", "sharedColour": true},
  {"code": "AT2502", "range": "Timberland 2.5mm", "colour": "Riverside Spotted Gum", "sizePrinted": "1219 x 228mm", "lengthMm": 1219.0, "widthMm": 228.0, "thicknessMm": 2.5, "wearLayerMm": 0.5, "piecesPerCarton": 14, "pieceM2": 0.277932, "cartonM2True": 3.891048, "cartonM2Printed": 3.9, "cartonM2Drift": 0.009, "boxesPerPallet": 56, "palletM2True": 217.898688, "palletM2Printed": 218.4, "palletM2Drift": 0.5013, "pricePerM2": 15.9, "pricePerPiece": 4.42, "pricePerCarton": 61.87, "pricePerCartonIfPrinted": 62.01, "pricePerPallet": 3464.59, "codeSeries": "AT25", "sharedColour": false},
  {"code": "AT2503", "range": "Timberland 2.5mm", "colour": "Weathered Oak", "sizePrinted": "1219 x 228mm", "lengthMm": 1219.0, "widthMm": 228.0, "thicknessMm": 2.5, "wearLayerMm": 0.5, "piecesPerCarton": 14, "pieceM2": 0.277932, "cartonM2True": 3.891048, "cartonM2Printed": 3.9, "cartonM2Drift": 0.009, "boxesPerPallet": 56, "palletM2True": 217.898688, "palletM2Printed": 218.4, "palletM2Drift": 0.5013, "pricePerM2": 15.9, "pricePerPiece": 4.42, "pricePerCarton": 61.87, "pricePerCartonIfPrinted": 62.01, "pricePerPallet": 3464.59, "codeSeries": "AT25", "sharedColour": true},
  {"code": "AT2504", "range": "Timberland 2.5mm", "colour": "Natural Oak", "sizePrinted": "1219 x 228mm", "lengthMm": 1219.0, "widthMm": 228.0, "thicknessMm": 2.5, "wearLayerMm": 0.5, "piecesPerCarton": 14, "pieceM2": 0.277932, "cartonM2True": 3.891048, "cartonM2Printed": 3.9, "cartonM2Drift": 0.009, "boxesPerPallet": 56, "palletM2True": 217.898688, "palletM2Printed": 218.4, "palletM2Drift": 0.5013, "pricePerM2": 15.9, "pricePerPiece": 4.42, "pricePerCarton": 61.87, "pricePerCartonIfPrinted": 62.01, "pricePerPallet": 3464.59, "codeSeries": "AT25", "sharedColour": false},
  {"code": "AT2505", "range": "Timberland 2.5mm", "colour": "Natural Blackbutt", "sizePrinted": "1219 x 228mm", "lengthMm": 1219.0, "widthMm": 228.0, "thicknessMm": 2.5, "wearLayerMm": 0.5, "piecesPerCarton": 14, "pieceM2": 0.277932, "cartonM2True": 3.891048, "cartonM2Printed": 3.9, "cartonM2Drift": 0.009, "boxesPerPallet": 56, "palletM2True": 217.898688, "palletM2Printed": 218.4, "palletM2Drift": 0.5013, "pricePerM2": 15.9, "pricePerPiece": 4.42, "pricePerCarton": 61.87, "pricePerCartonIfPrinted": 62.01, "pricePerPallet": 3464.59, "codeSeries": "AT25", "sharedColour": true},
  {"code": "AT2506", "range": "Timberland 2.5mm", "colour": "White Washed Oak", "sizePrinted": "1219 x 228mm", "lengthMm": 1219.0, "widthMm": 228.0, "thicknessMm": 2.5, "wearLayerMm": 0.5, "piecesPerCarton": 14, "pieceM2": 0.277932, "cartonM2True": 3.891048, "cartonM2Printed": 3.9, "cartonM2Drift": 0.009, "boxesPerPallet": 56, "palletM2True": 217.898688, "palletM2Printed": 218.4, "palletM2Drift": 0.5013, "pricePerM2": 15.9, "pricePerPiece": 4.42, "pricePerCarton": 61.87, "pricePerCartonIfPrinted": 62.01, "pricePerPallet": 3464.59, "codeSeries": "AT25", "sharedColour": true},
];
