/**
 * GENERATED by scripts/extract-bigpanda.py — do not hand-edit.
 * Source: Big_Panda_Flooring_Feb_2025_Terra_otVGLw.xlsx
 *
 * 38 floor colours across 5 ranges (25 SPC hybrid, 13 engineered oak), 5 trims
 * and 1 underlay. Read the extractor's docstring for what this supplier does
 * that the others do not — the short version:
 *
 *  - The price list date is off the FILENAME, not the sheet. Feb 2025, 19 months old.
 *  - `Modern Engineered Timber / Oak 14/3mm` carries TWO prices, split by board
 *    size (1900x190 $59, 2200x220 $62). Range does not determine price here.
 *  - SPC thickness in the range name is core + ATTACHED PAD. 6.5mm is a 5mm board.
 *  - No wear layer published on any SPC row. The '+1.5mm' is underlay, not wear.
 *  - Boards per box is DERIVED (every printed m2/box divides to a whole board),
 *    so `m2PerBox` is the derived figure and `m2PerBoxPrinted` is for invoices.
 *  - Big Panda do NOT deliver and charge NO baling/packing fee. Both confirmed.
 *  - Nothing in the accessories sheet fits the engineered timber.
 */

export type BigPandaFloor = {
  category: string;
  categoryPrinted: string;
  range: string;
  /** SPC only — every engineered row is codeless in the source. */
  code: string | null;
  colour: string;
  size: string;
  lengthMm: number;
  widthMm: number;
  /** TOTAL mm as named and sold. On SPC that INCLUDES the attached pad. */
  thicknessMm: number;
  /** SPC board without its pad — the number to compare against a rival's SPC. */
  coreMm: number | null;
  /** Attached IXPE pad. NOT a wear layer. */
  padMm: number | null;
  /** Engineered oak wear veneer, off the '14/3mm' notation. */
  veneerMm: number | null;
  boardM2: number;
  boardsPerBox: number;
  /** DERIVED: boardM2 x boardsPerBox. Use this for ordering. */
  m2PerBox: number;
  /** As printed. Cross-check an invoice against this and nothing else. */
  m2PerBoxPrinted: number;
  m2PerBoxDrifts: boolean;
  /** Embossing/grade text as printed. A look, not a durability rating. */
  surface: string;
  pricePerM2: number;
};

export type BigPandaAccessory = {
  item: string;
  size: string;
  applies: string;
  price: number;
  unitPrinted: string;
  isUnderlay: boolean;
  coverageM2: number | null;
  perM2: number | null;
  /** Set only where Big Panda name ONE floor range. Empty = fits any SPC. */
  fitsRange: string;
  matchColour: boolean;
  multiLength: boolean;
};

export const BP_SOURCE = "Big Panda Flooring price list (Feb 2025) \u2014 Big_Panda_Flooring_Feb_2025_Terra_otVGLw.xlsx";
export const BP_PRICE_LIST_DATE = "2025-02-01";
export const BP_PRICE_LIST_PRINTED = "Feb 2025";
/** Where the date came from. 'filename' = weakest provenance in the book. */
export const BP_PRICE_LIST_DATE_SOURCE = "filename";

/** Verbatim off the 'Supplier Notes' sheet. All four rules, unedited. */
export const BP_NOTES: string[] = [
  "Supplier does not deliver. Terra Flooring must arrange its own transport / pickup.",
  "No baling, packing or dispatch fee.",
  "MDF Scotia intentionally excluded \u2014 Terra Flooring does not sell this product.",
  "Supplier address: Building 2C/29-41 Lysaght St, Acacia Ridge QLD 4110."
];

/** Per-range digest, including which range splits its price on board size. */
export const BP_RANGES = [
  {
    "range": "Titan Guard SPC Hybrid 6.5mm",
    "category": "hybrid",
    "colours": 11,
    "sizes": [
      "1500 x 228 x 5+1.5mm"
    ],
    "prices": [
      18.5
    ],
    "m2PerBox": [
      2.052
    ],
    "boardsPerBox": [
      6
    ],
    "thicknessMm": 6.5,
    "coreMm": 5.0,
    "padMm": 1.5,
    "veneerMm": null,
    "surfaces": [
      "Random EIR"
    ],
    "splitOnSize": false
  },
  {
    "range": "Titan Guard SPC Hybrid 8.0mm",
    "category": "hybrid",
    "colours": 8,
    "sizes": [
      "1500 x 228 x 6.5+1.5mm"
    ],
    "prices": [
      25.5
    ],
    "m2PerBox": [
      2.052
    ],
    "boardsPerBox": [
      6
    ],
    "thicknessMm": 8.0,
    "coreMm": 6.5,
    "padMm": 1.5,
    "veneerMm": null,
    "surfaces": [
      "Wood texture"
    ],
    "splitOnSize": false
  },
  {
    "range": "Titan Guard SPC Hybrid 10.5mm",
    "category": "hybrid",
    "colours": 6,
    "sizes": [
      "1800 x 230 x 9+1.5mm"
    ],
    "prices": [
      29.9
    ],
    "m2PerBox": [
      1.242
    ],
    "boardsPerBox": [
      3
    ],
    "thicknessMm": 10.5,
    "coreMm": 9.0,
    "padMm": 1.5,
    "veneerMm": null,
    "surfaces": [
      "Wood texture"
    ],
    "splitOnSize": false
  },
  {
    "range": "Luminous Oak 15/2mm",
    "category": "timber",
    "colours": 7,
    "sizes": [
      "1900 x 190 x 15/2mm"
    ],
    "prices": [
      48.0
    ],
    "m2PerBox": [
      2.166
    ],
    "boardsPerBox": [
      6
    ],
    "thicknessMm": 15.0,
    "coreMm": null,
    "padMm": null,
    "veneerMm": 2.0,
    "surfaces": [
      "Timber Grade ABC+"
    ],
    "splitOnSize": false
  },
  {
    "range": "Modern Engineered Timber / Oak 14/3mm",
    "category": "timber",
    "colours": 6,
    "sizes": [
      "1900 x 190 x 14/3mm",
      "2200 x 220 x 14/3mm"
    ],
    "prices": [
      59.0,
      62.0
    ],
    "m2PerBox": [
      2.888,
      2.904
    ],
    "boardsPerBox": [
      6,
      8
    ],
    "thicknessMm": 14.0,
    "coreMm": null,
    "padMm": null,
    "veneerMm": 3.0,
    "surfaces": [
      "Timber Grade ABC+"
    ],
    "splitOnSize": true
  }
] as const;

/** Colour names that do NOT identify a product on their own. */
export const BP_COLOUR_COLLISIONS = [
  {
    "colour": "Natural Oak",
    "uses": [
      {
        "range": "Titan Guard SPC Hybrid 8.0mm",
        "category": "hybrid",
        "pricePerM2": 25.5
      },
      {
        "range": "Modern Engineered Timber / Oak 14/3mm",
        "category": "timber",
        "pricePerM2": 59.0
      }
    ]
  }
] as const;

/** What the accessories sheet does and does not cover. */
export const BP_ACCESSORY_GAPS = {
  "spcWithAccessories": true,
  "timberWithAccessories": false,
  "scotiaFitsOneThicknessOnly": "Titan Guard SPC Hybrid 6.5mm",
  "nosingNamesLaminateButNoneIsSold": true,
  "laminateRangesInBook": 0
} as const;

export const BP_FLOORS: BigPandaFloor[] = [
  {
    "category": "hybrid",
    "categoryPrinted": "Hybrid",
    "range": "Titan Guard SPC Hybrid 6.5mm",
    "code": "1107-7",
    "colour": "Honey Oak",
    "size": "1500 x 228 x 5+1.5mm",
    "lengthMm": 1500,
    "widthMm": 228,
    "thicknessMm": 6.5,
    "coreMm": 5.0,
    "padMm": 1.5,
    "veneerMm": null,
    "boardM2": 0.342,
    "boardsPerBox": 6,
    "m2PerBox": 2.052,
    "m2PerBoxPrinted": 2.052,
    "m2PerBoxDrifts": false,
    "surface": "Random EIR",
    "pricePerM2": 18.5
  },
  {
    "category": "hybrid",
    "categoryPrinted": "Hybrid",
    "range": "Titan Guard SPC Hybrid 6.5mm",
    "code": "1028-9",
    "colour": "Walnut",
    "size": "1500 x 228 x 5+1.5mm",
    "lengthMm": 1500,
    "widthMm": 228,
    "thicknessMm": 6.5,
    "coreMm": 5.0,
    "padMm": 1.5,
    "veneerMm": null,
    "boardM2": 0.342,
    "boardsPerBox": 6,
    "m2PerBox": 2.052,
    "m2PerBoxPrinted": 2.052,
    "m2PerBoxDrifts": false,
    "surface": "Random EIR",
    "pricePerM2": 18.5
  },
  {
    "category": "hybrid",
    "categoryPrinted": "Hybrid",
    "range": "Titan Guard SPC Hybrid 6.5mm",
    "code": "1107-11",
    "colour": "Salt Oak",
    "size": "1500 x 228 x 5+1.5mm",
    "lengthMm": 1500,
    "widthMm": 228,
    "thicknessMm": 6.5,
    "coreMm": 5.0,
    "padMm": 1.5,
    "veneerMm": null,
    "boardM2": 0.342,
    "boardsPerBox": 6,
    "m2PerBox": 2.052,
    "m2PerBoxPrinted": 2.052,
    "m2PerBoxDrifts": false,
    "surface": "Random EIR",
    "pricePerM2": 18.5
  },
  {
    "category": "hybrid",
    "categoryPrinted": "Hybrid",
    "range": "Titan Guard SPC Hybrid 6.5mm",
    "code": "1107-16",
    "colour": "Pinnacle Smoke",
    "size": "1500 x 228 x 5+1.5mm",
    "lengthMm": 1500,
    "widthMm": 228,
    "thicknessMm": 6.5,
    "coreMm": 5.0,
    "padMm": 1.5,
    "veneerMm": null,
    "boardM2": 0.342,
    "boardsPerBox": 6,
    "m2PerBox": 2.052,
    "m2PerBoxPrinted": 2.052,
    "m2PerBoxDrifts": false,
    "surface": "Random EIR",
    "pricePerM2": 18.5
  },
  {
    "category": "hybrid",
    "categoryPrinted": "Hybrid",
    "range": "Titan Guard SPC Hybrid 6.5mm",
    "code": "1107-22",
    "colour": "Sandy Oak",
    "size": "1500 x 228 x 5+1.5mm",
    "lengthMm": 1500,
    "widthMm": 228,
    "thicknessMm": 6.5,
    "coreMm": 5.0,
    "padMm": 1.5,
    "veneerMm": null,
    "boardM2": 0.342,
    "boardsPerBox": 6,
    "m2PerBox": 2.052,
    "m2PerBoxPrinted": 2.052,
    "m2PerBoxDrifts": false,
    "surface": "Random EIR",
    "pricePerM2": 18.5
  },
  {
    "category": "hybrid",
    "categoryPrinted": "Hybrid",
    "range": "Titan Guard SPC Hybrid 6.5mm",
    "code": "1179-2",
    "colour": "Blackbutt",
    "size": "1500 x 228 x 5+1.5mm",
    "lengthMm": 1500,
    "widthMm": 228,
    "thicknessMm": 6.5,
    "coreMm": 5.0,
    "padMm": 1.5,
    "veneerMm": null,
    "boardM2": 0.342,
    "boardsPerBox": 6,
    "m2PerBox": 2.052,
    "m2PerBoxPrinted": 2.052,
    "m2PerBoxDrifts": false,
    "surface": "Random EIR",
    "pricePerM2": 18.5
  },
  {
    "category": "hybrid",
    "categoryPrinted": "Hybrid",
    "range": "Titan Guard SPC Hybrid 6.5mm",
    "code": "88065-1",
    "colour": "Highland Oak",
    "size": "1500 x 228 x 5+1.5mm",
    "lengthMm": 1500,
    "widthMm": 228,
    "thicknessMm": 6.5,
    "coreMm": 5.0,
    "padMm": 1.5,
    "veneerMm": null,
    "boardM2": 0.342,
    "boardsPerBox": 6,
    "m2PerBox": 2.052,
    "m2PerBoxPrinted": 2.052,
    "m2PerBoxDrifts": false,
    "surface": "Random EIR",
    "pricePerM2": 18.5
  },
  {
    "category": "hybrid",
    "categoryPrinted": "Hybrid",
    "range": "Titan Guard SPC Hybrid 6.5mm",
    "code": "9021-11",
    "colour": "Seasoned Grey",
    "size": "1500 x 228 x 5+1.5mm",
    "lengthMm": 1500,
    "widthMm": 228,
    "thicknessMm": 6.5,
    "coreMm": 5.0,
    "padMm": 1.5,
    "veneerMm": null,
    "boardM2": 0.342,
    "boardsPerBox": 6,
    "m2PerBox": 2.052,
    "m2PerBoxPrinted": 2.052,
    "m2PerBoxDrifts": false,
    "surface": "Random EIR",
    "pricePerM2": 18.5
  },
  {
    "category": "hybrid",
    "categoryPrinted": "Hybrid",
    "range": "Titan Guard SPC Hybrid 6.5mm",
    "code": "1247-2",
    "colour": "Spotted Gum",
    "size": "1500 x 228 x 5+1.5mm",
    "lengthMm": 1500,
    "widthMm": 228,
    "thicknessMm": 6.5,
    "coreMm": 5.0,
    "padMm": 1.5,
    "veneerMm": null,
    "boardM2": 0.342,
    "boardsPerBox": 6,
    "m2PerBox": 2.052,
    "m2PerBoxPrinted": 2.052,
    "m2PerBoxDrifts": false,
    "surface": "Random EIR",
    "pricePerM2": 18.5
  },
  {
    "category": "hybrid",
    "categoryPrinted": "Hybrid",
    "range": "Titan Guard SPC Hybrid 6.5mm",
    "code": "6619-6",
    "colour": "Silver Grey",
    "size": "1500 x 228 x 5+1.5mm",
    "lengthMm": 1500,
    "widthMm": 228,
    "thicknessMm": 6.5,
    "coreMm": 5.0,
    "padMm": 1.5,
    "veneerMm": null,
    "boardM2": 0.342,
    "boardsPerBox": 6,
    "m2PerBox": 2.052,
    "m2PerBoxPrinted": 2.052,
    "m2PerBoxDrifts": false,
    "surface": "Random EIR",
    "pricePerM2": 18.5
  },
  {
    "category": "hybrid",
    "categoryPrinted": "Hybrid",
    "range": "Titan Guard SPC Hybrid 6.5mm",
    "code": "133-3",
    "colour": "Limed Oak",
    "size": "1500 x 228 x 5+1.5mm",
    "lengthMm": 1500,
    "widthMm": 228,
    "thicknessMm": 6.5,
    "coreMm": 5.0,
    "padMm": 1.5,
    "veneerMm": null,
    "boardM2": 0.342,
    "boardsPerBox": 6,
    "m2PerBox": 2.052,
    "m2PerBoxPrinted": 2.052,
    "m2PerBoxDrifts": false,
    "surface": "Random EIR",
    "pricePerM2": 18.5
  },
  {
    "category": "hybrid",
    "categoryPrinted": "Hybrid",
    "range": "Titan Guard SPC Hybrid 8.0mm",
    "code": "925-1",
    "colour": "Sahara",
    "size": "1500 x 228 x 6.5+1.5mm",
    "lengthMm": 1500,
    "widthMm": 228,
    "thicknessMm": 8.0,
    "coreMm": 6.5,
    "padMm": 1.5,
    "veneerMm": null,
    "boardM2": 0.342,
    "boardsPerBox": 6,
    "m2PerBox": 2.052,
    "m2PerBoxPrinted": 2.052,
    "m2PerBoxDrifts": false,
    "surface": "Wood texture",
    "pricePerM2": 25.5
  },
  {
    "category": "hybrid",
    "categoryPrinted": "Hybrid",
    "range": "Titan Guard SPC Hybrid 8.0mm",
    "code": "930-9",
    "colour": "Ironbark",
    "size": "1500 x 228 x 6.5+1.5mm",
    "lengthMm": 1500,
    "widthMm": 228,
    "thicknessMm": 8.0,
    "coreMm": 6.5,
    "padMm": 1.5,
    "veneerMm": null,
    "boardM2": 0.342,
    "boardsPerBox": 6,
    "m2PerBox": 2.052,
    "m2PerBoxPrinted": 2.052,
    "m2PerBoxDrifts": false,
    "surface": "Wood texture",
    "pricePerM2": 25.5
  },
  {
    "category": "hybrid",
    "categoryPrinted": "Hybrid",
    "range": "Titan Guard SPC Hybrid 8.0mm",
    "code": "952-1",
    "colour": "Mountain Eucalyptus",
    "size": "1500 x 228 x 6.5+1.5mm",
    "lengthMm": 1500,
    "widthMm": 228,
    "thicknessMm": 8.0,
    "coreMm": 6.5,
    "padMm": 1.5,
    "veneerMm": null,
    "boardM2": 0.342,
    "boardsPerBox": 6,
    "m2PerBox": 2.052,
    "m2PerBoxPrinted": 2.052,
    "m2PerBoxDrifts": false,
    "surface": "Wood texture",
    "pricePerM2": 25.5
  },
  {
    "category": "hybrid",
    "categoryPrinted": "Hybrid",
    "range": "Titan Guard SPC Hybrid 8.0mm",
    "code": "952-3",
    "colour": "Natural Oak",
    "size": "1500 x 228 x 6.5+1.5mm",
    "lengthMm": 1500,
    "widthMm": 228,
    "thicknessMm": 8.0,
    "coreMm": 6.5,
    "padMm": 1.5,
    "veneerMm": null,
    "boardM2": 0.342,
    "boardsPerBox": 6,
    "m2PerBox": 2.052,
    "m2PerBoxPrinted": 2.052,
    "m2PerBoxDrifts": false,
    "surface": "Wood texture",
    "pricePerM2": 25.5
  },
  {
    "category": "hybrid",
    "categoryPrinted": "Hybrid",
    "range": "Titan Guard SPC Hybrid 8.0mm",
    "code": "959-8",
    "colour": "Merbau",
    "size": "1500 x 228 x 6.5+1.5mm",
    "lengthMm": 1500,
    "widthMm": 228,
    "thicknessMm": 8.0,
    "coreMm": 6.5,
    "padMm": 1.5,
    "veneerMm": null,
    "boardM2": 0.342,
    "boardsPerBox": 6,
    "m2PerBox": 2.052,
    "m2PerBoxPrinted": 2.052,
    "m2PerBoxDrifts": false,
    "surface": "Wood texture",
    "pricePerM2": 25.5
  },
  {
    "category": "hybrid",
    "categoryPrinted": "Hybrid",
    "range": "Titan Guard SPC Hybrid 8.0mm",
    "code": "966-7",
    "colour": "Paperbark",
    "size": "1500 x 228 x 6.5+1.5mm",
    "lengthMm": 1500,
    "widthMm": 228,
    "thicknessMm": 8.0,
    "coreMm": 6.5,
    "padMm": 1.5,
    "veneerMm": null,
    "boardM2": 0.342,
    "boardsPerBox": 6,
    "m2PerBox": 2.052,
    "m2PerBoxPrinted": 2.052,
    "m2PerBoxDrifts": false,
    "surface": "Wood texture",
    "pricePerM2": 25.5
  },
  {
    "category": "hybrid",
    "categoryPrinted": "Hybrid",
    "range": "Titan Guard SPC Hybrid 8.0mm",
    "code": "967-4",
    "colour": "Wild Olive",
    "size": "1500 x 228 x 6.5+1.5mm",
    "lengthMm": 1500,
    "widthMm": 228,
    "thicknessMm": 8.0,
    "coreMm": 6.5,
    "padMm": 1.5,
    "veneerMm": null,
    "boardM2": 0.342,
    "boardsPerBox": 6,
    "m2PerBox": 2.052,
    "m2PerBoxPrinted": 2.052,
    "m2PerBoxDrifts": false,
    "surface": "Wood texture",
    "pricePerM2": 25.5
  },
  {
    "category": "hybrid",
    "categoryPrinted": "Hybrid",
    "range": "Titan Guard SPC Hybrid 8.0mm",
    "code": "969-6",
    "colour": "Silver Gum",
    "size": "1500 x 228 x 6.5+1.5mm",
    "lengthMm": 1500,
    "widthMm": 228,
    "thicknessMm": 8.0,
    "coreMm": 6.5,
    "padMm": 1.5,
    "veneerMm": null,
    "boardM2": 0.342,
    "boardsPerBox": 6,
    "m2PerBox": 2.052,
    "m2PerBoxPrinted": 2.052,
    "m2PerBoxDrifts": false,
    "surface": "Wood texture",
    "pricePerM2": 25.5
  },
  {
    "category": "hybrid",
    "categoryPrinted": "Hybrid",
    "range": "Titan Guard SPC Hybrid 10.5mm",
    "code": "9018-24",
    "colour": "Honey Maple",
    "size": "1800 x 230 x 9+1.5mm",
    "lengthMm": 1800,
    "widthMm": 230,
    "thicknessMm": 10.5,
    "coreMm": 9.0,
    "padMm": 1.5,
    "veneerMm": null,
    "boardM2": 0.414,
    "boardsPerBox": 3,
    "m2PerBox": 1.242,
    "m2PerBoxPrinted": 1.242,
    "m2PerBoxDrifts": false,
    "surface": "Wood texture",
    "pricePerM2": 29.9
  },
  {
    "category": "hybrid",
    "categoryPrinted": "Hybrid",
    "range": "Titan Guard SPC Hybrid 10.5mm",
    "code": "2372-1",
    "colour": "Alpine Gum",
    "size": "1800 x 230 x 9+1.5mm",
    "lengthMm": 1800,
    "widthMm": 230,
    "thicknessMm": 10.5,
    "coreMm": 9.0,
    "padMm": 1.5,
    "veneerMm": null,
    "boardM2": 0.414,
    "boardsPerBox": 3,
    "m2PerBox": 1.242,
    "m2PerBoxPrinted": 1.242,
    "m2PerBoxDrifts": false,
    "surface": "Wood texture",
    "pricePerM2": 29.9
  },
  {
    "category": "hybrid",
    "categoryPrinted": "Hybrid",
    "range": "Titan Guard SPC Hybrid 10.5mm",
    "code": "9018-1",
    "colour": "Natural Eucalyptus",
    "size": "1800 x 230 x 9+1.5mm",
    "lengthMm": 1800,
    "widthMm": 230,
    "thicknessMm": 10.5,
    "coreMm": 9.0,
    "padMm": 1.5,
    "veneerMm": null,
    "boardM2": 0.414,
    "boardsPerBox": 3,
    "m2PerBox": 1.242,
    "m2PerBoxPrinted": 1.242,
    "m2PerBoxDrifts": false,
    "surface": "Wood texture",
    "pricePerM2": 29.9
  },
  {
    "category": "hybrid",
    "categoryPrinted": "Hybrid",
    "range": "Titan Guard SPC Hybrid 10.5mm",
    "code": "9021-1",
    "colour": "Coastal Drift",
    "size": "1800 x 230 x 9+1.5mm",
    "lengthMm": 1800,
    "widthMm": 230,
    "thicknessMm": 10.5,
    "coreMm": 9.0,
    "padMm": 1.5,
    "veneerMm": null,
    "boardM2": 0.414,
    "boardsPerBox": 3,
    "m2PerBox": 1.242,
    "m2PerBoxPrinted": 1.242,
    "m2PerBoxDrifts": false,
    "surface": "Wood texture",
    "pricePerM2": 29.9
  },
  {
    "category": "hybrid",
    "categoryPrinted": "Hybrid",
    "range": "Titan Guard SPC Hybrid 10.5mm",
    "code": "9021-5",
    "colour": "Antique Oak",
    "size": "1800 x 230 x 9+1.5mm",
    "lengthMm": 1800,
    "widthMm": 230,
    "thicknessMm": 10.5,
    "coreMm": 9.0,
    "padMm": 1.5,
    "veneerMm": null,
    "boardM2": 0.414,
    "boardsPerBox": 3,
    "m2PerBox": 1.242,
    "m2PerBoxPrinted": 1.242,
    "m2PerBoxDrifts": false,
    "surface": "Wood texture",
    "pricePerM2": 29.9
  },
  {
    "category": "hybrid",
    "categoryPrinted": "Hybrid",
    "range": "Titan Guard SPC Hybrid 10.5mm",
    "code": "9021-10",
    "colour": "Snowy Ash",
    "size": "1800 x 230 x 9+1.5mm",
    "lengthMm": 1800,
    "widthMm": 230,
    "thicknessMm": 10.5,
    "coreMm": 9.0,
    "padMm": 1.5,
    "veneerMm": null,
    "boardM2": 0.414,
    "boardsPerBox": 3,
    "m2PerBox": 1.242,
    "m2PerBoxPrinted": 1.242,
    "m2PerBoxDrifts": false,
    "surface": "Wood texture",
    "pricePerM2": 29.9
  },
  {
    "category": "timber",
    "categoryPrinted": "Engineered Timber",
    "range": "Luminous Oak 15/2mm",
    "code": null,
    "colour": "Smokey Beige",
    "size": "1900 x 190 x 15/2mm",
    "lengthMm": 1900,
    "widthMm": 190,
    "thicknessMm": 15.0,
    "coreMm": null,
    "padMm": null,
    "veneerMm": 2.0,
    "boardM2": 0.361,
    "boardsPerBox": 6,
    "m2PerBox": 2.166,
    "m2PerBoxPrinted": 2.166,
    "m2PerBoxDrifts": false,
    "surface": "Timber Grade ABC+",
    "pricePerM2": 48.0
  },
  {
    "category": "timber",
    "categoryPrinted": "Engineered Timber",
    "range": "Luminous Oak 15/2mm",
    "code": null,
    "colour": "Classic Oak",
    "size": "1900 x 190 x 15/2mm",
    "lengthMm": 1900,
    "widthMm": 190,
    "thicknessMm": 15.0,
    "coreMm": null,
    "padMm": null,
    "veneerMm": 2.0,
    "boardM2": 0.361,
    "boardsPerBox": 6,
    "m2PerBox": 2.166,
    "m2PerBoxPrinted": 2.166,
    "m2PerBoxDrifts": false,
    "surface": "Timber Grade ABC+",
    "pricePerM2": 48.0
  },
  {
    "category": "timber",
    "categoryPrinted": "Engineered Timber",
    "range": "Luminous Oak 15/2mm",
    "code": null,
    "colour": "Snow Flurry",
    "size": "1900 x 190 x 15/2mm",
    "lengthMm": 1900,
    "widthMm": 190,
    "thicknessMm": 15.0,
    "coreMm": null,
    "padMm": null,
    "veneerMm": 2.0,
    "boardM2": 0.361,
    "boardsPerBox": 6,
    "m2PerBox": 2.166,
    "m2PerBoxPrinted": 2.166,
    "m2PerBoxDrifts": false,
    "surface": "Timber Grade ABC+",
    "pricePerM2": 48.0
  },
  {
    "category": "timber",
    "categoryPrinted": "Engineered Timber",
    "range": "Luminous Oak 15/2mm",
    "code": null,
    "colour": "Castle Blanc",
    "size": "1900 x 190 x 15/2mm",
    "lengthMm": 1900,
    "widthMm": 190,
    "thicknessMm": 15.0,
    "coreMm": null,
    "padMm": null,
    "veneerMm": 2.0,
    "boardM2": 0.361,
    "boardsPerBox": 6,
    "m2PerBox": 2.166,
    "m2PerBoxPrinted": 2.166,
    "m2PerBoxDrifts": false,
    "surface": "Timber Grade ABC+",
    "pricePerM2": 48.0
  },
  {
    "category": "timber",
    "categoryPrinted": "Engineered Timber",
    "range": "Luminous Oak 15/2mm",
    "code": null,
    "colour": "Maple Caramel",
    "size": "1900 x 190 x 15/2mm",
    "lengthMm": 1900,
    "widthMm": 190,
    "thicknessMm": 15.0,
    "coreMm": null,
    "padMm": null,
    "veneerMm": 2.0,
    "boardM2": 0.361,
    "boardsPerBox": 6,
    "m2PerBox": 2.166,
    "m2PerBoxPrinted": 2.166,
    "m2PerBoxDrifts": false,
    "surface": "Timber Grade ABC+",
    "pricePerM2": 48.0
  },
  {
    "category": "timber",
    "categoryPrinted": "Engineered Timber",
    "range": "Luminous Oak 15/2mm",
    "code": null,
    "colour": "Hazel Oak",
    "size": "1900 x 190 x 15/2mm",
    "lengthMm": 1900,
    "widthMm": 190,
    "thicknessMm": 15.0,
    "coreMm": null,
    "padMm": null,
    "veneerMm": 2.0,
    "boardM2": 0.361,
    "boardsPerBox": 6,
    "m2PerBox": 2.166,
    "m2PerBoxPrinted": 2.166,
    "m2PerBoxDrifts": false,
    "surface": "Timber Grade ABC+",
    "pricePerM2": 48.0
  },
  {
    "category": "timber",
    "categoryPrinted": "Engineered Timber",
    "range": "Luminous Oak 15/2mm",
    "code": null,
    "colour": "Rich Mocha",
    "size": "1900 x 190 x 15/2mm",
    "lengthMm": 1900,
    "widthMm": 190,
    "thicknessMm": 15.0,
    "coreMm": null,
    "padMm": null,
    "veneerMm": 2.0,
    "boardM2": 0.361,
    "boardsPerBox": 6,
    "m2PerBox": 2.166,
    "m2PerBoxPrinted": 2.166,
    "m2PerBoxDrifts": false,
    "surface": "Timber Grade ABC+",
    "pricePerM2": 48.0
  },
  {
    "category": "timber",
    "categoryPrinted": "Engineered Timber",
    "range": "Modern Engineered Timber / Oak 14/3mm",
    "code": null,
    "colour": "Natural Oak",
    "size": "1900 x 190 x 14/3mm",
    "lengthMm": 1900,
    "widthMm": 190,
    "thicknessMm": 14.0,
    "coreMm": null,
    "padMm": null,
    "veneerMm": 3.0,
    "boardM2": 0.361,
    "boardsPerBox": 8,
    "m2PerBox": 2.888,
    "m2PerBoxPrinted": 2.888,
    "m2PerBoxDrifts": false,
    "surface": "Timber Grade ABC+",
    "pricePerM2": 59.0
  },
  {
    "category": "timber",
    "categoryPrinted": "Engineered Timber",
    "range": "Modern Engineered Timber / Oak 14/3mm",
    "code": null,
    "colour": "White Sand",
    "size": "1900 x 190 x 14/3mm",
    "lengthMm": 1900,
    "widthMm": 190,
    "thicknessMm": 14.0,
    "coreMm": null,
    "padMm": null,
    "veneerMm": 3.0,
    "boardM2": 0.361,
    "boardsPerBox": 8,
    "m2PerBox": 2.888,
    "m2PerBoxPrinted": 2.888,
    "m2PerBoxDrifts": false,
    "surface": "Timber Grade ABC+",
    "pricePerM2": 59.0
  },
  {
    "category": "timber",
    "categoryPrinted": "Engineered Timber",
    "range": "Modern Engineered Timber / Oak 14/3mm",
    "code": null,
    "colour": "Dark Oak",
    "size": "1900 x 190 x 14/3mm",
    "lengthMm": 1900,
    "widthMm": 190,
    "thicknessMm": 14.0,
    "coreMm": null,
    "padMm": null,
    "veneerMm": 3.0,
    "boardM2": 0.361,
    "boardsPerBox": 8,
    "m2PerBox": 2.888,
    "m2PerBoxPrinted": 2.888,
    "m2PerBoxDrifts": false,
    "surface": "Timber Grade ABC+",
    "pricePerM2": 59.0
  },
  {
    "category": "timber",
    "categoryPrinted": "Engineered Timber",
    "range": "Modern Engineered Timber / Oak 14/3mm",
    "code": null,
    "colour": "Light Oak",
    "size": "1900 x 190 x 14/3mm",
    "lengthMm": 1900,
    "widthMm": 190,
    "thicknessMm": 14.0,
    "coreMm": null,
    "padMm": null,
    "veneerMm": 3.0,
    "boardM2": 0.361,
    "boardsPerBox": 8,
    "m2PerBox": 2.888,
    "m2PerBoxPrinted": 2.888,
    "m2PerBoxDrifts": false,
    "surface": "Timber Grade ABC+",
    "pricePerM2": 59.0
  },
  {
    "category": "timber",
    "categoryPrinted": "Engineered Timber",
    "range": "Modern Engineered Timber / Oak 14/3mm",
    "code": null,
    "colour": "Country Oak",
    "size": "2200 x 220 x 14/3mm",
    "lengthMm": 2200,
    "widthMm": 220,
    "thicknessMm": 14.0,
    "coreMm": null,
    "padMm": null,
    "veneerMm": 3.0,
    "boardM2": 0.484,
    "boardsPerBox": 6,
    "m2PerBox": 2.904,
    "m2PerBoxPrinted": 2.9,
    "m2PerBoxDrifts": true,
    "surface": "Timber Grade ABC+",
    "pricePerM2": 62.0
  },
  {
    "category": "timber",
    "categoryPrinted": "Engineered Timber",
    "range": "Modern Engineered Timber / Oak 14/3mm",
    "code": null,
    "colour": "Cream Oak",
    "size": "2200 x 220 x 14/3mm",
    "lengthMm": 2200,
    "widthMm": 220,
    "thicknessMm": 14.0,
    "coreMm": null,
    "padMm": null,
    "veneerMm": 3.0,
    "boardM2": 0.484,
    "boardsPerBox": 6,
    "m2PerBox": 2.904,
    "m2PerBoxPrinted": 2.9,
    "m2PerBoxDrifts": true,
    "surface": "Timber Grade ABC+",
    "pricePerM2": 62.0
  }
];

export const BP_ACCESSORIES: BigPandaAccessory[] = [
  {
    "item": "Scotia PVC/WPC",
    "size": "2400 x 22 x 12mm",
    "applies": "6.5mm SPC ONLY",
    "price": 4.8,
    "unitPrinted": "Length",
    "isUnderlay": false,
    "coverageM2": null,
    "perM2": null,
    "fitsRange": "Titan Guard SPC Hybrid 6.5mm",
    "matchColour": false,
    "multiLength": false
  },
  {
    "item": "Stair Nosing",
    "size": "2400 x 115 x 24mm",
    "applies": "All Laminate/SPC",
    "price": 27.5,
    "unitPrinted": "Length",
    "isUnderlay": false,
    "coverageM2": null,
    "perM2": null,
    "fitsRange": "",
    "matchColour": false,
    "multiLength": false
  },
  {
    "item": "L Angle Trim",
    "size": "2400mm (6.5mm & 10.5mm SPC); 2700mm (8mm only)",
    "applies": "Match Colour",
    "price": 7.7,
    "unitPrinted": "Length",
    "isUnderlay": false,
    "coverageM2": null,
    "perM2": null,
    "fitsRange": "",
    "matchColour": true,
    "multiLength": true
  },
  {
    "item": "Universal Trim",
    "size": "2700mm",
    "applies": "Match Colour",
    "price": 17.0,
    "unitPrinted": "Length",
    "isUnderlay": false,
    "coverageM2": null,
    "perM2": null,
    "fitsRange": "",
    "matchColour": true,
    "multiLength": false
  },
  {
    "item": "Reducer",
    "size": "2400mm",
    "applies": "Match Colour",
    "price": 20.5,
    "unitPrinted": "Length",
    "isUnderlay": false,
    "coverageM2": null,
    "perM2": null,
    "fitsRange": "",
    "matchColour": true,
    "multiLength": false
  },
  {
    "item": "SD Trade 2mm Underlay",
    "size": "50m\u00b2 roll",
    "applies": "Roll",
    "price": 40.0,
    "unitPrinted": "Roll",
    "isUnderlay": true,
    "coverageM2": 50.0,
    "perM2": 0.8,
    "fitsRange": "",
    "matchColour": false,
    "multiLength": false
  }
];
