/**
 * CHAPARRAL CARPETS -- GENERATED BY scripts/extract-chaparral.py. DO NOT EDIT BY HAND.
 *
 * Source: Chaparral_Carpets_Runable_Current_Ranges_2026_No_Natural_Choices_2rId6l.xlsx
 * 22 broadloom carpet colours, 3 ranges, all priced per LINEAL METRE
 * ex GST. Price list 1 June 2026 printed on every row, the only date in the file.
 *
 * FOUR THINGS THIS FILE CARRIES THAT CHANGE A QUOTE
 * 1. THE 20 LM BREAK IS REAL AND IT IS A CLIFF. Under 20.00 lm pays the cut
 *    rate, 20.00 lm and over pays the roll rate, and the discount applies to
 *    the WHOLE quantity. So 19 lm costs MORE than 20 lm on all three ranges --
 *    $132.00 more on Apartment 2. Modelled as a real
 *    roll/cut split so resolveRollCut says so at quote time.
 * 2. THE BREAK IS A FLAT $10.00/lm ON EVERY RANGE, not a percentage -- worth
 *    14.7% on Apartment 2 and only 7.2% on Outback. The prize is
 *    biggest at the BUDGET end, the opposite of the usual assumption.
 * 3. ROLL WIDTH IS 3.6m ON EVERY RANGE, AND IT IS NOT FROM THE FILE --
 *    Damien confirmed it. That is what makes lm -> m2 possible here, so every
 *    range carries a DERIVED per-m2 rate too. Note 3.6m is narrower than the
 *    3.66m much of the trade rolls. ROLL LENGTH is still unstated, but that
 *    no longer blocks the costing now baling is per order, not per roll.
 * 4. TWO RANGES ARE DELIBERATELY ABSENT -- Natural Direction and Brompton. See
 *    CHAPARRAL_EXCLUDED_RANGES; the source removed both and carries no price
 *    for either.
 */

export type ChaparralRow = {
  range: string;
  colour: string;
  /** Rate under 20 lm. HIGHER than the roll rate -- a cut premium. */
  cutPerLm: number;
  /** Rate at or above 20 lm. This is the `costPrice`. */
  rollPerLm: number;
  url: string;
  variantKey: string;
};

export type ChaparralRange = {
  range: string;
  cutPerLm: number;
  rollPerLm: number;
  url: string;
  colours: number;
  /** Flat dollars off per lm at the break. Identical on every range. */
  discountPerLm: number;
  discountPct: number;
  /** Below this many lm, buying the full 20 lm costs LESS than the short run. */
  breakEvenLm: number;
  /** Cost of 20 lm at the roll rate. */
  fullBreakCost: number;
  /** Dollars WASTED ordering 19 lm instead of 20 lm. */
  cliffAt19Lm: number;
  /** What the $2.00/lm fuel surcharge is worth against this range's roll rate. */
  fuelPctOfRoll: number;
  /** DERIVED off the 3.6m width, never a Chaparral figure. They publish lm only. */
  cutPerM2: number;
  rollPerM2: number;
};

export const CHAPARRAL_SOURCE = "Chaparral_Carpets_Runable_Current_Ranges_2026_No_Natural_Choices_2rId6l.xlsx";
export const CHAPARRAL_SUPPLIER_NAME = "Chaparral Carpets";
export const CHAPARRAL_PRICE_LIST_DATE = "2026-06-01";
export const CHAPARRAL_PRICE_LIST_PRINTED = "1 June 2026";
export const CHAPARRAL_PRICE_STATUS = "Current price";
export const CHAPARRAL_UNIT = "lineal metre";

/**
 * Roll width, metres. NOT FROM THE WORKBOOK -- Damien confirmed it, and
 * CHAPARRAL_ROLL_WIDTH_SOURCE records that so it is never mistaken for a
 * printed spec. All carpet is priced per LINEAL metre, so this is the only way
 * a Chaparral line converts to the m2 a floor is measured in.
 */
export const CHAPARRAL_ROLL_WIDTH_M = 3.6;
export const CHAPARRAL_ROLL_WIDTH_SOURCE = "Damien, confirmed directly. Not printed in the workbook.";
/** Much of the trade rolls 3.66m. Chaparral is narrower -- confirm before a big order. */
export const CHAPARRAL_TRADE_STANDARD_WIDTH_M = 3.66;

/** The cut/roll threshold in lineal metres, off the source's column headings. */
export const CHAPARRAL_BREAK_LM = 20.0;
/** Flat dollars off per lm at or above the break -- identical on all three ranges. */
export const CHAPARRAL_BREAK_DISCOUNT_PER_LM = 10.0;

/** $2.00 per lineal metre, temporary, until further notice. NOT in any costPrice. */
export const CHAPARRAL_FUEL = { amount: 2.0, unit: "per lineal metre" };
/**
 * $20.00 baling. `unit` is the workbook's own wording, extracted verbatim, and
 * the workbook is WRONG: Damien confirms it is charged once per order, flat,
 * however many rolls ship. Use CHAPARRAL_BALING_ACTUAL_BASIS, and note the fee
 * rule in seed-suppliers.ts is seeded with basis "order" on purpose.
 */
export const CHAPARRAL_BALING = { amount: 20.0, unit: "per roll" };
/** Damien's correction to the line above. This is what the costing uses. */
export const CHAPARRAL_BALING_ACTUAL_BASIS = "order";
export const CHAPARRAL_BALING_BASIS_SOURCE =
  "Damien, confirmed directly. The workbook says per roll; it is charged once per order.";

/**
 * Ranges the source file removed, kept here so their absence reads as a
 * decision. Damien's message named both and quoted rates for them; the
 * workbook carries no price row for either, so nothing was seeded. If either
 * is still orderable, get a current sheet from Chaparral and add it.
 */
export const CHAPARRAL_EXCLUDED_RANGES: Array<{
  range: string;
  reason: string;
  quotedInChat: string;
}> = [{"range": "Natural Direction", "reason": "No longer shown on Chaparral's website. Removed by the source file's Supplier Rules sheet; no price row exists anywhere in the workbook.", "quotedInChat": "$88.00 cut / $78.00 roll per lm"}, {"range": "Brompton", "reason": "No longer shown on Chaparral's website. Removed by the source file's Supplier Rules sheet; no price row exists anywhere in the workbook.", "quotedInChat": "$118.00 cut / $108.00 roll per lm"}];

/** The source workbook's own Supplier Rules sheet, verbatim. */
export const CHAPARRAL_RULES: Array<{ rule: string; setting: string }> = [{"rule": "Range filtering", "setting": "Only keep ranges currently shown on Chaparral website. Natural Direction and Brompton removed."}, {"rule": "Cut pricing rule", "setting": "Under 20.00 broadloom lineal metres = Cut Length price. 20.00 lm and over = Roll price."}, {"rule": "Fuel surcharge", "setting": "$2.00 per lineal metre, temporary, active until further notice."}, {"rule": "Baling", "setting": "$20.00 per roll."}, {"rule": "Freight / delivery", "setting": "Do not apply Chaparral direct delivery charge. Terra uses Jocks Transport / on-forwarder; transport cost handled separately."}, {"rule": "GST", "setting": "All stored prices are ex GST."}];

export const CHAPARRAL_RANGES: ChaparralRange[] = [
  {"range": "Apartment 2", "cutPerLm": 68.0, "rollPerLm": 58.0, "url": "https://chaparral.com.au/apartment-2/", "colours": 9, "discountPerLm": 10.0, "discountPct": 14.7, "breakEvenLm": 17.06, "fullBreakCost": 1160.0, "cliffAt19Lm": 132.0, "fuelPctOfRoll": 3.4, "cutPerM2": 18.89, "rollPerM2": 16.11},
  {"range": "Kingston", "cutPerLm": 89.0, "rollPerLm": 79.0, "url": "https://chaparral.com.au/kingston/", "colours": 7, "discountPerLm": 10.0, "discountPct": 11.2, "breakEvenLm": 17.75, "fullBreakCost": 1580.0, "cliffAt19Lm": 111.0, "fuelPctOfRoll": 2.5, "cutPerM2": 24.72, "rollPerM2": 21.94},
  {"range": "Outback", "cutPerLm": 138.0, "rollPerLm": 128.0, "url": "https://chaparral.com.au/carpet-range/", "colours": 6, "discountPerLm": 10.0, "discountPct": 7.2, "breakEvenLm": 18.55, "fullBreakCost": 2560.0, "cliffAt19Lm": 62.0, "fuelPctOfRoll": 1.6, "cutPerM2": 38.33, "rollPerM2": 35.56},
];

export const CHAPARRAL_BROADLOOM: ChaparralRow[] = [
  {"range": "Apartment 2", "colour": "Red", "cutPerLm": 68.0, "rollPerLm": 58.0, "url": "https://chaparral.com.au/apartment-2/", "variantKey": "chaparral|carpet|apartment-2|red"},
  {"range": "Apartment 2", "colour": "Marlin", "cutPerLm": 68.0, "rollPerLm": 58.0, "url": "https://chaparral.com.au/apartment-2/", "variantKey": "chaparral|carpet|apartment-2|marlin"},
  {"range": "Apartment 2", "colour": "Pewter", "cutPerLm": 68.0, "rollPerLm": 58.0, "url": "https://chaparral.com.au/apartment-2/", "variantKey": "chaparral|carpet|apartment-2|pewter"},
  {"range": "Apartment 2", "colour": "Silhouette", "cutPerLm": 68.0, "rollPerLm": 58.0, "url": "https://chaparral.com.au/apartment-2/", "variantKey": "chaparral|carpet|apartment-2|silhouette"},
  {"range": "Apartment 2", "colour": "Slate", "cutPerLm": 68.0, "rollPerLm": 58.0, "url": "https://chaparral.com.au/apartment-2/", "variantKey": "chaparral|carpet|apartment-2|slate"},
  {"range": "Apartment 2", "colour": "Violet", "cutPerLm": 68.0, "rollPerLm": 58.0, "url": "https://chaparral.com.au/apartment-2/", "variantKey": "chaparral|carpet|apartment-2|violet"},
  {"range": "Apartment 2", "colour": "Clay", "cutPerLm": 68.0, "rollPerLm": 58.0, "url": "https://chaparral.com.au/apartment-2/", "variantKey": "chaparral|carpet|apartment-2|clay"},
  {"range": "Apartment 2", "colour": "Fawn", "cutPerLm": 68.0, "rollPerLm": 58.0, "url": "https://chaparral.com.au/apartment-2/", "variantKey": "chaparral|carpet|apartment-2|fawn"},
  {"range": "Apartment 2", "colour": "Gull", "cutPerLm": 68.0, "rollPerLm": 58.0, "url": "https://chaparral.com.au/apartment-2/", "variantKey": "chaparral|carpet|apartment-2|gull"},
  {"range": "Kingston", "colour": "Ash", "cutPerLm": 89.0, "rollPerLm": 79.0, "url": "https://chaparral.com.au/kingston/", "variantKey": "chaparral|carpet|kingston|ash"},
  {"range": "Kingston", "colour": "Cinder", "cutPerLm": 89.0, "rollPerLm": 79.0, "url": "https://chaparral.com.au/kingston/", "variantKey": "chaparral|carpet|kingston|cinder"},
  {"range": "Kingston", "colour": "Dusk", "cutPerLm": 89.0, "rollPerLm": 79.0, "url": "https://chaparral.com.au/kingston/", "variantKey": "chaparral|carpet|kingston|dusk"},
  {"range": "Kingston", "colour": "Ice", "cutPerLm": 89.0, "rollPerLm": 79.0, "url": "https://chaparral.com.au/kingston/", "variantKey": "chaparral|carpet|kingston|ice"},
  {"range": "Kingston", "colour": "Midnight", "cutPerLm": 89.0, "rollPerLm": 79.0, "url": "https://chaparral.com.au/kingston/", "variantKey": "chaparral|carpet|kingston|midnight"},
  {"range": "Kingston", "colour": "Titan", "cutPerLm": 89.0, "rollPerLm": 79.0, "url": "https://chaparral.com.au/kingston/", "variantKey": "chaparral|carpet|kingston|titan"},
  {"range": "Kingston", "colour": "Ivory", "cutPerLm": 89.0, "rollPerLm": 79.0, "url": "https://chaparral.com.au/kingston/", "variantKey": "chaparral|carpet|kingston|ivory"},
  {"range": "Outback", "colour": "Bronze", "cutPerLm": 138.0, "rollPerLm": 128.0, "url": "https://chaparral.com.au/carpet-range/", "variantKey": "chaparral|carpet|outback|bronze"},
  {"range": "Outback", "colour": "Cloud", "cutPerLm": 138.0, "rollPerLm": 128.0, "url": "https://chaparral.com.au/carpet-range/", "variantKey": "chaparral|carpet|outback|cloud"},
  {"range": "Outback", "colour": "Granite", "cutPerLm": 138.0, "rollPerLm": 128.0, "url": "https://chaparral.com.au/carpet-range/", "variantKey": "chaparral|carpet|outback|granite"},
  {"range": "Outback", "colour": "Opal", "cutPerLm": 138.0, "rollPerLm": 128.0, "url": "https://chaparral.com.au/carpet-range/", "variantKey": "chaparral|carpet|outback|opal"},
  {"range": "Outback", "colour": "Quartz", "cutPerLm": 138.0, "rollPerLm": 128.0, "url": "https://chaparral.com.au/carpet-range/", "variantKey": "chaparral|carpet|outback|quartz"},
  {"range": "Outback", "colour": "Smoke", "cutPerLm": 138.0, "rollPerLm": 128.0, "url": "https://chaparral.com.au/carpet-range/", "variantKey": "chaparral|carpet|outback|smoke"},
];
