/**
 * Dunlop Flooring boxed hard-flooring products from the owner-supplied workbook.
 * Scope is exactly the workbook's "Boxed Products Master" sheet: flooring only.
 * Accessories, stair noses, adhesives, end profiles, scotia and T trims are excluded.
 */
export const DUNLOP_SOURCE = "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026";
export const DUNLOP_PRICE_LIST_DATE = "2026-09-30";

export type DunlopRow = {
  supplier: string;
  productType: string;
  range: string;
  code: string | null;
  colour: string;
  m2PerBox: number;
  pricePerM2: number;
  palletM2: number | null;
  size: string | null;
  thicknessMm: number | null;
  sourceWorkbook: string;
  notes: string | null;
};

export const DUNLOP_BOXED_PRODUCTS: DunlopRow[] = [
  {
    "supplier": "Dunlop Flooring",
    "productType": "Engineered Timber",
    "range": "Australian Species Engineered Timber",
    "code": "820601",
    "colour": "HR ENG WOOD BLACKBUTT",
    "m2PerBox": 2.089,
    "pricePerM2": 76.95,
    "palletM2": 116.984,
    "size": null,
    "thicknessMm": null,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "Multi-layered Eucalyptus; 8 pieces/carton; 56 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Engineered Timber",
    "range": "Australian Species Engineered Timber",
    "code": "820602",
    "colour": "HR ENG WOOD SPOTTED GUM",
    "m2PerBox": 2.089,
    "pricePerM2": 76.95,
    "palletM2": 116.984,
    "size": null,
    "thicknessMm": null,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "Multi-layered Eucalyptus; 8 pieces/carton; 56 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Engineered Timber",
    "range": "Engineered Timber Rustic Oak (T&G)",
    "code": "820204",
    "colour": "WHITE SMK-SY",
    "m2PerBox": 2.888,
    "pricePerM2": 62.85,
    "palletM2": null,
    "size": null,
    "thicknessMm": null,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": null
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Engineered Timber",
    "range": "Heartridge Engineered Timber - Riviera Oak",
    "code": "825101",
    "colour": "LAUREL",
    "m2PerBox": 2.888,
    "pricePerM2": 68.95,
    "palletM2": 115.52,
    "size": null,
    "thicknessMm": null,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "Spruce/Pine timber core; 8 pieces/carton; 40 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Engineered Timber",
    "range": "Heartridge Engineered Timber - Riviera Oak",
    "code": "825102",
    "colour": "ACACIA",
    "m2PerBox": 2.888,
    "pricePerM2": 68.95,
    "palletM2": 115.52,
    "size": null,
    "thicknessMm": null,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "Spruce/Pine timber core; 8 pieces/carton; 40 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Engineered Timber",
    "range": "Heartridge Engineered Timber - Riviera Oak",
    "code": "825103",
    "colour": "AMBERWOOD",
    "m2PerBox": 2.888,
    "pricePerM2": 68.95,
    "palletM2": 115.52,
    "size": null,
    "thicknessMm": null,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "Spruce/Pine timber core; 8 pieces/carton; 40 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Engineered Timber",
    "range": "Heartridge Engineered Timber - Riviera Oak",
    "code": "825104",
    "colour": "BIRCH",
    "m2PerBox": 2.888,
    "pricePerM2": 68.95,
    "palletM2": 115.52,
    "size": null,
    "thicknessMm": null,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "Spruce/Pine timber core; 8 pieces/carton; 40 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Engineered Timber",
    "range": "Heartridge Engineered Timber - Riviera Oak",
    "code": "825105",
    "colour": "ALMOND",
    "m2PerBox": 2.888,
    "pricePerM2": 68.95,
    "palletM2": 115.52,
    "size": null,
    "thicknessMm": null,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "Spruce/Pine timber core; 8 pieces/carton; 40 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Engineered Timber",
    "range": "Heartridge Engineered Timber - Riviera Oak",
    "code": "825106",
    "colour": "KENTIA OAK",
    "m2PerBox": 2.888,
    "pricePerM2": 68.95,
    "palletM2": 115.52,
    "size": null,
    "thicknessMm": null,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "Spruce/Pine timber core; 8 pieces/carton; 40 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Engineered Timber",
    "range": "Heartridge Engineered Timber - Riviera Oak",
    "code": "825107",
    "colour": "SEQUOIA",
    "m2PerBox": 2.888,
    "pricePerM2": 68.95,
    "palletM2": 115.52,
    "size": null,
    "thicknessMm": null,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "Spruce/Pine timber core; 8 pieces/carton; 40 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Engineered Timber",
    "range": "Heartridge Engineered Timber - Riviera Oak",
    "code": "825108",
    "colour": "SYCAMORE",
    "m2PerBox": 2.888,
    "pricePerM2": 68.95,
    "palletM2": 115.52,
    "size": null,
    "thicknessMm": null,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "Spruce/Pine timber core; 8 pieces/carton; 40 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Engineered Timber",
    "range": "Heartridge Engineered Timber - Riviera Oak",
    "code": "825109",
    "colour": "ECRU",
    "m2PerBox": 2.888,
    "pricePerM2": 68.95,
    "palletM2": 115.52,
    "size": null,
    "thicknessMm": null,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "Spruce/Pine timber core; 8 pieces/carton; 40 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Engineered Timber",
    "range": "Heartridge Engineered Timber - Riviera Oak",
    "code": "825110",
    "colour": "EBONY",
    "m2PerBox": 2.888,
    "pricePerM2": 68.95,
    "palletM2": 115.52,
    "size": null,
    "thicknessMm": null,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "Spruce/Pine timber core; 8 pieces/carton; 40 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Hybrid",
    "range": "Australian Hybrid",
    "code": "835401",
    "colour": "NORTHERN SPOTTED GUM",
    "m2PerBox": 1.656,
    "pricePerM2": 38.5,
    "palletM2": 99.36,
    "size": "180 x 1840 mm",
    "thicknessMm": 7,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "60 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Hybrid",
    "range": "Australian Hybrid",
    "code": "835402",
    "colour": "SOUTHERN SPOTTED GUM",
    "m2PerBox": 1.656,
    "pricePerM2": 38.5,
    "palletM2": 99.36,
    "size": "180 x 1840 mm",
    "thicknessMm": 7,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "60 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Hybrid",
    "range": "Australian Hybrid",
    "code": "835403",
    "colour": "BLACKBUTT",
    "m2PerBox": 1.656,
    "pricePerM2": 38.5,
    "palletM2": 99.36,
    "size": "180 x 1840 mm",
    "thicknessMm": 7,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "60 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Hybrid",
    "range": "Australian Hybrid",
    "code": "835404",
    "colour": "TASMANIAN OAK",
    "m2PerBox": 1.656,
    "pricePerM2": 38.5,
    "palletM2": 99.36,
    "size": "180 x 1840 mm",
    "thicknessMm": 7,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "60 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Hybrid",
    "range": "Australian Hybrid",
    "code": "835405",
    "colour": "JARRAH",
    "m2PerBox": 1.656,
    "pricePerM2": 38.5,
    "palletM2": 99.36,
    "size": "180 x 1840 mm",
    "thicknessMm": 7,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "60 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Hybrid",
    "range": "Australian Hybrid",
    "code": "835406",
    "colour": "BRUSHBOX",
    "m2PerBox": 1.656,
    "pricePerM2": 38.5,
    "palletM2": 99.36,
    "size": "180 x 1840 mm",
    "thicknessMm": 7,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "60 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Hybrid",
    "range": "Highland Oak Hybrid",
    "code": "835008",
    "colour": "REGAL COVE",
    "m2PerBox": 2.098,
    "pricePerM2": 38.5,
    "palletM2": 100.704,
    "size": "228 x 1840 mm",
    "thicknessMm": 7,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "48 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Hybrid",
    "range": "Highland Oak Hybrid",
    "code": "835009",
    "colour": "AUTUMN HRVEST",
    "m2PerBox": 2.098,
    "pricePerM2": 38.5,
    "palletM2": 100.704,
    "size": "228 x 1840 mm",
    "thicknessMm": 7,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "48 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Hybrid",
    "range": "Highland Oak Hybrid",
    "code": "835010",
    "colour": "ARLINGTON GRV",
    "m2PerBox": 2.098,
    "pricePerM2": 38.5,
    "palletM2": 100.704,
    "size": "228 x 1840 mm",
    "thicknessMm": 7,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "48 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Hybrid",
    "range": "Highland Oak Hybrid",
    "code": "835011",
    "colour": "SMOKEY ISLE",
    "m2PerBox": 2.098,
    "pricePerM2": 38.5,
    "palletM2": 100.704,
    "size": "228 x 1840 mm",
    "thicknessMm": 7,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "48 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Hybrid",
    "range": "Highland Oak Hybrid",
    "code": "835012",
    "colour": "STERLING FALL",
    "m2PerBox": 2.098,
    "pricePerM2": 38.5,
    "palletM2": 100.704,
    "size": "228 x 1840 mm",
    "thicknessMm": 7,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "48 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Hybrid",
    "range": "Highland Oak Hybrid",
    "code": "835013",
    "colour": "KEMPTON OAK",
    "m2PerBox": 2.098,
    "pricePerM2": 38.5,
    "palletM2": 100.704,
    "size": "228 x 1840 mm",
    "thicknessMm": 7,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "48 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Hybrid",
    "range": "Highland Oak Hybrid",
    "code": "835014",
    "colour": "DALMORE ASH",
    "m2PerBox": 2.098,
    "pricePerM2": 38.5,
    "palletM2": 100.704,
    "size": "228 x 1840 mm",
    "thicknessMm": 7,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "48 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Hybrid",
    "range": "Highland Oak Hybrid",
    "code": "835015",
    "colour": "WOODFORD GLEN",
    "m2PerBox": 2.098,
    "pricePerM2": 38.5,
    "palletM2": 100.704,
    "size": "228 x 1840 mm",
    "thicknessMm": 7,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "48 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Hybrid",
    "range": "Natural Oak Hybrid",
    "code": "835601",
    "colour": "NEVADA PLAIN",
    "m2PerBox": 1.656,
    "pricePerM2": 38.5,
    "palletM2": 99.36,
    "size": "180 x 1840 mm",
    "thicknessMm": 7,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "60 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Hybrid",
    "range": "Natural Oak Hybrid",
    "code": "835602",
    "colour": "SAHARA DUNE",
    "m2PerBox": 1.656,
    "pricePerM2": 38.5,
    "palletM2": 99.36,
    "size": "180 x 1840 mm",
    "thicknessMm": 7,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "60 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Hybrid",
    "range": "Natural Oak Hybrid",
    "code": "835603",
    "colour": "PROVINCIAL GREY",
    "m2PerBox": 1.656,
    "pricePerM2": 38.5,
    "palletM2": 99.36,
    "size": "180 x 1840 mm",
    "thicknessMm": 7,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "60 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Hybrid",
    "range": "Natural Oak Hybrid",
    "code": "835604",
    "colour": "OSLO WHITE",
    "m2PerBox": 1.656,
    "pricePerM2": 38.5,
    "palletM2": 99.36,
    "size": "180 x 1840 mm",
    "thicknessMm": 7,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "60 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Hybrid",
    "range": "Natural Oak Hybrid",
    "code": "835605",
    "colour": "MOONSTONE",
    "m2PerBox": 1.656,
    "pricePerM2": 38.5,
    "palletM2": 99.36,
    "size": "180 x 1840 mm",
    "thicknessMm": 7,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "60 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Hybrid",
    "range": "Natural Oak Hybrid",
    "code": "835606",
    "colour": "TEMPEST",
    "m2PerBox": 1.656,
    "pricePerM2": 38.5,
    "palletM2": 99.36,
    "size": "180 x 1840 mm",
    "thicknessMm": 7,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "60 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Hybrid",
    "range": "Summerhill Hybrid",
    "code": "835701",
    "colour": "PHANTOM",
    "m2PerBox": 1.757,
    "pricePerM2": 29.95,
    "palletM2": 114.205,
    "size": "180 x 1220 mm",
    "thicknessMm": 6,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "65 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Hybrid",
    "range": "Summerhill Hybrid",
    "code": "835702",
    "colour": "WILLOW GREY",
    "m2PerBox": 1.757,
    "pricePerM2": 29.95,
    "palletM2": 114.205,
    "size": "180 x 1220 mm",
    "thicknessMm": 6,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "65 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Hybrid",
    "range": "Summerhill Hybrid",
    "code": "835703",
    "colour": "SMOKEY QUARTZ",
    "m2PerBox": 1.757,
    "pricePerM2": 29.95,
    "palletM2": 114.205,
    "size": "180 x 1220 mm",
    "thicknessMm": 6,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "65 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Hybrid",
    "range": "Summerhill Hybrid",
    "code": "835704",
    "colour": "MERINO MIST",
    "m2PerBox": 1.757,
    "pricePerM2": 29.95,
    "palletM2": 114.205,
    "size": "180 x 1220 mm",
    "thicknessMm": 6,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "65 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Hybrid",
    "range": "Summerhill Hybrid",
    "code": "835705",
    "colour": "BURLYWOOD",
    "m2PerBox": 1.757,
    "pricePerM2": 29.95,
    "palletM2": 114.205,
    "size": "180 x 1220 mm",
    "thicknessMm": 6,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "65 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Hybrid",
    "range": "Summerhill Hybrid",
    "code": "835706",
    "colour": "BROWN MAPLE",
    "m2PerBox": 1.757,
    "pricePerM2": 29.95,
    "palletM2": 114.205,
    "size": "180 x 1220 mm",
    "thicknessMm": 6,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "65 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Hybrid",
    "range": "Summerhill Hybrid",
    "code": "835707",
    "colour": "VIENNA OAK",
    "m2PerBox": 1.757,
    "pricePerM2": 29.95,
    "palletM2": 114.205,
    "size": "180 x 1220 mm",
    "thicknessMm": 6,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "65 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Hybrid",
    "range": "Summerhill Hybrid",
    "code": "835708",
    "colour": "BLACKBUTT",
    "m2PerBox": 1.757,
    "pricePerM2": 29.95,
    "palletM2": 114.205,
    "size": "180 x 1220 mm",
    "thicknessMm": 6,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "65 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Hybrid",
    "range": "Summerhill Hybrid",
    "code": "835709",
    "colour": "SAFARI SUN",
    "m2PerBox": 1.757,
    "pricePerM2": 29.95,
    "palletM2": 114.205,
    "size": "180 x 1220 mm",
    "thicknessMm": 6,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "65 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Hybrid",
    "range": "Summerhill Hybrid",
    "code": "835710",
    "colour": "BRAIDWOOD",
    "m2PerBox": 1.757,
    "pricePerM2": 29.95,
    "palletM2": 114.205,
    "size": "180 x 1220 mm",
    "thicknessMm": 6,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "65 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Hybrid",
    "range": "Summerhill Hybrid",
    "code": "835711",
    "colour": "BURLAP HUE",
    "m2PerBox": 1.757,
    "pricePerM2": 29.95,
    "palletM2": 114.205,
    "size": "180 x 1220 mm",
    "thicknessMm": 6,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "65 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Hybrid",
    "range": "Summerhill Hybrid",
    "code": "835712",
    "colour": "SPOTTED GUM",
    "m2PerBox": 1.757,
    "pricePerM2": 29.95,
    "palletM2": 114.205,
    "size": "180 x 1220 mm",
    "thicknessMm": 6,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "65 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Laminate",
    "range": "Forestbrook Laminate Collection",
    "code": "810201",
    "colour": "SPOTTED GUM",
    "m2PerBox": 1.764,
    "pricePerM2": 22.95,
    "palletM2": 105.84,
    "size": "196 x 1500 mm",
    "thicknessMm": 8,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "60 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Laminate",
    "range": "Forestbrook Laminate Collection",
    "code": "810202",
    "colour": "SHADOWED SPOTTED GUM",
    "m2PerBox": 1.764,
    "pricePerM2": 22.95,
    "palletM2": 105.84,
    "size": "196 x 1500 mm",
    "thicknessMm": 8,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "60 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Laminate",
    "range": "Forestbrook Laminate Collection",
    "code": "810203",
    "colour": "BLACKBUTT",
    "m2PerBox": 1.764,
    "pricePerM2": 22.95,
    "palletM2": 105.84,
    "size": "196 x 1500 mm",
    "thicknessMm": 8,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "60 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Laminate",
    "range": "Forestbrook Laminate Collection",
    "code": "810204",
    "colour": "COASTAL BLACKBUTT",
    "m2PerBox": 1.764,
    "pricePerM2": 22.95,
    "palletM2": 105.84,
    "size": "196 x 1500 mm",
    "thicknessMm": 8,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "60 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Laminate",
    "range": "Forestbrook Laminate Collection",
    "code": "810205",
    "colour": "MANGROVE",
    "m2PerBox": 1.764,
    "pricePerM2": 22.95,
    "palletM2": 105.84,
    "size": "196 x 1500 mm",
    "thicknessMm": 8,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "60 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Laminate",
    "range": "Forestbrook Laminate Collection",
    "code": "810206",
    "colour": "OAKRIDGE",
    "m2PerBox": 1.764,
    "pricePerM2": 22.95,
    "palletM2": 105.84,
    "size": "196 x 1500 mm",
    "thicknessMm": 8,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "60 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Laminate",
    "range": "Forestbrook Laminate Collection",
    "code": "810207",
    "colour": "WOODLAND",
    "m2PerBox": 1.764,
    "pricePerM2": 22.95,
    "palletM2": 105.84,
    "size": "196 x 1500 mm",
    "thicknessMm": 8,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "60 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Laminate",
    "range": "Forestbrook Laminate Collection",
    "code": "810208",
    "colour": "PINECREST",
    "m2PerBox": 1.764,
    "pricePerM2": 22.95,
    "palletM2": 105.84,
    "size": "196 x 1500 mm",
    "thicknessMm": 8,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "60 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Laminate",
    "range": "Forestbrook Laminate Collection",
    "code": "810209",
    "colour": "PALMSTONE",
    "m2PerBox": 1.764,
    "pricePerM2": 22.95,
    "palletM2": 105.84,
    "size": "196 x 1500 mm",
    "thicknessMm": 8,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "60 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Laminate",
    "range": "Forestbrook Laminate Collection",
    "code": "810210",
    "colour": "FERNWOOD",
    "m2PerBox": 1.764,
    "pricePerM2": 22.95,
    "palletM2": 105.84,
    "size": "196 x 1500 mm",
    "thicknessMm": 8,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "60 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Laminate",
    "range": "Riverfields 12mm Laminate Collection",
    "code": "810301",
    "colour": "MILLSTONE",
    "m2PerBox": 2.077,
    "pricePerM2": 28.95,
    "palletM2": 99.696,
    "size": "236 x 2200 mm",
    "thicknessMm": 12,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "48 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Laminate",
    "range": "Riverfields 12mm Laminate Collection",
    "code": "810302",
    "colour": "GREIGE",
    "m2PerBox": 2.077,
    "pricePerM2": 28.95,
    "palletM2": 99.696,
    "size": "236 x 2200 mm",
    "thicknessMm": 12,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "48 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Laminate",
    "range": "Riverfields 12mm Laminate Collection",
    "code": "810303",
    "colour": "COBBLESTONE",
    "m2PerBox": 2.077,
    "pricePerM2": 28.95,
    "palletM2": 99.696,
    "size": "236 x 2200 mm",
    "thicknessMm": 12,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "48 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Laminate",
    "range": "Riverfields 12mm Laminate Collection",
    "code": "810304",
    "colour": "MAPLE SPRING",
    "m2PerBox": 2.077,
    "pricePerM2": 28.95,
    "palletM2": 99.696,
    "size": "236 x 2200 mm",
    "thicknessMm": 12,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "48 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Laminate",
    "range": "Riverfields 12mm Laminate Collection",
    "code": "810305",
    "colour": "AMARETTO",
    "m2PerBox": 2.077,
    "pricePerM2": 28.95,
    "palletM2": 99.696,
    "size": "236 x 2200 mm",
    "thicknessMm": 12,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "48 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Laminate",
    "range": "Riverfields 12mm Laminate Collection",
    "code": "810306",
    "colour": "BARN OAK",
    "m2PerBox": 2.077,
    "pricePerM2": 28.95,
    "palletM2": 99.696,
    "size": "236 x 2200 mm",
    "thicknessMm": 12,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "48 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Laminate",
    "range": "Riverfields 12mm Laminate Collection",
    "code": "810307",
    "colour": "SUMMER SUN",
    "m2PerBox": 2.077,
    "pricePerM2": 28.95,
    "palletM2": 99.696,
    "size": "236 x 2200 mm",
    "thicknessMm": 12,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "48 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Laminate",
    "range": "Riverfields 12mm Laminate Collection",
    "code": "810308",
    "colour": "REGAL SAND",
    "m2PerBox": 2.077,
    "pricePerM2": 28.95,
    "palletM2": 99.696,
    "size": "236 x 2200 mm",
    "thicknessMm": 12,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "48 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Laminate",
    "range": "Riverfields 12mm Laminate Collection",
    "code": "810309",
    "colour": "CARBON OAK",
    "m2PerBox": 2.077,
    "pricePerM2": 28.95,
    "palletM2": 99.696,
    "size": "236 x 2200 mm",
    "thicknessMm": 12,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "48 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Laminate",
    "range": "Riverfields 12mm Laminate Collection",
    "code": "810310",
    "colour": "GALWAY",
    "m2PerBox": 2.077,
    "pricePerM2": 28.95,
    "palletM2": 99.696,
    "size": "236 x 2200 mm",
    "thicknessMm": 12,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "48 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Laminate",
    "range": "Riverfields 12mm Laminate Collection",
    "code": "810311",
    "colour": "BLACKBUTT",
    "m2PerBox": 2.077,
    "pricePerM2": 28.95,
    "palletM2": 99.696,
    "size": "236 x 2200 mm",
    "thicknessMm": 12,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "48 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Laminate",
    "range": "Riverfields 12mm Laminate Collection",
    "code": "810312",
    "colour": "SPOTTED GUM",
    "m2PerBox": 2.077,
    "pricePerM2": 28.95,
    "palletM2": 99.696,
    "size": "236 x 2200 mm",
    "thicknessMm": 12,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "48 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Laminate",
    "range": "Riverfields 8mm Laminate Collection",
    "code": "810101",
    "colour": "MILLSTONE",
    "m2PerBox": 1.907,
    "pricePerM2": 19.95,
    "palletM2": 133.49,
    "size": "196 x 1216 mm",
    "thicknessMm": 8,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "70 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Laminate",
    "range": "Riverfields 8mm Laminate Collection",
    "code": "810102",
    "colour": "GREIGE",
    "m2PerBox": 1.907,
    "pricePerM2": 19.95,
    "palletM2": 133.49,
    "size": "196 x 1216 mm",
    "thicknessMm": 8,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "70 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Laminate",
    "range": "Riverfields 8mm Laminate Collection",
    "code": "810103",
    "colour": "COBBLESTONE",
    "m2PerBox": 1.907,
    "pricePerM2": 19.95,
    "palletM2": 133.49,
    "size": "196 x 1216 mm",
    "thicknessMm": 8,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "70 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Laminate",
    "range": "Riverfields 8mm Laminate Collection",
    "code": "810104",
    "colour": "MAPLE SPRING",
    "m2PerBox": 1.907,
    "pricePerM2": 19.95,
    "palletM2": 133.49,
    "size": "196 x 1216 mm",
    "thicknessMm": 8,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "70 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Laminate",
    "range": "Riverfields 8mm Laminate Collection",
    "code": "810105",
    "colour": "AMARETTO",
    "m2PerBox": 1.907,
    "pricePerM2": 19.95,
    "palletM2": 133.49,
    "size": "196 x 1216 mm",
    "thicknessMm": 8,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "70 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Laminate",
    "range": "Riverfields 8mm Laminate Collection",
    "code": "810106",
    "colour": "BARN OAK",
    "m2PerBox": 1.907,
    "pricePerM2": 19.95,
    "palletM2": 133.49,
    "size": "196 x 1216 mm",
    "thicknessMm": 8,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "70 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Laminate",
    "range": "Riverfields 8mm Laminate Collection",
    "code": "810107",
    "colour": "SUMMER SUN",
    "m2PerBox": 1.907,
    "pricePerM2": 19.95,
    "palletM2": 133.49,
    "size": "196 x 1216 mm",
    "thicknessMm": 8,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "70 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Laminate",
    "range": "Riverfields 8mm Laminate Collection",
    "code": "810108",
    "colour": "REGAL SAND",
    "m2PerBox": 1.907,
    "pricePerM2": 19.95,
    "palletM2": 133.49,
    "size": "196 x 1216 mm",
    "thicknessMm": 8,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "70 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Laminate",
    "range": "Riverfields 8mm Laminate Collection",
    "code": "810109",
    "colour": "CARBON OAK",
    "m2PerBox": 1.907,
    "pricePerM2": 19.95,
    "palletM2": 133.49,
    "size": "196 x 1216 mm",
    "thicknessMm": 8,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "70 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Laminate",
    "range": "Riverfields 8mm Laminate Collection",
    "code": "810110",
    "colour": "GALWAY",
    "m2PerBox": 1.907,
    "pricePerM2": 19.95,
    "palletM2": 133.49,
    "size": "196 x 1216 mm",
    "thicknessMm": 8,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "70 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Laminate",
    "range": "Riverfields 8mm Laminate Collection",
    "code": "810111",
    "colour": "BLACKBUTT",
    "m2PerBox": 1.907,
    "pricePerM2": 19.95,
    "palletM2": 133.49,
    "size": "196 x 1216 mm",
    "thicknessMm": 8,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "70 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "Laminate",
    "range": "Riverfields 8mm Laminate Collection",
    "code": "810112",
    "colour": "SPOTTED GUM",
    "m2PerBox": 1.907,
    "pricePerM2": 19.95,
    "palletM2": 133.49,
    "size": "196 x 1216 mm",
    "thicknessMm": 8,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "70 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Australian Timber Luxury Vinyl Plank",
    "code": "830407",
    "colour": "HR LVPLL AUST NTHRN SPOTTD GUM",
    "m2PerBox": 1.382,
    "pricePerM2": 37.95,
    "palletM2": 103.65,
    "size": "189 x 1828 mm",
    "thicknessMm": 5,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "75 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Australian Timber Luxury Vinyl Plank",
    "code": "830408",
    "colour": "HR LVPLL AUST STHRN SPOTTD GUM",
    "m2PerBox": 1.382,
    "pricePerM2": 37.95,
    "palletM2": 103.65,
    "size": "189 x 1828 mm",
    "thicknessMm": 5,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "75 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Australian Timber Luxury Vinyl Plank",
    "code": "830409",
    "colour": "HR LVPLL AUST BLACKBUTT",
    "m2PerBox": 1.382,
    "pricePerM2": 37.95,
    "palletM2": 103.65,
    "size": "189 x 1828 mm",
    "thicknessMm": 5,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "75 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Australian Timber Luxury Vinyl Plank",
    "code": "830411",
    "colour": "HR LVPLL AUST JARRAH",
    "m2PerBox": 1.382,
    "pricePerM2": 37.95,
    "palletM2": 103.65,
    "size": "189 x 1828 mm",
    "thicknessMm": 5,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "75 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Australian Timber Luxury Vinyl Plank",
    "code": "830412",
    "colour": "HR LVPLL AUST BRUSHBOX",
    "m2PerBox": 1.382,
    "pricePerM2": 37.95,
    "palletM2": 103.65,
    "size": "189 x 1828 mm",
    "thicknessMm": 5,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "75 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Australian Timber Luxury Vinyl Plank",
    "code": "830413",
    "colour": "HR LVP AUST LIGHT TAS OAK",
    "m2PerBox": 1.382,
    "pricePerM2": 37.95,
    "palletM2": 103.65,
    "size": "189 x 1828 mm",
    "thicknessMm": 5,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "75 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Elmfield 4mm Vinyl Collection",
    "code": "830801",
    "colour": "SNOWFALL",
    "m2PerBox": 2.153,
    "pricePerM2": 29.95,
    "palletM2": 146.404,
    "size": "233 x 1540 mm",
    "thicknessMm": 4,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "68 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Elmfield 4mm Vinyl Collection",
    "code": "830802",
    "colour": "DOVE GREY",
    "m2PerBox": 2.153,
    "pricePerM2": 29.95,
    "palletM2": 146.404,
    "size": "233 x 1540 mm",
    "thicknessMm": 4,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "68 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Elmfield 4mm Vinyl Collection",
    "code": "830803",
    "colour": "SAND",
    "m2PerBox": 2.153,
    "pricePerM2": 29.95,
    "palletM2": 146.404,
    "size": "233 x 1540 mm",
    "thicknessMm": 4,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "68 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Elmfield 4mm Vinyl Collection",
    "code": "830804",
    "colour": "LATTE",
    "m2PerBox": 2.153,
    "pricePerM2": 29.95,
    "palletM2": 146.404,
    "size": "233 x 1540 mm",
    "thicknessMm": 4,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "68 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Elmfield 4mm Vinyl Collection",
    "code": "830805",
    "colour": "ASH",
    "m2PerBox": 2.153,
    "pricePerM2": 29.95,
    "palletM2": 146.404,
    "size": "233 x 1540 mm",
    "thicknessMm": 4,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "68 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Elmfield 4mm Vinyl Collection",
    "code": "830806",
    "colour": "MANUKA",
    "m2PerBox": 2.153,
    "pricePerM2": 29.95,
    "palletM2": 146.404,
    "size": "233 x 1540 mm",
    "thicknessMm": 4,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "68 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Elmfield 4mm Vinyl Collection",
    "code": "830807",
    "colour": "HAZEL",
    "m2PerBox": 2.153,
    "pricePerM2": 29.95,
    "palletM2": 146.404,
    "size": "233 x 1540 mm",
    "thicknessMm": 4,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "68 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Elmfield 4mm Vinyl Collection",
    "code": "830808",
    "colour": "CAMBRIDGE",
    "m2PerBox": 2.153,
    "pricePerM2": 29.95,
    "palletM2": 146.404,
    "size": "233 x 1540 mm",
    "thicknessMm": 4,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "68 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Elmfield 4mm Vinyl Collection",
    "code": "830809",
    "colour": "STORM",
    "m2PerBox": 2.153,
    "pricePerM2": 29.95,
    "palletM2": 146.404,
    "size": "233 x 1540 mm",
    "thicknessMm": 4,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "68 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Elmfield 4mm Vinyl Collection",
    "code": "830810",
    "colour": "COASTAL SPOTTED GUM",
    "m2PerBox": 2.153,
    "pricePerM2": 29.95,
    "palletM2": 146.404,
    "size": "233 x 1540 mm",
    "thicknessMm": 4,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "68 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Elmfield 4mm Vinyl Collection",
    "code": "830811",
    "colour": "SPOTTED GUM",
    "m2PerBox": 2.153,
    "pricePerM2": 29.95,
    "palletM2": 146.404,
    "size": "233 x 1540 mm",
    "thicknessMm": 4,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "68 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Elmfield 4mm Vinyl Collection",
    "code": "830812",
    "colour": "BLACKBUTT",
    "m2PerBox": 2.153,
    "pricePerM2": 29.95,
    "palletM2": 146.404,
    "size": "233 x 1540 mm",
    "thicknessMm": 4,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "68 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Natural Oak Luxury Vinyl Plank",
    "code": "830607",
    "colour": "HR LVPLL NAT OAK NEVADA PLAIN",
    "m2PerBox": 1.382,
    "pricePerM2": 37.95,
    "palletM2": 103.65,
    "size": "189 x 1828 mm",
    "thicknessMm": 5,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "75 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Natural Oak Luxury Vinyl Plank",
    "code": "830608",
    "colour": "HR LVPLL NAT OAK SAHARA DUNE",
    "m2PerBox": 1.382,
    "pricePerM2": 37.95,
    "palletM2": 103.65,
    "size": "189 x 1828 mm",
    "thicknessMm": 5,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "75 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Natural Oak Luxury Vinyl Plank",
    "code": "830609",
    "colour": "HR LVPLL NAT OAK PRVNCIAL GREY",
    "m2PerBox": 1.382,
    "pricePerM2": 37.95,
    "palletM2": 103.65,
    "size": "189 x 1828 mm",
    "thicknessMm": 5,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "75 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Natural Oak Luxury Vinyl Plank",
    "code": "830610",
    "colour": "HR LVPLL NAT OAK OSLO WHITE",
    "m2PerBox": 1.382,
    "pricePerM2": 37.95,
    "palletM2": 103.65,
    "size": "189 x 1828 mm",
    "thicknessMm": 5,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "75 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Natural Oak Luxury Vinyl Plank",
    "code": "830611",
    "colour": "HR LVPLL NAT OAK MOONSTONE",
    "m2PerBox": 1.382,
    "pricePerM2": 37.95,
    "palletM2": 103.65,
    "size": "189 x 1828 mm",
    "thicknessMm": 5,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "75 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Natural Oak Luxury Vinyl Plank",
    "code": "830612",
    "colour": "HR LVPLL NAT OAK TEMPEST",
    "m2PerBox": 1.382,
    "pricePerM2": 37.95,
    "palletM2": 103.65,
    "size": "189 x 1828 mm",
    "thicknessMm": 5,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "75 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Smoked Oak Luxury Vinyl Plank",
    "code": "830201",
    "colour": "HR LVPLL SMK OAK SILVERMIST",
    "m2PerBox": 1.951,
    "pricePerM2": 37.95,
    "palletM2": 132.668,
    "size": "229 x 1219 mm",
    "thicknessMm": 5,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "68 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Smoked Oak Luxury Vinyl Plank",
    "code": "830202",
    "colour": "HR LVPLL SMK OAK SIERRA FROST",
    "m2PerBox": 1.951,
    "pricePerM2": 37.95,
    "palletM2": 132.668,
    "size": "229 x 1219 mm",
    "thicknessMm": 5,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "68 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Smoked Oak Luxury Vinyl Plank",
    "code": "830203",
    "colour": "HR LVPLL SMK OAK WINDSPRAY",
    "m2PerBox": 1.951,
    "pricePerM2": 37.95,
    "palletM2": 132.668,
    "size": "229 x 1219 mm",
    "thicknessMm": 5,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "68 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Smoked Oak Luxury Vinyl Plank",
    "code": "830204",
    "colour": "HR LVPLL SMK OAK SUNSET HAZE",
    "m2PerBox": 1.951,
    "pricePerM2": 37.95,
    "palletM2": 132.668,
    "size": "229 x 1219 mm",
    "thicknessMm": 5,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "68 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Smoked Oak Luxury Vinyl Plank",
    "code": "830205",
    "colour": "HR LVPLL SMK OAK GREYSTONE",
    "m2PerBox": 1.951,
    "pricePerM2": 37.95,
    "palletM2": 132.668,
    "size": "229 x 1219 mm",
    "thicknessMm": 5,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "68 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Smoked Oak Luxury Vinyl Plank",
    "code": "830206",
    "colour": "HR LVPLL SMK OAK BURNT HUSK",
    "m2PerBox": 1.951,
    "pricePerM2": 37.95,
    "palletM2": 132.668,
    "size": "229 x 1219 mm",
    "thicknessMm": 5,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "68 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Smoked Oak Luxury Vinyl Plank",
    "code": "830207",
    "colour": "HR LVPLL SMK OAK DUSKMOOR",
    "m2PerBox": 1.951,
    "pricePerM2": 37.95,
    "palletM2": 132.668,
    "size": "229 x 1219 mm",
    "thicknessMm": 5,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "68 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Smoked Oak Luxury Vinyl Plank",
    "code": "830208",
    "colour": "HR LVPLL SMK OAK RIVERMALT",
    "m2PerBox": 1.951,
    "pricePerM2": 37.95,
    "palletM2": 132.668,
    "size": "229 x 1219 mm",
    "thicknessMm": 5,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "68 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Smoked Oak Luxury Vinyl Plank",
    "code": "830209",
    "colour": "HR LVPLL SMK OAK NORDIC BEECH",
    "m2PerBox": 1.951,
    "pricePerM2": 37.95,
    "palletM2": 132.668,
    "size": "229 x 1219 mm",
    "thicknessMm": 5,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "68 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Smoked Oak Luxury Vinyl Plank",
    "code": "830210",
    "colour": "HR LVPLL SMK OAK FROSTFALL",
    "m2PerBox": 1.951,
    "pricePerM2": 37.95,
    "palletM2": 132.668,
    "size": "229 x 1219 mm",
    "thicknessMm": 5,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "68 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Elmfield 2mm Vinyl Collection",
    "code": "840801",
    "colour": "SNOWFALL",
    "m2PerBox": 5.388,
    "pricePerM2": 15.95,
    "palletM2": 296.34,
    "size": "184.15 x 1219.2 mm",
    "thicknessMm": 2,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "55 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Elmfield 2mm Vinyl Collection",
    "code": "840802",
    "colour": "DOVE GREY",
    "m2PerBox": 5.388,
    "pricePerM2": 15.95,
    "palletM2": 296.34,
    "size": "184.15 x 1219.2 mm",
    "thicknessMm": 2,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "55 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Elmfield 2mm Vinyl Collection",
    "code": "840803",
    "colour": "SAND",
    "m2PerBox": 5.388,
    "pricePerM2": 15.95,
    "palletM2": 296.34,
    "size": "184.15 x 1219.2 mm",
    "thicknessMm": 2,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "55 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Elmfield 2mm Vinyl Collection",
    "code": "840804",
    "colour": "LATTE",
    "m2PerBox": 5.388,
    "pricePerM2": 15.95,
    "palletM2": 296.34,
    "size": "184.15 x 1219.2 mm",
    "thicknessMm": 2,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "55 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Elmfield 2mm Vinyl Collection",
    "code": "840805",
    "colour": "ASH",
    "m2PerBox": 5.388,
    "pricePerM2": 15.95,
    "palletM2": 296.34,
    "size": "184.15 x 1219.2 mm",
    "thicknessMm": 2,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "55 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Elmfield 2mm Vinyl Collection",
    "code": "840806",
    "colour": "MANUKA",
    "m2PerBox": 5.388,
    "pricePerM2": 15.95,
    "palletM2": 296.34,
    "size": "184.15 x 1219.2 mm",
    "thicknessMm": 2,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "55 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Elmfield 2mm Vinyl Collection",
    "code": "840807",
    "colour": "HAZEL",
    "m2PerBox": 5.388,
    "pricePerM2": 15.95,
    "palletM2": 296.34,
    "size": "184.15 x 1219.2 mm",
    "thicknessMm": 2,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "55 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Elmfield 2mm Vinyl Collection",
    "code": "840808",
    "colour": "CAMBRIDGE",
    "m2PerBox": 5.388,
    "pricePerM2": 15.95,
    "palletM2": 296.34,
    "size": "184.15 x 1219.2 mm",
    "thicknessMm": 2,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "55 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Elmfield 2mm Vinyl Collection",
    "code": "840809",
    "colour": "STORM",
    "m2PerBox": 5.388,
    "pricePerM2": 15.95,
    "palletM2": 296.34,
    "size": "184.15 x 1219.2 mm",
    "thicknessMm": 2,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "55 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Elmfield 2mm Vinyl Collection",
    "code": "840810",
    "colour": "COASTAL SPOTTED GUM",
    "m2PerBox": 5.388,
    "pricePerM2": 15.95,
    "palletM2": 296.34,
    "size": "184.15 x 1219.2 mm",
    "thicknessMm": 2,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "55 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Elmfield 2mm Vinyl Collection",
    "code": "840811",
    "colour": "SPOTTED GUM",
    "m2PerBox": 5.388,
    "pricePerM2": 15.95,
    "palletM2": 296.34,
    "size": "184.15 x 1219.2 mm",
    "thicknessMm": 2,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "55 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Elmfield 2mm Vinyl Collection",
    "code": "840812",
    "colour": "BLACKBUTT",
    "m2PerBox": 5.388,
    "pricePerM2": 15.95,
    "palletM2": 296.34,
    "size": "184.15 x 1219.2 mm",
    "thicknessMm": 2,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "55 cartons/pallet"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Summerhill Vinyl",
    "code": "840701",
    "colour": "PHANTOM",
    "m2PerBox": 4.181,
    "pricePerM2": 20.95,
    "palletM2": 229.955,
    "size": null,
    "thicknessMm": null,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "18 pieces/carton; 55 cartons/pallet; plank size not stated on supplied price list"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Summerhill Vinyl",
    "code": "840702",
    "colour": "WILLOW GREY",
    "m2PerBox": 4.181,
    "pricePerM2": 20.95,
    "palletM2": 229.955,
    "size": null,
    "thicknessMm": null,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "18 pieces/carton; 55 cartons/pallet; plank size not stated on supplied price list"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Summerhill Vinyl",
    "code": "840703",
    "colour": "SMOKEY QUARTZ",
    "m2PerBox": 4.181,
    "pricePerM2": 20.95,
    "palletM2": 229.955,
    "size": null,
    "thicknessMm": null,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "18 pieces/carton; 55 cartons/pallet; plank size not stated on supplied price list"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Summerhill Vinyl",
    "code": "840704",
    "colour": "MERINO MIST",
    "m2PerBox": 4.181,
    "pricePerM2": 20.95,
    "palletM2": 229.955,
    "size": null,
    "thicknessMm": null,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "18 pieces/carton; 55 cartons/pallet; plank size not stated on supplied price list"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Summerhill Vinyl",
    "code": "840705",
    "colour": "BURLYWOOD",
    "m2PerBox": 4.181,
    "pricePerM2": 20.95,
    "palletM2": 229.955,
    "size": null,
    "thicknessMm": null,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "18 pieces/carton; 55 cartons/pallet; plank size not stated on supplied price list"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Summerhill Vinyl",
    "code": "840706",
    "colour": "BROWN MAPLE",
    "m2PerBox": 4.181,
    "pricePerM2": 20.95,
    "palletM2": 229.955,
    "size": null,
    "thicknessMm": null,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "18 pieces/carton; 55 cartons/pallet; plank size not stated on supplied price list"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Summerhill Vinyl",
    "code": "840707",
    "colour": "VIENNA OAK",
    "m2PerBox": 4.181,
    "pricePerM2": 20.95,
    "palletM2": 229.955,
    "size": null,
    "thicknessMm": null,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "18 pieces/carton; 55 cartons/pallet; plank size not stated on supplied price list"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Summerhill Vinyl",
    "code": "840708",
    "colour": "BLACKBUTT",
    "m2PerBox": 4.181,
    "pricePerM2": 20.95,
    "palletM2": 229.955,
    "size": null,
    "thicknessMm": null,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "18 pieces/carton; 55 cartons/pallet; plank size not stated on supplied price list"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Summerhill Vinyl",
    "code": "840709",
    "colour": "SAFARI SUN",
    "m2PerBox": 4.181,
    "pricePerM2": 20.95,
    "palletM2": 229.955,
    "size": null,
    "thicknessMm": null,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "18 pieces/carton; 55 cartons/pallet; plank size not stated on supplied price list"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Summerhill Vinyl",
    "code": "840710",
    "colour": "BRAIDWOOD",
    "m2PerBox": 4.181,
    "pricePerM2": 20.95,
    "palletM2": 229.955,
    "size": null,
    "thicknessMm": null,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "18 pieces/carton; 55 cartons/pallet; plank size not stated on supplied price list"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Summerhill Vinyl",
    "code": "840711",
    "colour": "BURLAP HUE",
    "m2PerBox": 4.181,
    "pricePerM2": 20.95,
    "palletM2": 229.955,
    "size": null,
    "thicknessMm": null,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "18 pieces/carton; 55 cartons/pallet; plank size not stated on supplied price list"
  },
  {
    "supplier": "Dunlop Flooring",
    "productType": "LVT",
    "range": "Summerhill Vinyl",
    "code": "840712",
    "colour": "SPOTTED GUM",
    "m2PerBox": 4.181,
    "pricePerM2": 20.95,
    "palletM2": 229.955,
    "size": null,
    "thicknessMm": null,
    "sourceWorkbook": "Dunlop Flooring Price List - Hard Flooring 30 Sep 2026",
    "notes": "18 pieces/carton; 55 cartons/pallet; plank size not stated on supplied price list"
  }
];
