// GENERATED by scripts/extract-hurfords.py -- do not edit by hand.
//
// Hurford's CD Non Structural Pine Plywood, effective 1 Jun 2025.
//
// NON STRUCTURAL. This sheet CANNOT span joists -- it is an overlay laid over an
// existing floor. Anywhere a structural rating is specified this product does not
// qualify, however close its price looks to a structural sheet.
//
// PACK vs LOOSE is a real price axis: the pack rate applies at a full pack and up,
// the loose rate below it, and the loose rate is +8% NOMINAL on every thickness.
// A pack is a fixed HEIGHT of timber (~500-545mm), which is why the break quantity
// falls as the sheet gets thicker: 75 sheets at 7mm, 20 sheets at 25mm.
//
// The loose prices are Hurford's OWN printed figures, not 8% applied in code: they
// were rounded independently and three of the eight miss a flat 8% by a cent, in
// both directions. Seed `cutCostPrice` from `loosePrice`, never `cutUpliftPct`.

export type HurfordsPlywoodRow = {
  code: string;
  product: string;
  sizePrinted: string;
  lengthMm: number;
  widthMm: number;
  thicknessMm: number;
  sheetM2: number;
  /** Sheets in one full pack. At or above this the pack rate applies. */
  packQty: number;
  /** Per SHEET ex GST at a full pack or more. */
  packPrice: number;
  /**
   * Per SHEET ex GST below a full pack. THE AUTHORITATIVE loose rate --
   * printed by Hurford's, not derived, because 8% does not reproduce it to
   * the cent on 9mm, 15mm or 21mm.
   */
  loosePrice: number;
  /** Actual premium this line carries, ~8% but not exactly. */
  looseUpliftPct: number;
  /** What a flat 8% on the pack price would have given. */
  looseFrom8Pct: number;
  /** loosePrice - looseFrom8Pct. Non-zero on the three rounded lines. */
  centDrift: number;
  /** thicknessMm x packQty. Evidence the break is a physical pack, not a tier. */
  packHeightMm: number;
  /** Above this many sheets, a full pack is cheaper than buying loose. */
  breakEvenSheets: number;
  packM2: number;
  rule: string;
};

export const HURFORDS_SOURCE = "Hurfords_CD_Non_Structural_Pine_Plywood_Runable_isvB_D.xlsx";
export const HURFORDS_EFFECTIVE_FROM = "2025-06-01";
export const HURFORDS_LOOSE_UPLIFT_PCT = 8.0;

export const HURFORDS_PLYWOOD: HurfordsPlywoodRow[] = [
  {"code": "PNCD241207", "product": "CD Non Structural Pine Plywood", "sizePrinted": "2400 x 1200", "lengthMm": 2400.0, "widthMm": 1200.0, "thicknessMm": 7.0, "sheetM2": 2.88, "packQty": 75, "packPrice": 23.95, "loosePrice": 25.87, "looseUpliftPct": 8.0167, "looseFrom8Pct": 25.87, "centDrift": 0.0, "packHeightMm": 525.0, "breakEvenSheets": 69.43, "packM2": 216.0, "rule": "Pack price applies at 75+ sheets; loose price applies below 75 sheets."},
  {"code": "PNCD241209", "product": "CD Non Structural Pine Plywood", "sizePrinted": "2400 x 1200", "lengthMm": 2400.0, "widthMm": 1200.0, "thicknessMm": 9.0, "sheetM2": 2.88, "packQty": 60, "packPrice": 26.94, "loosePrice": 29.09, "looseUpliftPct": 7.9807, "looseFrom8Pct": 29.1, "centDrift": -0.01, "packHeightMm": 540.0, "breakEvenSheets": 55.57, "packM2": 172.8, "rule": "Pack price applies at 60+ sheets; loose price applies below 60 sheets."},
  {"code": "PNCD241212", "product": "CD Non Structural Pine Plywood", "sizePrinted": "2400 x 1200", "lengthMm": 2400.0, "widthMm": 1200.0, "thicknessMm": 12.0, "sheetM2": 2.88, "packQty": 45, "packPrice": 32.24, "loosePrice": 34.82, "looseUpliftPct": 8.0025, "looseFrom8Pct": 34.82, "centDrift": 0.0, "packHeightMm": 540.0, "breakEvenSheets": 41.67, "packM2": 129.6, "rule": "Pack price applies at 45+ sheets; loose price applies below 45 sheets."},
  {"code": "PNCD241215", "product": "CD Non Structural Pine Plywood", "sizePrinted": "2400 x 1200", "lengthMm": 2400.0, "widthMm": 1200.0, "thicknessMm": 15.0, "sheetM2": 2.88, "packQty": 35, "packPrice": 41.2, "loosePrice": 44.49, "looseUpliftPct": 7.9854, "looseFrom8Pct": 44.5, "centDrift": -0.01, "packHeightMm": 525.0, "breakEvenSheets": 32.41, "packM2": 100.8, "rule": "Pack price applies at 35+ sheets; loose price applies below 35 sheets."},
  {"code": "PNCD241217", "product": "CD Non Structural Pine Plywood", "sizePrinted": "2400 x 1200", "lengthMm": 2400.0, "widthMm": 1200.0, "thicknessMm": 17.0, "sheetM2": 2.88, "packQty": 32, "packPrice": 45.62, "loosePrice": 49.27, "looseUpliftPct": 8.0009, "looseFrom8Pct": 49.27, "centDrift": 0.0, "packHeightMm": 544.0, "breakEvenSheets": 29.63, "packM2": 92.16, "rule": "Pack price applies at 32+ sheets; loose price applies below 32 sheets."},
  {"code": "PNCD241219", "product": "CD Non Structural Pine Plywood", "sizePrinted": "2400 x 1200", "lengthMm": 2400.0, "widthMm": 1200.0, "thicknessMm": 19.0, "sheetM2": 2.88, "packQty": 28, "packPrice": 52.12, "loosePrice": 56.29, "looseUpliftPct": 8.0008, "looseFrom8Pct": 56.29, "centDrift": 0.0, "packHeightMm": 532.0, "breakEvenSheets": 25.93, "packM2": 80.64, "rule": "Pack price applies at 28+ sheets; loose price applies below 28 sheets."},
  {"code": "PNCD241221", "product": "CD Non Structural Pine Plywood", "sizePrinted": "2400 x 1200", "lengthMm": 2400.0, "widthMm": 1200.0, "thicknessMm": 21.0, "sheetM2": 2.88, "packQty": 25, "packPrice": 62.31, "loosePrice": 67.3, "looseUpliftPct": 8.0083, "looseFrom8Pct": 67.29, "centDrift": 0.01, "packHeightMm": 525.0, "breakEvenSheets": 23.15, "packM2": 72.0, "rule": "Pack price applies at 25+ sheets; loose price applies below 25 sheets."},
  {"code": "PNCD241225", "product": "CD Non Structural Pine Plywood", "sizePrinted": "2400 x 1200", "lengthMm": 2400.0, "widthMm": 1200.0, "thicknessMm": 25.0, "sheetM2": 2.88, "packQty": 20, "packPrice": 72.84, "loosePrice": 78.67, "looseUpliftPct": 8.0038, "looseFrom8Pct": 78.67, "centDrift": 0.0, "packHeightMm": 500.0, "breakEvenSheets": 18.52, "packM2": 57.6, "rule": "Pack price applies at 20+ sheets; loose price applies below 20 sheets."},
];
