// GENERATED by scripts/extract-mitre10.py -- do not edit by hand.
//
// Woodmans Mitre 10 Beenleigh. A trade store QUOTE, not a price list:
// every line carries an expiry and stops being Terra's price after it.
//
// Structural Plywood is F8 RATED -- the sheet that spans joists. Hurford's CD
// plywood is NON structural and cannot, so the two are not substitutes even
// where the $/sheet looks comparable.
//
// Mouldings are sold as whole 5.4m lengths, NOT by the metre. Their prices came
// from inc-GST line totals divided by 1.10, so a size can differ by a cent
// between profiles for no commercial reason -- flagged as roundingNoise. A
// spread of more than 2c in a size band is a real price difference (realPremium).

export type Mitre10PlyRow = {
  code: string;
  description: string;
  sizePrinted: string;
  lengthMm: number;
  widthMm: number;
  thicknessMm: number;
  sheetM2: number;
  pricePerSheet: number;
  quoteDate: string;
  quoteExpiry: string;
  /** Negative means the quote has already lapsed. */
  daysLeft: number;
  /** A separate SELEX product line, not the B9404xx run. */
  isSelex: boolean;
  perMmPerM2: number;
  /** Price per mm sits outside the band the rest of the range holds. */
  outOfBand: boolean;
};

export type Mitre10MouldingRow = {
  code: string;
  product: string;
  profile: string;
  sizePrinted: string;
  /** Face width in mm -- the visible height once fixed. */
  faceMm: number;
  thicknessMm: number;
  lengthM: number;
  lengthMm: number;
  /** Per whole 5.4m length ex GST. The real purchase unit. */
  priceEach: number;
  /** Derived only, for comparing against per-metre suppliers. Never order on it. */
  pricePerM: number;
  quoteNo: string;
  quoteDate: string;
  quoteExpiry: string;
  daysLeft: number;
  /** Within 2c of the cheapest in its size band: an inc-GST division artifact. */
  roundingNoise: boolean;
  /** More than 2c above its size band base: a genuine premium for that profile. */
  realPremium: boolean;
  sizeBandBase: number;
  sizeBandSpread: number;
};

export const MITRE10_SOURCE = "Mitre_10_Woodman_Beenleigh_Plywood_and_Mouldings_K_GTn4.xlsx";
export const MITRE10_BRANCH = "Woodmans Mitre 10 Beenleigh";
export const MITRE10_PLY: Mitre10PlyRow[] = [
  {"code": "B940462", "description": "PLY STRUCTURAL F8 BD", "sizePrinted": "2400 x 1200", "lengthMm": 2400.0, "widthMm": 1200.0, "thicknessMm": 9.0, "sheetM2": 2.88, "pricePerSheet": 39.35, "quoteDate": "2026-09-21", "quoteExpiry": "2026-10-21", "daysLeft": 25, "isSelex": false, "perMmPerM2": 1.5181, "outOfBand": false},
  {"code": "B940463", "description": "PLY STRUCTURAL F8 BD", "sizePrinted": "2400 x 1200", "lengthMm": 2400.0, "widthMm": 1200.0, "thicknessMm": 12.0, "sheetM2": 2.88, "pricePerSheet": 47.95, "quoteDate": "2026-09-21", "quoteExpiry": "2026-10-21", "daysLeft": 25, "isSelex": false, "perMmPerM2": 1.3874, "outOfBand": false},
  {"code": "B940464", "description": "PLY STRUCTURAL F8 BD", "sizePrinted": "2400 x 1200", "lengthMm": 2400.0, "widthMm": 1200.0, "thicknessMm": 15.0, "sheetM2": 2.88, "pricePerSheet": 59.73, "quoteDate": "2026-09-21", "quoteExpiry": "2026-10-21", "daysLeft": 25, "isSelex": false, "perMmPerM2": 1.3826, "outOfBand": false},
  {"code": "B940446", "description": "PLY STRUCTURAL F8 BD", "sizePrinted": "2400 x 1200", "lengthMm": 2400.0, "widthMm": 1200.0, "thicknessMm": 18.0, "sheetM2": 2.88, "pricePerSheet": 69.22, "quoteDate": "2026-09-21", "quoteExpiry": "2026-10-21", "daysLeft": 25, "isSelex": false, "perMmPerM2": 1.3353, "outOfBand": false},
  {"code": "ZZ4011022056", "description": "PLY STRUCTURAL SELEX BD F8", "sizePrinted": "2400 x 1200", "lengthMm": 2400.0, "widthMm": 1200.0, "thicknessMm": 25.0, "sheetM2": 2.88, "pricePerSheet": 144.77, "quoteDate": "2026-09-21", "quoteExpiry": "2026-10-21", "daysLeft": 25, "isSelex": true, "perMmPerM2": 2.0107, "outOfBand": true},
];

export const MITRE10_MOULDINGS: Mitre10MouldingRow[] = [
  {"code": "B940745", "product": "PINE MOULD FJ EZI TRIM PLUS", "profile": "Bullnose", "sizePrinted": "42 x 11mm", "faceMm": 42.0, "thicknessMm": 11.0, "lengthM": 5.4, "lengthMm": 5400.0, "priceEach": 5.28, "pricePerM": 0.98, "quoteNo": "6431308", "quoteDate": "2026-05-13", "quoteExpiry": "2026-06-12", "daysLeft": -106, "roundingNoise": false, "realPremium": false, "sizeBandBase": 5.28, "sizeBandSpread": 0.0},
  {"code": "B940746", "product": "PINE MOULD FJ EZI TRIM PLUS", "profile": "Bullnose", "sizePrinted": "66 x 11mm", "faceMm": 66.0, "thicknessMm": 11.0, "lengthM": 5.4, "lengthMm": 5400.0, "priceEach": 7.75, "pricePerM": 1.44, "quoteNo": "6431308", "quoteDate": "2026-05-13", "quoteExpiry": "2026-06-12", "daysLeft": -106, "roundingNoise": false, "realPremium": false, "sizeBandBase": 7.75, "sizeBandSpread": 0.0},
  {"code": "B940472", "product": "PINE MOULD FJ EZI TRIM PLUS", "profile": "Bullnose", "sizePrinted": "90 x 11mm", "faceMm": 90.0, "thicknessMm": 11.0, "lengthM": 5.4, "lengthMm": 5400.0, "priceEach": 11.54, "pricePerM": 2.14, "quoteNo": "6431308", "quoteDate": "2026-05-13", "quoteExpiry": "2026-06-12", "daysLeft": -106, "roundingNoise": true, "realPremium": false, "sizeBandBase": 11.53, "sizeBandSpread": 0.01},
  {"code": "B940442", "product": "PINE MOULD FJ EZI TRIM PLUS", "profile": "Bullnose", "sizePrinted": "42 x 18mm", "faceMm": 42.0, "thicknessMm": 18.0, "lengthM": 5.4, "lengthMm": 5400.0, "priceEach": 7.72, "pricePerM": 1.43, "quoteNo": "6431308", "quoteDate": "2026-05-13", "quoteExpiry": "2026-06-12", "daysLeft": -106, "roundingNoise": true, "realPremium": false, "sizeBandBase": 7.71, "sizeBandSpread": 0.01},
  {"code": "B940467", "product": "PINE MOULD FJ EZI TRIM PLUS", "profile": "Bullnose", "sizePrinted": "66 x 18mm", "faceMm": 66.0, "thicknessMm": 18.0, "lengthM": 5.4, "lengthMm": 5400.0, "priceEach": 11.78, "pricePerM": 2.18, "quoteNo": "6431308", "quoteDate": "2026-05-13", "quoteExpiry": "2026-06-12", "daysLeft": -106, "roundingNoise": false, "realPremium": true, "sizeBandBase": 11.74, "sizeBandSpread": 0.04},
  {"code": "B940801", "product": "PINE MOULD FJ EZI TRIM PLUS", "profile": "Bullnose", "sizePrinted": "90 x 18mm", "faceMm": 90.0, "thicknessMm": 18.0, "lengthM": 5.4, "lengthMm": 5400.0, "priceEach": 14.58, "pricePerM": 2.7, "quoteNo": "6431308", "quoteDate": "2026-05-13", "quoteExpiry": "2026-06-12", "daysLeft": -106, "roundingNoise": false, "realPremium": false, "sizeBandBase": 14.58, "sizeBandSpread": 0.0},
  {"code": "B300721", "product": "PINE MOULD FJ EZI TRIM PLUS", "profile": "Half Splayed AS4", "sizePrinted": "42 x 11mm", "faceMm": 42.0, "thicknessMm": 11.0, "lengthM": 5.4, "lengthMm": 5400.0, "priceEach": 5.28, "pricePerM": 0.98, "quoteNo": "6431308", "quoteDate": "2026-05-13", "quoteExpiry": "2026-06-12", "daysLeft": -106, "roundingNoise": false, "realPremium": false, "sizeBandBase": 5.28, "sizeBandSpread": 0.0},
  {"code": "B300720", "product": "PINE MOULD FJ EZI TRIM PLUS", "profile": "Half Splayed AS4", "sizePrinted": "66 x 11mm", "faceMm": 66.0, "thicknessMm": 11.0, "lengthM": 5.4, "lengthMm": 5400.0, "priceEach": 7.75, "pricePerM": 1.44, "quoteNo": "6431308", "quoteDate": "2026-05-13", "quoteExpiry": "2026-06-12", "daysLeft": -106, "roundingNoise": false, "realPremium": false, "sizeBandBase": 7.75, "sizeBandSpread": 0.0},
  {"code": "B940803", "product": "PINE MOULD FJ EZI TRIM PLUS", "profile": "Half Splayed AS4", "sizePrinted": "90 x 11mm", "faceMm": 90.0, "thicknessMm": 11.0, "lengthM": 5.4, "lengthMm": 5400.0, "priceEach": 11.54, "pricePerM": 2.14, "quoteNo": "6431308", "quoteDate": "2026-05-13", "quoteExpiry": "2026-06-12", "daysLeft": -106, "roundingNoise": true, "realPremium": false, "sizeBandBase": 11.53, "sizeBandSpread": 0.01},
  {"code": "B940186", "product": "PINE MOULD FJ EZI TRIM PLUS", "profile": "Half Splayed AS4", "sizePrinted": "42 x 18mm", "faceMm": 42.0, "thicknessMm": 18.0, "lengthM": 5.4, "lengthMm": 5400.0, "priceEach": 7.71, "pricePerM": 1.43, "quoteNo": "6431308", "quoteDate": "2026-05-13", "quoteExpiry": "2026-06-12", "daysLeft": -106, "roundingNoise": false, "realPremium": false, "sizeBandBase": 7.71, "sizeBandSpread": 0.0},
  {"code": "B940187", "product": "PINE MOULD FJ EZI TRIM PLUS", "profile": "Half Splayed AS4", "sizePrinted": "66 x 18mm", "faceMm": 66.0, "thicknessMm": 18.0, "lengthM": 5.4, "lengthMm": 5400.0, "priceEach": 11.83, "pricePerM": 2.19, "quoteNo": "6431308", "quoteDate": "2026-05-13", "quoteExpiry": "2026-06-12", "daysLeft": -106, "roundingNoise": false, "realPremium": true, "sizeBandBase": 11.74, "sizeBandSpread": 0.09},
  {"code": "B940817", "product": "PINE MOULD FJ EZI TRIM PLUS", "profile": "Half Splayed AS4", "sizePrinted": "90 x 18mm", "faceMm": 90.0, "thicknessMm": 18.0, "lengthM": 5.4, "lengthMm": 5400.0, "priceEach": 14.59, "pricePerM": 2.7, "quoteNo": "6431308", "quoteDate": "2026-05-13", "quoteExpiry": "2026-06-12", "daysLeft": -106, "roundingNoise": true, "realPremium": false, "sizeBandBase": 14.58, "sizeBandSpread": 0.01},
  {"code": "B941618", "product": "PINE MOULD FJ EZI TRIM HALF SPLAYED", "profile": "Half Splayed AS4", "sizePrinted": "138 x 18mm", "faceMm": 138.0, "thicknessMm": 18.0, "lengthM": 5.4, "lengthMm": 5400.0, "priceEach": 30.55, "pricePerM": 5.66, "quoteNo": "6431308", "quoteDate": "2026-05-13", "quoteExpiry": "2026-06-12", "daysLeft": -106, "roundingNoise": false, "realPremium": true, "sizeBandBase": 26.16, "sizeBandSpread": 4.39},
  {"code": "B940333", "product": "PINE MOULD FJ EZI TRIM PLUS", "profile": "Splayed", "sizePrinted": "42 x 11mm", "faceMm": 42.0, "thicknessMm": 11.0, "lengthM": 5.4, "lengthMm": 5400.0, "priceEach": 5.28, "pricePerM": 0.98, "quoteNo": "6431308", "quoteDate": "2026-05-13", "quoteExpiry": "2026-06-12", "daysLeft": -106, "roundingNoise": false, "realPremium": false, "sizeBandBase": 5.28, "sizeBandSpread": 0.0},
  {"code": "B940334", "product": "PINE MOULD FJ EZI TRIM PLUS", "profile": "Splayed", "sizePrinted": "66 x 11mm", "faceMm": 66.0, "thicknessMm": 11.0, "lengthM": 5.4, "lengthMm": 5400.0, "priceEach": 7.75, "pricePerM": 1.44, "quoteNo": "6431308", "quoteDate": "2026-05-13", "quoteExpiry": "2026-06-12", "daysLeft": -106, "roundingNoise": false, "realPremium": false, "sizeBandBase": 7.75, "sizeBandSpread": 0.0},
  {"code": "B940744", "product": "PINE MOULD FJ EZI TRIM PLUS", "profile": "Splayed", "sizePrinted": "90 x 11mm", "faceMm": 90.0, "thicknessMm": 11.0, "lengthM": 5.4, "lengthMm": 5400.0, "priceEach": 11.53, "pricePerM": 2.14, "quoteNo": "6431308", "quoteDate": "2026-05-13", "quoteExpiry": "2026-06-12", "daysLeft": -106, "roundingNoise": false, "realPremium": false, "sizeBandBase": 11.53, "sizeBandSpread": 0.0},
  {"code": "B940347", "product": "PINE MOULD FJ EZI TRIM PLUS", "profile": "Bevel", "sizePrinted": "42 x 18mm", "faceMm": 42.0, "thicknessMm": 18.0, "lengthM": 5.4, "lengthMm": 5400.0, "priceEach": 7.72, "pricePerM": 1.43, "quoteNo": "6431308", "quoteDate": "2026-05-13", "quoteExpiry": "2026-06-12", "daysLeft": -106, "roundingNoise": true, "realPremium": false, "sizeBandBase": 7.71, "sizeBandSpread": 0.01},
  {"code": "B940159", "product": "PINE MOULD FJ EZI TRIM PLUS", "profile": "Bevel", "sizePrinted": "66 x 18mm", "faceMm": 66.0, "thicknessMm": 18.0, "lengthM": 5.4, "lengthMm": 5400.0, "priceEach": 11.74, "pricePerM": 2.17, "quoteNo": "6431308", "quoteDate": "2026-05-13", "quoteExpiry": "2026-06-12", "daysLeft": -106, "roundingNoise": false, "realPremium": false, "sizeBandBase": 11.74, "sizeBandSpread": 0.0},
  {"code": "B940807", "product": "PINE MOULD FJ EZI TRIM PLUS", "profile": "Bevel", "sizePrinted": "90 x 18mm", "faceMm": 90.0, "thicknessMm": 18.0, "lengthM": 5.4, "lengthMm": 5400.0, "priceEach": 17.95, "pricePerM": 3.32, "quoteNo": "6431308", "quoteDate": "2026-05-13", "quoteExpiry": "2026-06-12", "daysLeft": -106, "roundingNoise": false, "realPremium": true, "sizeBandBase": 14.58, "sizeBandSpread": 3.37},
  {"code": "B941628", "product": "PINE MOULD FJ EZI TRIM PLUS", "profile": "Bevel", "sizePrinted": "138 x 18mm", "faceMm": 138.0, "thicknessMm": 18.0, "lengthM": 5.4, "lengthMm": 5400.0, "priceEach": 30.55, "pricePerM": 5.66, "quoteNo": "6431308", "quoteDate": "2026-05-13", "quoteExpiry": "2026-06-12", "daysLeft": -106, "roundingNoise": false, "realPremium": true, "sizeBandBase": 26.16, "sizeBandSpread": 4.39},
  {"code": "B940475", "product": "PINE MOULD FJ EZI TRIM PLUS", "profile": "Colonial 1", "sizePrinted": "42 x 11mm", "faceMm": 42.0, "thicknessMm": 11.0, "lengthM": 5.4, "lengthMm": 5400.0, "priceEach": 5.28, "pricePerM": 0.98, "quoteNo": "6431308", "quoteDate": "2026-05-13", "quoteExpiry": "2026-06-12", "daysLeft": -106, "roundingNoise": false, "realPremium": false, "sizeBandBase": 5.28, "sizeBandSpread": 0.0},
  {"code": "B940476", "product": "PINE MOULD FJ EZI TRIM PLUS", "profile": "Colonial 1", "sizePrinted": "66 x 11mm", "faceMm": 66.0, "thicknessMm": 11.0, "lengthM": 5.4, "lengthMm": 5400.0, "priceEach": 7.75, "pricePerM": 1.44, "quoteNo": "6431308", "quoteDate": "2026-05-13", "quoteExpiry": "2026-06-12", "daysLeft": -106, "roundingNoise": false, "realPremium": false, "sizeBandBase": 7.75, "sizeBandSpread": 0.0},
  {"code": "B940478", "product": "PINE MOULD FJ EZI TRIM PLUS", "profile": "Colonial 1", "sizePrinted": "90 x 11mm", "faceMm": 90.0, "thicknessMm": 11.0, "lengthM": 5.4, "lengthMm": 5400.0, "priceEach": 11.54, "pricePerM": 2.14, "quoteNo": "6431308", "quoteDate": "2026-05-13", "quoteExpiry": "2026-06-12", "daysLeft": -106, "roundingNoise": true, "realPremium": false, "sizeBandBase": 11.53, "sizeBandSpread": 0.01},
  {"code": "B940798", "product": "PINE MOULD FJ EZI TRIM PLUS", "profile": "NSW Colonial AS2", "sizePrinted": "42 x 18mm", "faceMm": 42.0, "thicknessMm": 18.0, "lengthM": 5.4, "lengthMm": 5400.0, "priceEach": 7.71, "pricePerM": 1.43, "quoteNo": "6431308", "quoteDate": "2026-05-13", "quoteExpiry": "2026-06-12", "daysLeft": -106, "roundingNoise": false, "realPremium": false, "sizeBandBase": 7.71, "sizeBandSpread": 0.0},
  {"code": "B940797", "product": "PINE MOULD FJ EZI TRIM PLUS", "profile": "NSW Colonial AS2", "sizePrinted": "66 x 18mm", "faceMm": 66.0, "thicknessMm": 18.0, "lengthM": 5.4, "lengthMm": 5400.0, "priceEach": 11.8, "pricePerM": 2.19, "quoteNo": "6431308", "quoteDate": "2026-05-13", "quoteExpiry": "2026-06-12", "daysLeft": -106, "roundingNoise": false, "realPremium": true, "sizeBandBase": 11.74, "sizeBandSpread": 0.06},
  {"code": "B940527", "product": "PINE MOULD FJ EZI TRIM PLUS", "profile": "NSW Colonial AS2", "sizePrinted": "90 x 18mm", "faceMm": 90.0, "thicknessMm": 18.0, "lengthM": 5.4, "lengthMm": 5400.0, "priceEach": 14.58, "pricePerM": 2.7, "quoteNo": "6431308", "quoteDate": "2026-05-13", "quoteExpiry": "2026-06-12", "daysLeft": -106, "roundingNoise": false, "realPremium": false, "sizeBandBase": 14.58, "sizeBandSpread": 0.0},
  {"code": "B940816", "product": "PINE MOULD FJ EZI TRIM PLUS", "profile": "NSW Colonial AS2", "sizePrinted": "138 x 18mm", "faceMm": 138.0, "thicknessMm": 18.0, "lengthM": 5.4, "lengthMm": 5400.0, "priceEach": 26.16, "pricePerM": 4.84, "quoteNo": "6431308", "quoteDate": "2026-05-13", "quoteExpiry": "2026-06-12", "daysLeft": -106, "roundingNoise": false, "realPremium": false, "sizeBandBase": 26.16, "sizeBandSpread": 0.0},
  {"code": "B940474", "product": "PINE MOULD FJ EZI TRIM PLUS", "profile": "Colonial 2", "sizePrinted": "42 x 11mm", "faceMm": 42.0, "thicknessMm": 11.0, "lengthM": 5.4, "lengthMm": 5400.0, "priceEach": 5.28, "pricePerM": 0.98, "quoteNo": "6431308", "quoteDate": "2026-05-13", "quoteExpiry": "2026-06-12", "daysLeft": -106, "roundingNoise": false, "realPremium": false, "sizeBandBase": 5.28, "sizeBandSpread": 0.0},
  {"code": "B940477", "product": "PINE MOULD FJ EZI TRIM PLUS", "profile": "Colonial 2", "sizePrinted": "66 x 11mm", "faceMm": 66.0, "thicknessMm": 11.0, "lengthM": 5.4, "lengthMm": 5400.0, "priceEach": 7.75, "pricePerM": 1.44, "quoteNo": "6431308", "quoteDate": "2026-05-13", "quoteExpiry": "2026-06-12", "daysLeft": -106, "roundingNoise": false, "realPremium": false, "sizeBandBase": 7.75, "sizeBandSpread": 0.0},
  {"code": "B940479", "product": "PINE MOULD FJ EZI TRIM PLUS", "profile": "Colonial 2", "sizePrinted": "90 x 11mm", "faceMm": 90.0, "thicknessMm": 11.0, "lengthM": 5.4, "lengthMm": 5400.0, "priceEach": 11.54, "pricePerM": 2.14, "quoteNo": "6431308", "quoteDate": "2026-05-13", "quoteExpiry": "2026-06-12", "daysLeft": -106, "roundingNoise": true, "realPremium": false, "sizeBandBase": 11.53, "sizeBandSpread": 0.01},
];
