/**
 * Polyflor price book — generated from the owner-supplied workbook by
 * scripts/extract-polyflor.py. DO NOT hand-edit: re-run the script instead.
 *
 * Source: Polyflor_Master_Runable_Final_DTNNP6.xlsx, sheet "Products & Colours"
 * (474 colour lines) + sheet "Accessories & Charges".
 *
 * Two things about this supplier that no earlier one had:
 *
 * 1. TWO PRICE COLUMNS. The workbook carries a "Trade" and a "Discount" column.
 *    Damien's call: where a Discount price exists it IS his everyday cost, so it
 *    is the STANDARD cost, not a special — it has no end date and never reverts.
 *    Where Discount is blank (3 Expona ranges) the Trade price is the standard
 *    cost. `costSource` records which column each rate was read from.
 *
 * 2. ROLL vs CUT. Every sheet-vinyl line has two rates: a roll rate and a
 *    higher cut rate for anything under a full 2m x 20m (40 m2) roll. Both are
 *    stored; which one applies depends on the ORDER QUANTITY, so it is resolved
 *    at quote time by `resolveRollCut` in api/lib/pricing.ts, never baked into
 *    the product row.
 */

/** Sheet vinyl comes off a 2m wide roll, 20 lineal metres, 40 m2. */
export const POLYFLOR_ROLL_WIDTH_M = 2;
export const POLYFLOR_ROLL_LM = 20;
export const POLYFLOR_ROLL_M2 = 40;

export const POLYFLOR_SOURCE = "Polyflor master price list (owner-supplied workbook)";

/** Which column of the supplier's list the standard cost was read from. */
export type PolyflorCostSource = "discount" | "trade" | "owner";

/** A colour line. Everything optional overrides its range's value. */
export type PolyflorColour = {
  colour: string;
  code: string;
  format?: string;
  size?: string;
  m2PerUnit?: number | null;
  qtyPerBox?: number | null;
  boxesPerPallet?: number | null;
  note?: string;
};

export type PolyflorRange = {
  /** LVT | Commercial Sheet | Safety Sheet, as Polyflor bands them. */
  band: string;
  range: string;
  /** Per m2 ex-GST. Full-roll rate for sheet; the only rate for boxed LVT. */
  rollCost: number;
  /** Per m2 ex-GST for a part roll. Null on boxed product, which has no cut. */
  cutCost: number | null;
  costSource: PolyflorCostSource;
  /** m2 on one full roll. Null on boxed product. */
  rollM2: number | null;
  format: string;
  thicknessMm: number | null;
  wearLayerMm: number | null;
  size: string;
  /** m2 per box (LVT) as the supplier prints it — rounded, cross-check only. */
  m2PerUnit: number | null;
  qtyPerBox: number | null;
  boxesPerPallet: number | null;
  note: string;
  colours: PolyflorColour[];
};

export const POLYFLOR_RANGES: PolyflorRange[] = [
  {
    band: "LVT",
    range: "MiPlank",
    rollCost: 33.98,
    cutCost: null,
    costSource: "discount",
    rollM2: null,
    format: "Plank",
    thicknessMm: 5,
    wearLayerMm: 0.55,
    size: "185mm x 1505mm",
    m2PerUnit: 2.23,
    qtyPerBox: 8,
    boxesPerPallet: 55,
    note: "Product price applies to this colour.",
    colours: [
      { colour: "Dark Oak", code: "2414", size: "177.8mm x 1219.2mm", m2PerUnit: 2.17, qtyPerBox: 10 },
      { colour: "Blackwood", code: "2417", size: "177.8mm x 1219.2mm", m2PerUnit: 2.17, qtyPerBox: 10 },
      { colour: "Grey Gum", code: "2420", boxesPerPallet: null },
      { colour: "Paperbark", code: "2411", size: "177.8mm x 1219.2mm", m2PerUnit: 2.17, qtyPerBox: 10 },
      { colour: "Wattle", code: "2412", size: "177.8mm x 1219.2mm", m2PerUnit: 2.17, qtyPerBox: 10 },
      { colour: "Sassafras", code: "2413", size: "177.8mm x 1219.2mm", m2PerUnit: 2.17, qtyPerBox: 10 },
      { colour: "Silver Birch", code: "2418", size: "177.8mm x 1219.2mm", m2PerUnit: 2.17, qtyPerBox: 10 },
      { colour: "Sun Bleached Ash", code: "2421", boxesPerPallet: null },
      { colour: "Cotton Wood", code: "2440", boxesPerPallet: 65 },
      { colour: "Weathered Fir", code: "2441", boxesPerPallet: 65 },
      { colour: "Blonde Myrtle", code: "2442", boxesPerPallet: 65 },
      { colour: "Eastern Oak", code: "2443", boxesPerPallet: 65 },
      { colour: "Kauri Pine", code: "2444", boxesPerPallet: 65 },
      { colour: "Refined Walnut", code: "2445", boxesPerPallet: 65 },
    ],
  },
  {
    band: "LVT",
    range: "MiPlank Acoustic",
    rollCost: 45.6,
    cutCost: null,
    costSource: "discount",
    rollM2: null,
    format: "Plank",
    thicknessMm: 5,
    wearLayerMm: 0.55,
    size: "177.8mm x 1219.2mm",
    m2PerUnit: 2.17,
    qtyPerBox: 10,
    boxesPerPallet: null,
    note: "Product price applies to this colour.",
    colours: [
      { colour: "Dark Oak", code: "9414" },
      { colour: "Blackwood", code: "9417" },
      { colour: "Grey Gum", code: "9420", size: "185mm x 1505mm", m2PerUnit: 2.23, qtyPerBox: 8, boxesPerPallet: 55 },
      { colour: "Paperbark", code: "9411" },
      { colour: "Sassafras", code: "9413" },
      { colour: "Silver Birch", code: "9418" },
      { colour: "Sun Bleached Ash", code: "9421", size: "185mm x 1505mm", m2PerUnit: 2.23, qtyPerBox: 8, boxesPerPallet: 55 },
    ],
  },
  {
    band: "LVT",
    range: "Expona Superplank PUR",
    rollCost: 25.04,
    cutCost: null,
    costSource: "discount",
    rollM2: null,
    format: "Plank",
    thicknessMm: null,
    wearLayerMm: null,
    size: "See shade format",
    m2PerUnit: null,
    qtyPerBox: null,
    boxesPerPallet: null,
    note: "Product price applies to this colour.",
    colours: [
      { colour: "Blond Oak", code: "2109" },
      { colour: "Black Japan", code: "2110" },
      { colour: "Bleached Oak", code: "2111" },
      { colour: "Vanilla Oak", code: "2112" },
      { colour: "Ghost Gum", code: "2113" },
      { colour: "Washed Elm", code: "2114" },
      { colour: "Heritage Bark", code: "2115" },
      { colour: "Nordic White Oak", code: "2116" },
      { colour: "Grey Elm", code: "2117" },
      { colour: "Golden Oak", code: "2118" },
      { colour: "Plied Birch", code: "2119" },
      { colour: "Amber Wood", code: "2120" },
      { colour: "Honey Limed Oak", code: "2121" },
      { colour: "Harvest", code: "2122" },
      { colour: "Granite", code: "2123" },
      { colour: "Gilded", code: "2124" },
      { colour: "Zephyr", code: "2125" },
    ],
  },
  {
    band: "LVT",
    range: "Camaro PUR",
    rollCost: 38.77,
    cutCost: null,
    costSource: "owner",
    rollM2: null,
    format: "Plank / Tile",
    thicknessMm: 2,
    wearLayerMm: 0.3,
    size: "Multiple sizes",
    m2PerUnit: null,
    qtyPerBox: null,
    boxesPerPallet: null,
    note: "Product price applies to this colour.",
    colours: [
      { colour: "Natural Oak", code: "2232" },
      { colour: "Bianco Oak", code: "2241" },
      { colour: "Boathouse Oak", code: "2242" },
      { colour: "Cashmere Oak", code: "2244" },
      { colour: "Quayside Oak", code: "2246" },
      { colour: "Sienna Oak", code: "2248" },
      { colour: "Wild Amber Oak", code: "2249" },
      { colour: "Rosedale Oak", code: "2254" },
      { colour: "Fenland Oak", code: "2258" },
      { colour: "Astoria Oak", code: "2259" },
      { colour: "Bayswater Oak", code: "2261" },
      { colour: "Cambridge Parquet", code: "2251" },
      { colour: "Georgian Parquet", code: "2252" },
      { colour: "Ocean Slate", code: "2319" },
      { colour: "Atlantic Slate", code: "2339" },
      { colour: "White Metalstone", code: "2332" },
      { colour: "Arctic Slate", code: "2341" },
      { colour: "Burnished Concrete", code: "2342" },
      { colour: "Soho Cement", code: "2347" },
      { colour: "Tribeca Cement", code: "2348" },
      { colour: "Goldstone Micro Terrazzo", code: "2349" },
      { colour: "Nut Tree", code: "2202" },
      { colour: "Smoke Brushed Elm", code: "2233" },
      { colour: "Westchester Oak Large Parquet", code: "LPQ2253" },
      { colour: "Waterside Oak Large Parquet", code: "LPQ2256" },
      { colour: "Naked Blond Oak Large Parquet", code: "LPQ2257" },
      { colour: "Westchester Oak", code: "PLK2253" },
      { colour: "Waterside Oak", code: "PLK2256" },
      { colour: "Naked Blond Oak", code: "PLK2257" },
      { colour: "Salvaged Timber", code: "2247" },
    ],
  },
  {
    band: "LVT",
    range: "Expona Simplay PUR",
    rollCost: 51.96,
    cutCost: null,
    costSource: "trade",
    rollM2: null,
    format: "Plank / Tile",
    thicknessMm: null,
    wearLayerMm: null,
    size: "See shade format",
    m2PerUnit: null,
    qtyPerBox: null,
    boxesPerPallet: null,
    note: "Product price applies to this colour.",
    colours: [
      { colour: "Light Cherry", code: "2501" },
      { colour: "American Oak", code: "2503" },
      { colour: "Dark Grey Fineline", code: "2510" },
      { colour: "Natural Ash", code: "2511" },
      { colour: "Grey Ash", code: "2512" },
      { colour: "White Rustic Pine", code: "2513" },
      { colour: "Natural Wild Oak", code: "2571" },
      { colour: "Honey Wild Oak", code: "2572" },
      { colour: "Black Ash", code: "2573" },
      { colour: "Medium Classic Oak", code: "2521" },
      { colour: "Light Grey Concrete", code: "2567" },
      { colour: "Dark Grey Concrete", code: "2569" },
      { colour: "Warm Cracked Concrete", code: "2584" },
      { colour: "Cold Cracked Concrete", code: "2585" },
      { colour: "Light Marble", code: "2583" },
      { colour: "Light Mono", code: "2579" },
      { colour: "Charcoal Mono", code: "2581" },
      { colour: "Natural Rustic Pine", code: "2514" },
    ],
  },
  {
    band: "LVT",
    range: "Expona Design PUR",
    rollCost: 55.78,
    cutCost: null,
    costSource: "trade",
    rollM2: null,
    format: "Plank / Tile",
    thicknessMm: null,
    wearLayerMm: null,
    size: "See shade format",
    m2PerUnit: null,
    qtyPerBox: null,
    boxesPerPallet: null,
    note: "Product price applies to this colour.",
    colours: [
      { colour: "Warm Grey Concrete", code: "7033" },
      { colour: "Light Grey Concrete", code: "7036" },
      { colour: "Cool Grey Concrete", code: "7037" },
      { colour: "Dark Grey Concrete", code: "7038" },
    ],
  },
  {
    band: "Commercial Sheet",
    range: "XL PU",
    rollCost: 21.24,
    cutCost: 26.42,
    costSource: "discount",
    rollM2: 40,
    format: "Sheet",
    thicknessMm: 2,
    wearLayerMm: null,
    size: "2m x 20m",
    m2PerUnit: 40,
    qtyPerBox: null,
    boxesPerPallet: null,
    note: "ROLL and CUT prices are different. Roll coverage shown is full 2m x 20m = 40m² roll.",
    colours: [
      { colour: "Pumice", code: "3700" },
      { colour: "Fossil", code: "3710" },
      { colour: "Flint", code: "3720" },
      { colour: "Blue Nickel", code: "3730" },
      { colour: "Crystal Blue", code: "3740" },
      { colour: "Tanzanite Blue", code: "3750" },
      { colour: "Blue Zircon", code: "3760" },
      { colour: "Azure", code: "3770" },
      { colour: "Connemara Green", code: "3800" },
      { colour: "Turquoise", code: "3810" },
      { colour: "Jade", code: "3830" },
      { colour: "Ironstone", code: "3850" },
      { colour: "Rose Quartz", code: "3870" },
      { colour: "Porcelain", code: "3880" },
      { colour: "Carnelian Beige", code: "3890" },
      { colour: "Sablee Beige", code: "3900" },
      { colour: "Dolomite", code: "3910" },
      { colour: "Citrine", code: "3930" },
    ],
  },
  {
    band: "Commercial Sheet",
    range: "Classic Mystique PUR",
    rollCost: 27.84,
    cutCost: 33.05,
    costSource: "discount",
    rollM2: 40,
    format: "Sheet",
    thicknessMm: 2,
    wearLayerMm: null,
    size: "2m x 20m",
    m2PerUnit: 40,
    qtyPerBox: null,
    boxesPerPallet: null,
    note: "ROLL and CUT prices are different. Roll coverage shown is full 2m x 20m = 40m² roll.",
    colours: [
      { colour: "Lemon Zest", code: "1140" },
      { colour: "Spring Meadow", code: "1150" },
      { colour: "Smokestone", code: "1160" },
      { colour: "Smoked Truffle", code: "1190" },
      { colour: "Pale Slate", code: "1200" },
      { colour: "Cloudburst", code: "1210" },
      { colour: "Delta Blue", code: "1220" },
      { colour: "Sunblaze", code: "1260" },
      { colour: "Asparagus", code: "1320" },
      { colour: "Mountain Lake", code: "1330" },
      { colour: "Satinwood", code: "1370" },
      { colour: "Nocturne", code: "1380" },
      { colour: "Quartz", code: "1400" },
      { colour: "Ladoga", code: "1410" },
      { colour: "Silver Mist", code: "1430" },
      { colour: "Shoreline", code: "1460" },
      { colour: "Rich Chocolate", code: "1520" },
      { colour: "Cloud Stone", code: "1530" },
      { colour: "Silent Dove", code: "1540" },
      { colour: "Steel Parade", code: "1550" },
      { colour: "Soft Almond", code: "1560" },
      { colour: "Nut Husk", code: "1570" },
      { colour: "Sorrel Bay", code: "1580" },
      { colour: "Atlantic Surf", code: "1590" },
    ],
  },
  {
    band: "Commercial Sheet",
    range: "Palettone PUR",
    rollCost: 39.59,
    cutCost: 44.71,
    costSource: "discount",
    rollM2: 40,
    format: "Sheet",
    thicknessMm: 2,
    wearLayerMm: null,
    size: "2m x 20m",
    m2PerUnit: 40,
    qtyPerBox: null,
    boxesPerPallet: null,
    note: "ROLL and CUT prices are different. Roll coverage shown is full 2m x 20m = 40m² roll.",
    colours: [
      { colour: "Urban Air", code: "8605" },
      { colour: "Frosted Glass", code: "8606" },
      { colour: "Dove Tail", code: "8607" },
      { colour: "Pencil Lead", code: "8608" },
      { colour: "Deep Space", code: "8609" },
      { colour: "Morning Air", code: "8610" },
      { colour: "Weekend Sky", code: "8611" },
      { colour: "Painter's Dream", code: "8612" },
      { colour: "Faded Denim", code: "8613" },
      { colour: "Petrol", code: "8614" },
      { colour: "Woodland Air", code: "8615" },
      { colour: "Orchard Walk", code: "8616" },
      { colour: "Sunshine Meadow", code: "8617" },
      { colour: "English Garden", code: "8618" },
      { colour: "Harvest Air", code: "8620" },
      { colour: "Natural Cotton", code: "8621" },
      { colour: "Foundation", code: "8622" },
      { colour: "China Clay", code: "8623" },
      { colour: "Freshly Ground", code: "8624" },
      { colour: "Blossom Air", code: "8625" },
      { colour: "Sugar Candy", code: "8627" },
      { colour: "Potters Wheel", code: "8628" },
      { colour: "Regency Room", code: "8629" },
      { colour: "New Dawn", code: "8630" },
      { colour: "Cayenne Heat", code: "8633" },
      { colour: "Heritage Hall", code: "8634" },
      { colour: "Linen Air", code: "8635" },
      { colour: "Cool Blende", code: "8636" },
      { colour: "Lunar Landscape", code: "8637" },
      { colour: "Quarrystone", code: "8639" },
      { colour: "Earthenware", code: "8641" },
      { colour: "Fired Ochre", code: "8642" },
      { colour: "Garden Sage", code: "8643" },
      { colour: "Dried Tarragon", code: "8644" },
      { colour: "Pecan Crunch", code: "8646" },
      { colour: "Superior Sky", code: "8648" },
      { colour: "Sapphire Star", code: "8649" },
      { colour: "Aqua Pura", code: "8651" },
      { colour: "Pennyroyal Mint", code: "8652" },
      { colour: "Crisp Apple", code: "8653" },
      { colour: "Hay Grain", code: "8655" },
      { colour: "Buttered Corn", code: "8656" },
    ],
  },
  {
    band: "Commercial Sheet",
    range: "Forest FX PUR",
    rollCost: 33.36,
    cutCost: 39.58,
    costSource: "discount",
    rollM2: 40,
    format: "Sheet",
    thicknessMm: 2,
    wearLayerMm: null,
    size: "2m x 20m",
    m2PerUnit: 40,
    qtyPerBox: null,
    boxesPerPallet: null,
    note: "ROLL and CUT prices are different. Roll coverage shown is full 2m x 20m = 40m² roll.",
    colours: [
      { colour: "Oiled Oak", code: "2990" },
      { colour: "Classic Oak", code: "3100" },
      { colour: "Grey Sawmill Oak", code: "3101" },
      { colour: "Rural Deckwood", code: "3102" },
      { colour: "Rock Salt Oak", code: "3103" },
      { colour: "Oslo Oak", code: "3104" },
      { colour: "Alloyed Timber", code: "3105" },
      { colour: "Parish Oak Parquet", code: "3106" },
      { colour: "Eton Oak Parquet", code: "3108" },
      { colour: "Newport Oak", code: "3109" },
      { colour: "Blanched Oak", code: "3113" },
      { colour: "French Walnut", code: "3120" },
      { colour: "Smoked Oak", code: "3150" },
      { colour: "Rustic Oak", code: "3330" },
      { colour: "European Oak", code: "3340" },
      { colour: "Mahogany", code: "3360" },
      { colour: "American Oak", code: "3380" },
      { colour: "Brazilian Walnut", code: "3990" },
    ],
  },
  {
    band: "Commercial Sheet",
    range: "Expona Flow PUR",
    rollCost: 37.08,
    cutCost: 42.45,
    costSource: "discount",
    rollM2: 40,
    format: "Sheet",
    thicknessMm: 2,
    wearLayerMm: null,
    size: "2m x 20m",
    m2PerUnit: 40,
    qtyPerBox: null,
    boxesPerPallet: null,
    note: "ROLL and CUT prices are different. Roll coverage shown is full 2m x 20m = 40m² roll.",
    colours: [
      { colour: "Blond Oak", code: "9820" },
      { colour: "Honey Oak", code: "9821" },
      { colour: "Toasted Oak", code: "9822" },
      { colour: "English Oak", code: "9823" },
      { colour: "Sun Bleached Oak", code: "9825" },
      { colour: "Silver Oak", code: "9826" },
      { colour: "Smoked Oak", code: "9827" },
      { colour: "Roasted Limed Ash", code: "9831" },
      { colour: "Warm Limed Ash", code: "9832" },
      { colour: "Classic Limed Ash", code: "9833" },
      { colour: "Oatmeal", code: "9840" },
      { colour: "Moleskin", code: "9841" },
      { colour: "Jet", code: "9842" },
      { colour: "Storm", code: "9845" },
      { colour: "Warm Concrete", code: "9855" },
      { colour: "Cool Concrete", code: "9856" },
      { colour: "Dark Grey Concrete", code: "9857" },
      { colour: "Light Grey Concrete", code: "9858" },
      { colour: "Dark Industrial Concrete", code: "9859" },
      { colour: "Light Industrial Concrete", code: "9860" },
      { colour: "Copper Ornamental", code: "9861" },
      { colour: "Autumn Rain", code: "9864" },
      { colour: "Honey Beige", code: "9869" },
      { colour: "Eden Oak", code: "9671" },
      { colour: "Ridge Oak", code: "9672" },
      { colour: "Serene Oak", code: "9673" },
      { colour: "Bracken Oak", code: "9674" },
      { colour: "Upland Oak", code: "9675" },
      { colour: "Borough Oak", code: "9676" },
      { colour: "Eden Oak Parquet", code: "9677" },
      { colour: "Serene Oak Parquet", code: "9678" },
      { colour: "Upland Oak Parquet", code: "9679" },
      { colour: "Classic Basket Weave", code: "9681" },
      { colour: "Antique Basket Weave", code: "9682" },
      { colour: "Grey Archer Oak", code: "9683" },
      { colour: "Tan Archer Oak", code: "9684" },
      { colour: "Dove Cement", code: "9685" },
      { colour: "Pewter Cement", code: "9686" },
      { colour: "Chalk Cement", code: "9687" },
      { colour: "Sepia Cement", code: "9688" },
      { colour: "Starlight", code: "9689" },
      { colour: "Pebble", code: "9691" },
      { colour: "Marlstone", code: "9692" },
      { colour: "Oyster", code: "9693" },
    ],
  },
  {
    band: "Commercial Sheet",
    range: "Bloc PUR",
    rollCost: 47.01,
    cutCost: 52.85,
    costSource: "discount",
    rollM2: 40,
    format: "Sheet",
    thicknessMm: 2,
    wearLayerMm: null,
    size: "2m x 20m",
    m2PerUnit: 40,
    qtyPerBox: null,
    boxesPerPallet: null,
    note: "ROLL and CUT prices are different. Roll coverage shown is full 2m x 20m = 40m² roll.",
    colours: [
      { colour: "Loft White", code: "9931" },
      { colour: "Rock Salt", code: "9932" },
      { colour: "Studio Grey", code: "9933" },
      { colour: "Urban Chic", code: "9934" },
      { colour: "Classic Black", code: "9935" },
      { colour: "Cool Breeze", code: "9936" },
      { colour: "Nordic Sky", code: "9937" },
      { colour: "Marine Blue", code: "9939" },
      { colour: "Lime Crush", code: "9940" },
      { colour: "Woodland Green", code: "9941" },
      { colour: "Soft Moss", code: "9942" },
      { colour: "Caramel Blush", code: "9944" },
      { colour: "Clay Deep", code: "9946" },
      { colour: "Lemon Punch", code: "9947" },
      { colour: "Red Beacon", code: "9948" },
      { colour: "Lilac Essence", code: "9949" },
    ],
  },
  {
    band: "Safety Sheet",
    range: "Polysafe Standard PUR",
    rollCost: 32.22,
    cutCost: 40.51,
    costSource: "discount",
    rollM2: 40,
    format: "Sheet",
    thicknessMm: 2,
    wearLayerMm: null,
    size: "2m x 20m",
    m2PerUnit: 40,
    qtyPerBox: null,
    boxesPerPallet: null,
    note: "ROLL and CUT prices are different. Roll coverage shown is full 2m x 20m = 40m² roll.",
    colours: [
      { colour: "Nordic Grey", code: "4090" },
      { colour: "Alpine Green", code: "4110" },
      { colour: "Arctic Blue", code: "4130" },
      { colour: "Autumn Beige", code: "4140" },
      { colour: "Silver Birch", code: "4020" },
      { colour: "Redwood", code: "4040" },
      { colour: "Cedar Blue", code: "4060" },
      { colour: "Black Walnut", code: "4150" },
      { colour: "Twilight", code: "4490" },
      { colour: "Elmwood", code: "4520" },
      { colour: "Ash Grey", code: "4540" },
      { colour: "Storm Blue", code: "4560" },
      { colour: "Cool Aqua", code: "4570" },
      { colour: "Lilac Blue", code: "4580" },
      { colour: "Wild Mushroom", code: "4600" },
      { colour: "Taupe", code: "4610" },
    ],
  },
  {
    band: "Safety Sheet",
    range: "Polysafe Verona PUR",
    rollCost: 36.06,
    cutCost: 44.14,
    costSource: "discount",
    rollM2: 40,
    format: "Sheet",
    thicknessMm: 2,
    wearLayerMm: null,
    size: "2m x 20m",
    m2PerUnit: 40,
    qtyPerBox: null,
    boxesPerPallet: null,
    note: "ROLL and CUT prices are different. Roll coverage shown is full 2m x 20m = 40m² roll.",
    colours: [
      { colour: "Cookie Cream", code: "5201" },
      { colour: "Rainstorm", code: "5202" },
      { colour: "Dolphin Grey", code: "5203" },
      { colour: "Café Noir", code: "5204" },
      { colour: "Skyline", code: "5205" },
      { colour: "Blue Lagoon", code: "5206" },
      { colour: "Nightfall", code: "5207" },
      { colour: "Horizon Blue", code: "5208" },
      { colour: "Freshmint", code: "5209" },
      { colour: "Oregano", code: "5210" },
      { colour: "Seagrass", code: "5211" },
      { colour: "Biscotti", code: "5212" },
      { colour: "Caramel Latte", code: "5213" },
      { colour: "Marshmallow", code: "5214" },
      { colour: "Soft Peach", code: "5216" },
      { colour: "Summer Coulis", code: "5217" },
      { colour: "Butterscotch", code: "5218" },
    ],
  },
  {
    band: "Safety Sheet",
    range: "Polysafe Verona PUR - Pure Colours",
    rollCost: 36.06,
    cutCost: 44.14,
    costSource: "discount",
    rollM2: 40,
    format: "Sheet",
    thicknessMm: 2,
    wearLayerMm: null,
    size: "2m x 20m",
    m2PerUnit: 40,
    qtyPerBox: null,
    boxesPerPallet: null,
    note: "ROLL and CUT prices are different. Roll coverage shown is full 2m x 20m = 40m² roll.",
    colours: [
      { colour: "Vanilla", code: "5221" },
      { colour: "Mocha", code: "5222" },
      { colour: "Cappuccino", code: "5224" },
      { colour: "Glacier", code: "5225" },
      { colour: "Monsoon", code: "5226" },
      { colour: "Sea Breeze", code: "5227" },
      { colour: "Pacific Blue", code: "5228" },
      { colour: "Azure", code: "5229" },
      { colour: "Rock Salt", code: "5231" },
      { colour: "Pebble Shore", code: "5233" },
      { colour: "Americano", code: "5234" },
      { colour: "Duck Egg", code: "5235" },
      { colour: "Rich Black", code: "5236" },
      { colour: "Midnight Blue", code: "5238" },
      { colour: "Neptune", code: "5239" },
      { colour: "Lemon Drizzle", code: "5241" },
    ],
  },
  {
    band: "Safety Sheet",
    range: "Polysafe Quattro PUR",
    rollCost: 44.06,
    cutCost: 53.38,
    costSource: "discount",
    rollM2: 40,
    format: "Sheet",
    thicknessMm: 2,
    wearLayerMm: null,
    size: "2m x 20m",
    m2PerUnit: 40,
    qtyPerBox: null,
    boxesPerPallet: null,
    note: "ROLL and CUT prices are different. Roll coverage shown is full 2m x 20m = 40m² roll.",
    colours: [
      { colour: "Barley Cove", code: "5761" },
      { colour: "Truffle Shore", code: "5762" },
      { colour: "Sea Spray", code: "5763" },
      { colour: "Coastal Flint", code: "5764" },
      { colour: "Granite Sky", code: "5765" },
      { colour: "Chalk Dune", code: "5766" },
      { colour: "Cool Pebble", code: "5767" },
      { colour: "Sea Mist", code: "5768" },
      { colour: "Calm Azure", code: "5770" },
      { colour: "Deep Lagoon", code: "5771" },
      { colour: "Lunar Shell", code: "5772" },
      { colour: "Slate Haze", code: "5773" },
    ],
  },
  {
    band: "Safety Sheet",
    range: "Polysafe Wood FX PUR",
    rollCost: 51.4,
    cutCost: 60.72,
    costSource: "discount",
    rollM2: 40,
    format: "Sheet",
    thicknessMm: 2,
    wearLayerMm: null,
    size: "2m x 20m",
    m2PerUnit: 40,
    qtyPerBox: null,
    boxesPerPallet: null,
    note: "ROLL and CUT prices are different. Roll coverage shown is full 2m x 20m = 40m² roll.",
    colours: [
      { colour: "Classic Oak", code: "3107" },
      { colour: "Rustic Oak", code: "3337" },
      { colour: "European Oak", code: "3347" },
      { colour: "Silver Oak", code: "3357" },
      { colour: "Nero Oak", code: "3371" },
      { colour: "Sun Bleached Oak", code: "3372" },
      { colour: "Aged Oak", code: "3373" },
      { colour: "Oiled Oak", code: "3374" },
      { colour: "Roasted Limed Ash", code: "3375" },
      { colour: "Tropical Pine", code: "3376" },
      { colour: "American Oak", code: "3387" },
    ],
  },
  {
    band: "Safety Sheet",
    range: "Polysafe Stone FX PUR",
    rollCost: 51.4,
    cutCost: 60.72,
    costSource: "discount",
    rollM2: 40,
    format: "Sheet",
    thicknessMm: 2,
    wearLayerMm: null,
    size: "2m x 20m",
    m2PerUnit: 40,
    qtyPerBox: null,
    boxesPerPallet: null,
    note: "ROLL and CUT prices are different. Roll coverage shown is full 2m x 20m = 40m² roll.",
    colours: [
      { colour: "Grey Flourite", code: "4042" },
      { colour: "Agate Grey", code: "4043" },
      { colour: "Gypsum", code: "4044" },
      { colour: "Jetstone", code: "4045" },
      { colour: "Copal", code: "4046" },
      { colour: "Galena", code: "4047" },
      { colour: "Andesite", code: "4049" },
      { colour: "Angelite", code: "4051" },
      { colour: "Blue Quartz", code: "4054" },
      { colour: "Muted Stone", code: "5081" },
      { colour: "Deep Fossil", code: "5082" },
      { colour: "Pebble Grey", code: "5083" },
      { colour: "Pearl River", code: "5084" },
      { colour: "Valley Rock", code: "5086" },
      { colour: "Light Concrete", code: "5087" },
      { colour: "Dark Concrete", code: "5089" },
      { colour: "Flagstone Grey", code: "5091" },
      { colour: "Clay Stone", code: "5092" },
      { colour: "Jurassic Stone", code: "6011" },
      { colour: "Dove Slate", code: "6012" },
      { colour: "Urban Concrete", code: "6013" },
      { colour: "Natural Slate", code: "6014" },
    ],
  },
  {
    band: "Safety Sheet",
    range: "Polysafe QuickLay PUR",
    rollCost: 60.05,
    cutCost: 71.2,
    costSource: "discount",
    rollM2: 40,
    format: "Sheet",
    thicknessMm: 2.2,
    wearLayerMm: null,
    size: "2m x 20m",
    m2PerUnit: 40,
    qtyPerBox: null,
    boxesPerPallet: null,
    note: "ROLL $60.05/m²; CUT $71.20/m². Full roll = 40m².",
    colours: [
      { colour: "Glacier", code: "6241" },
      { colour: "Pacific Blue", code: "6244" },
      { colour: "Midnight Blue", code: "6245" },
      { colour: "Monsoon", code: "6248" },
      { colour: "Mocha", code: "6249" },
      { colour: "Pebble Shore", code: "6250" },
      { colour: "Rock Salt", code: "6251" },
      { colour: "Rich Black", code: "6252" },
      { colour: "Vanilla", code: "6253" },
      { colour: "Sea Breeze", code: "6254" },
      { colour: "Azure", code: "6255" },
      { colour: "Americano", code: "6256" },
    ],
  },
  {
    band: "LVT",
    range: "Affinity 2⁵⁵ PUR",
    rollCost: 23.52,
    cutCost: null,
    costSource: "discount",
    rollM2: null,
    format: "Plank",
    thicknessMm: 2,
    wearLayerMm: 0.55,
    size: "184.2mm x 1219.2mm",
    m2PerUnit: 3.37,
    qtyPerBox: 15,
    boxesPerPallet: null,
    note: "Product price per m²; 15 planks/box; 3.37m²/box.",
    colours: [
      { colour: "Aspen Pine", code: "9870" },
      { colour: "Cracked White Oak", code: "9871" },
      { colour: "Planed White Oak", code: "9872" },
      { colour: "French Limed Oak", code: "9873" },
      { colour: "Champagne Oak", code: "9874" },
      { colour: "Dappled Oak", code: "9875" },
      { colour: "Harvest Oak", code: "9876" },
      { colour: "Saw Mill Oak", code: "9877" },
      { colour: "Cross Sawn Timber", code: "9878" },
      { colour: "Hazel Oak", code: "9879" },
      { colour: "Smoked Walnut", code: "9880" },
      { colour: "Flamed Chestnut", code: "9881" },
      { colour: "Huckleberry Oak", code: "9882" },
      { colour: "Reclaimed Pine", code: "9883" },
      { colour: "Seasoned Grey Oak", code: "9884" },
      { colour: "Jet Black Ash", code: "9885" },
    ],
  },
  {
    band: "LVT",
    range: "Expona Control PUR",
    rollCost: 53.12,
    cutCost: null,
    costSource: "trade",
    rollM2: null,
    format: "Plank",
    thicknessMm: 2.5,
    wearLayerMm: 0.7,
    size: "152.4mm x 914.4mm",
    m2PerUnit: 3.34,
    qtyPerBox: 24,
    boxesPerPallet: null,
    note: "Trade price per m²; 24 planks/box; 3.34m²/box.",
    colours: [
      { colour: "American Oak", code: "6500" },
      { colour: "Blond Country Plank", code: "6501" },
      { colour: "Nut Tree", code: "6502" },
      { colour: "Classic Oak", code: "6503" },
      { colour: "Weathered Country Plank", code: "6504" },
      { colour: "White Oak", code: "6505" },
      { colour: "Light Elm", code: "6506" },
      { colour: "Portland Stone", code: "7500", format: "Tile", size: "457.2mm x 457.2mm", qtyPerBox: 16, note: "Trade price per m²; 16 tiles/box; 3.34m²/box." },
      { colour: "Classic Limestone", code: "7501", format: "Tile", size: "457.2mm x 457.2mm", qtyPerBox: 16, note: "Trade price per m²; 16 tiles/box; 3.34m²/box." },
      { colour: "Classic Yorkstone", code: "7502", format: "Tile", size: "457.2mm x 457.2mm", qtyPerBox: 16, note: "Trade price per m²; 16 tiles/box; 3.34m²/box." },
      { colour: "Smoked Limestone", code: "7503", format: "Tile", size: "457.2mm x 457.2mm", qtyPerBox: 16, note: "Trade price per m²; 16 tiles/box; 3.34m²/box." },
      { colour: "Warm Grey Concrete", code: "7504", format: "Tile", size: "457.2mm x 457.2mm", qtyPerBox: 16, note: "Trade price per m²; 16 tiles/box; 3.34m²/box." },
      { colour: "Roman Limestone", code: "7506", format: "Tile", size: "304.8mm x 609.6mm", qtyPerBox: 18, note: "Trade price per m²; 18 tiles/box; 3.34m²/box." },
      { colour: "Cambrian Stone", code: "7507", format: "Tile", size: "304.8mm x 609.6mm", qtyPerBox: 18, note: "Trade price per m²; 18 tiles/box; 3.34m²/box." },
    ],
  },
  {
    band: "Safety Sheet",
    range: "Polysafe Apex",
    rollCost: 60.1,
    cutCost: 68.91,
    costSource: "discount",
    rollM2: 40,
    format: "Sheet",
    thicknessMm: 2.5,
    wearLayerMm: null,
    size: "2m x 20m",
    m2PerUnit: 40,
    qtyPerBox: null,
    boxesPerPallet: null,
    note: "ROLL $60.10/m²; CUT $68.91/m². Full roll = 40m².",
    colours: [
      { colour: "Green Quartz", code: "4201" },
      { colour: "Chromite", code: "4202" },
      { colour: "Biotite", code: "4203" },
      { colour: "Breccia", code: "4204" },
      { colour: "Siltstone", code: "4205" },
      { colour: "Red Ochre", code: "4206" },
    ],
  },
  {
    band: "LVT",
    range: "Expona Commercial PUR",
    rollCost: 28.81,
    cutCost: null,
    costSource: "discount",
    rollM2: null,
    format: "Plank",
    thicknessMm: 2.5,
    wearLayerMm: 0.55,
    size: "609.6 x 609.6mm",
    m2PerUnit: 3.34,
    qtyPerBox: 9,
    boxesPerPallet: null,
    note: "Product price per m²; 9 pieces/box; 3.34m²/box.",
    colours: [
      { colour: "Classic Oak", code: "1902", size: "101.6 x 914.4mm", qtyPerBox: 36, note: "Product price per m²; 36 pieces/box; 3.34m²/box." },
      { colour: "Silvered Driftwood", code: "4014", size: "203.2 x 1219.2mm", m2PerUnit: 3.46, qtyPerBox: 14, note: "Product price per m²; 14 pieces/box; 3.46m²/box." },
      { colour: "Antique oak", code: "4016", size: "203.2 x 1219.2mm", m2PerUnit: 3.46, qtyPerBox: 14, note: "Product price per m²; 14 pieces/box; 3.46m²/box." },
      { colour: "Blond Country Plank", code: "4017", size: "152.4 x 914.4mm", qtyPerBox: 24, note: "Product price per m²; 24 pieces/box; 3.34m²/box." },
      { colour: "Weathered Country Plank", code: "4019", size: "152.4 x 914.4mm", qtyPerBox: 24, note: "Product price per m²; 24 pieces/box; 3.34m²/box." },
      { colour: "Grey Ash", code: "4020", size: "152.4 x 1219.2mm", qtyPerBox: 18, note: "Product price per m²; 18 pieces/box; 3.34m²/box." },
      { colour: "Honey Ash", code: "4022", size: "152.4 x 1219.2mm", qtyPerBox: 18, note: "Product price per m²; 18 pieces/box; 3.34m²/box." },
      { colour: "Dark Brushed Oak", code: "4030", size: "203.2 x 1219.2mm", m2PerUnit: 3.46, qtyPerBox: 14, note: "Product price per m²; 14 pieces/box; 3.46m²/box." },
      { colour: "Natural Brushed Oak", code: "4031", size: "203.2 x 1219.2mm", m2PerUnit: 3.46, qtyPerBox: 14, note: "Product price per m²; 14 pieces/box; 3.46m²/box." },
      { colour: "Smoked Beam", code: "4033", size: "152.4 x 914.4mm", qtyPerBox: 24, note: "Product price per m²; 24 pieces/box; 3.34m²/box." },
      { colour: "Light Elm", code: "4034", size: "152.4 x 914.4mm", qtyPerBox: 24, note: "Product price per m²; 24 pieces/box; 3.34m²/box." },
      { colour: "Black Elm", code: "4035", size: "152.4 x 914.4mm", qtyPerBox: 24, note: "Product price per m²; 24 pieces/box; 3.34m²/box." },
      { colour: "White Oak", code: "4037", size: "152.4 x 914.4mm", qtyPerBox: 24, note: "Product price per m²; 24 pieces/box; 3.34m²/box." },
      { colour: "Saffron Oak", code: "4057", size: "184.2 x 1524mm", m2PerUnit: 3.37, qtyPerBox: 12, note: "Product price per m²; 12 pieces/box; 3.37m²/box." },
      { colour: "French Vanilla Oak", code: "4058", size: "184.2 x 1524mm", m2PerUnit: 3.37, qtyPerBox: 12, note: "Product price per m²; 12 pieces/box; 3.37m²/box." },
      { colour: "Beige Varnished Wood", code: "4069", size: "152.4 x 1219.2mm", qtyPerBox: 18, note: "Product price per m²; 18 pieces/box; 3.34m²/box." },
      { colour: "Light Varnished Wood", code: "4071", size: "152.4 x 1219.2mm", qtyPerBox: 18, note: "Product price per m²; 18 pieces/box; 3.34m²/box." },
      { colour: "Shoreline Oak", code: "4078", size: "184.2 x 1524mm", m2PerUnit: 3.37, qtyPerBox: 12, note: "Product price per m²; 12 pieces/box; 3.37m²/box." },
      { colour: "Roasted Oak", code: "4079", size: "184.2 x 1219.2mm", m2PerUnit: 3.37, qtyPerBox: 15, note: "Product price per m²; 15 pieces/box; 3.37m²/box." },
      { colour: "Blond Limed Oak", code: "4081", size: "203.2 x 1219.2mm", m2PerUnit: 3.46, qtyPerBox: 14, note: "Product price per m²; 14 pieces/box; 3.46m²/box." },
      { colour: "Grey Limed Oak", code: "4082", size: "203.2 x 1219.2mm", m2PerUnit: 3.46, qtyPerBox: 14, note: "Product price per m²; 14 pieces/box; 3.46m²/box." },
      { colour: "Dark Limed Oak", code: "4083", size: "203.2 x 1219.2mm", m2PerUnit: 3.46, qtyPerBox: 14, note: "Product price per m²; 14 pieces/box; 3.46m²/box." },
      { colour: "Light Classic Oak", code: "4085", size: "152.4 x 1219.2mm", qtyPerBox: 18, note: "Product price per m²; 18 pieces/box; 3.34m²/box." },
      { colour: "Honey Classic Oak", code: "4086", size: "152.4 x 1219.2mm", qtyPerBox: 18, note: "Product price per m²; 18 pieces/box; 3.34m²/box." },
      { colour: "Amber Classic Oak", code: "4087", size: "152.4 x 1219.2mm", qtyPerBox: 18, note: "Product price per m²; 18 pieces/box; 3.34m²/box." },
      { colour: "Dark Classic Oak", code: "4088", size: "152.4 x 1219.2mm", qtyPerBox: 18, note: "Product price per m²; 18 pieces/box; 3.34m²/box." },
      { colour: "Oiled Oak", code: "4098", size: "184.2 x 1219.2mm", m2PerUnit: 3.37, qtyPerBox: 15, note: "Product price per m²; 15 pieces/box; 3.37m²/box." },
      { colour: "Sherwood Oak", code: "4099", size: "184.2 x 1219.2mm", m2PerUnit: 3.37, qtyPerBox: 15, note: "Product price per m²; 15 pieces/box; 3.37m²/box." },
      { colour: "Everglade Oak", code: "4101", size: "184.2 x 1219.2mm", m2PerUnit: 3.37, qtyPerBox: 15, note: "Product price per m²; 15 pieces/box; 3.37m²/box." },
      { colour: "Blue Salvaged Wood", code: "4103", size: "203.2 x 1524mm", m2PerUnit: 3.41, qtyPerBox: 11, note: "Product price per m²; 11 pieces/box; 3.41m²/box." },
      { colour: "Grey Salvaged Wood", code: "4104", size: "203.2 x 1524mm", m2PerUnit: 3.41, qtyPerBox: 11, note: "Product price per m²; 11 pieces/box; 3.41m²/box." },
      { colour: "Bronzed Salvaged Wood", code: "4106", size: "203.2 x 1524mm", m2PerUnit: 3.41, qtyPerBox: 11, note: "Product price per m²; 11 pieces/box; 3.41m²/box." },
      { colour: "Natural Barnwood", code: "4107", size: "184.2 x 1524mm", m2PerUnit: 3.37, qtyPerBox: 12, note: "Product price per m²; 12 pieces/box; 3.37m²/box." },
      { colour: "Grey Barnwood", code: "4108", size: "184.2 x 1524mm", m2PerUnit: 3.37, qtyPerBox: 12, note: "Product price per m²; 12 pieces/box; 3.37m²/box." },
      { colour: "Endgrain Woodblock", code: "4109", size: "101.6 x 914.4mm", qtyPerBox: 36, note: "Product price per m²; 36 pieces/box; 3.34m²/box." },
      { colour: "Provence Oak", code: "4113", size: "203.2 x 1524mm", m2PerUnit: 3.41, qtyPerBox: 11, note: "Product price per m²; 11 pieces/box; 3.41m²/box." },
      { colour: "Wild Orchard Oak", code: "4114", size: "184.2 x 1524mm", m2PerUnit: 3.37, qtyPerBox: 12, note: "Product price per m²; 12 pieces/box; 3.37m²/box." },
      { colour: "Cottage Oak", code: "4116", size: "203.2 x 1524mm", m2PerUnit: 3.41, qtyPerBox: 11, note: "Product price per m²; 11 pieces/box; 3.41m²/box." },
      { colour: "Cottage Oak Prisma", code: "4117", format: "Tile" },
      { colour: "Vineyard Oak Prisma", code: "4118", format: "Tile" },
      { colour: "Provence Oak Prisma", code: "4119", format: "Tile" },
      { colour: "Saffron Oak Parquet", code: "4121", format: "Parquet", size: "152.4 x 609.6mm", qtyPerBox: 36, note: "Product price per m²; 36 pieces/box; 3.34m²/box." },
      { colour: "French Vanilla Oak Parquet", code: "4122", format: "Parquet", size: "152.4 x 609.6mm", qtyPerBox: 36, note: "Product price per m²; 36 pieces/box; 3.34m²/box." },
      { colour: "Sherwood Oak Parquet", code: "4123", format: "Parquet", size: "152.4 x 609.6mm", qtyPerBox: 36, note: "Product price per m²; 36 pieces/box; 3.34m²/box." },
      { colour: "Sherwood Oak Versailles", code: "4124", format: "Tile" },
      { colour: "Everglade Oak Parquet", code: "4126", format: "Parquet", size: "152.4 x 609.6mm", qtyPerBox: 36, note: "Product price per m²; 36 pieces/box; 3.34m²/box." },
      { colour: "Everglade Oak Versailles", code: "4127", format: "Tile" },
      { colour: "Oiled Oak Parquet", code: "4128", format: "Parquet", size: "152.4 x 609.6mm", qtyPerBox: 36, note: "Product price per m²; 36 pieces/box; 3.34m²/box." },
      { colour: "Oiled Oak Versailles", code: "4129", format: "Tile" },
      { colour: "Una White Oak", code: "4132", size: "184.2 x 1219.2mm", m2PerUnit: 3.37, qtyPerBox: 15, note: "Product price per m²; 15 pieces/box; 3.37m²/box." },
      { colour: "Wilder Oak", code: "4133", size: "184.2 x 1219.2mm", m2PerUnit: 3.37, qtyPerBox: 15, note: "Product price per m²; 15 pieces/box; 3.37m²/box." },
      { colour: "Everest Oak", code: "4134", size: "184.2 x 1524mm", m2PerUnit: 3.37, qtyPerBox: 12, note: "Product price per m²; 12 pieces/box; 3.37m²/box." },
      { colour: "Vineyard Oak", code: "4136", size: "203.2 x 1524mm", m2PerUnit: 3.41, qtyPerBox: 11, note: "Product price per m²; 11 pieces/box; 3.41m²/box." },
      { colour: "Pure Cement", code: "5034", format: "Tile", size: "609.6 x 1219.2mm", m2PerUnit: 5.95, qtyPerBox: 8, note: "Product price per m²; 8 pieces/box; 5.95m²/box." },
      { colour: "Tan Cement", code: "5035", format: "Tile", size: "609.6 x 1219.2mm", m2PerUnit: 5.95, qtyPerBox: 8, note: "Product price per m²; 8 pieces/box; 5.95m²/box." },
      { colour: "Dark Contour", code: "5046", format: "Tile", size: "304.8 x 914.4mm", qtyPerBox: 12, note: "Product price per m²; 12 pieces/box; 3.34m²/box." },
      { colour: "India Ink Slate", code: "5056", format: "Tile", size: "304.8 x 914.4mm", qtyPerBox: 12, note: "Product price per m²; 12 pieces/box; 3.34m²/box." },
      { colour: "Urban Slate", code: "5057", format: "Tile", size: "304.8 x 914.4mm", qtyPerBox: 12, note: "Product price per m²; 12 pieces/box; 3.34m²/box." },
      { colour: "Dovestail Slate", code: "5058", format: "Tile", size: "304.8 x 914.4mm", qtyPerBox: 12, note: "Product price per m²; 12 pieces/box; 3.34m²/box." },
      { colour: "Warm Grey Concrete", code: "5064", format: "Tile" },
      { colour: "Light Grey Concrete", code: "5067", format: "Tile" },
      { colour: "Cool Grey Concrete", code: "5068", format: "Tile" },
      { colour: "Dark Grey Concrete", code: "5069", format: "Tile" },
      { colour: "Black Textile", code: "5077", format: "Tile" },
      { colour: "Arctic Mosaic", code: "5094", format: "Tile" },
      { colour: "Granite Mosaic", code: "5095", format: "Tile" },
      { colour: "Rusted Metal", code: "5098", format: "Tile", size: "457.2 x 914.4mm", qtyPerBox: 8, note: "Product price per m²; 8 pieces/box; 3.34m²/box." },
      { colour: "Bister", code: "5099", format: "Tile", size: "457.2 x 914.4mm", qtyPerBox: 8, note: "Product price per m²; 8 pieces/box; 3.34m²/box." },
      { colour: "Industrial Steel", code: "5101", format: "Tile", size: "457.2 x 914.4mm", qtyPerBox: 8, note: "Product price per m²; 8 pieces/box; 3.34m²/box." },
      { colour: "Iron Ore", code: "5102", format: "Tile", size: "457.2 x 914.4mm", qtyPerBox: 8, note: "Product price per m²; 8 pieces/box; 3.34m²/box." },
      { colour: "Grey Abstract", code: "5117", size: "203.2 x 1524mm", m2PerUnit: 3.41, qtyPerBox: 11, note: "Product price per m²; 11 pieces/box; 3.41m²/box." },
      { colour: "Black Abstract", code: "5118", size: "203.2 x 1524mm", m2PerUnit: 3.41, qtyPerBox: 11, note: "Product price per m²; 11 pieces/box; 3.41m²/box." },
      { colour: "Light Triassic", code: "5119", size: "203.2 x 1524mm", m2PerUnit: 3.41, qtyPerBox: 11, note: "Product price per m²; 11 pieces/box; 3.41m²/box." },
      { colour: "Grey Triassic", code: "5121", size: "203.2 x 1524mm", m2PerUnit: 3.41, qtyPerBox: 11, note: "Product price per m²; 11 pieces/box; 3.41m²/box." },
      { colour: "Light Micro Terrazzo", code: "5123", format: "Tile", size: "609.6 x 1219.2mm", m2PerUnit: 5.95, qtyPerBox: 8, note: "Product price per m²; 8 pieces/box; 5.95m²/box." },
      { colour: "Grey Micro Terrazzo", code: "5124", format: "Tile", size: "609.6 x 1219.2mm", m2PerUnit: 5.95, qtyPerBox: 8, note: "Product price per m²; 8 pieces/box; 5.95m²/box." },
      { colour: "Warm Micro Terrazzo", code: "5125", format: "Tile", size: "609.6 x 1219.2mm", m2PerUnit: 5.95, qtyPerBox: 8, note: "Product price per m²; 8 pieces/box; 5.95m²/box." },
      { colour: "Silica Micro Terrazzo", code: "5126", format: "Tile", size: "609.6 x 1219.2mm", m2PerUnit: 5.95, qtyPerBox: 8, note: "Product price per m²; 8 pieces/box; 5.95m²/box." },
      { colour: "Dark Terrazzo", code: "5127", format: "Tile", size: "609.6 x 1219.2mm", m2PerUnit: 5.95, qtyPerBox: 8, note: "Product price per m²; 8 pieces/box; 5.95m²/box." },
      { colour: "Grey Terrazzo", code: "5128", format: "Tile", size: "609.6 x 1219.2mm", m2PerUnit: 5.95, qtyPerBox: 8, note: "Product price per m²; 8 pieces/box; 5.95m²/box." },
    ],
  },
];

/**
 * Sheet "Accessories & Charges". Weld rod is a SELLABLE product (Damien: priced
 * per lineal metre), so it lands in the price book. Freight and baling are
 * Terra-side order charges and live in supplier_fee_rules instead.
 */
export const POLYFLOR_ACCESSORIES: { name: string; unit: string; cost: number; note: string }[] = [
  { name: "Weld Rod", unit: "lm", cost: 2.2, note: "Trade price shown on supplied price sheet" },
];

/* Order charges from the same sheet, for reference — seeded as supplier fee rules:
 *   Delivery · Freight · Per delivery · $80 · Supplied price sheet
 *   Baling · Baling Fee · Per roll · $20 · Supplied price sheet
 */
