/**
 * Riverhill price book — generated from the owner-supplied workbook by
 * scripts/extract-riverhill.py. DO NOT hand-edit: re-run the script instead.
 *
 * Source: Riverhill_2025_Product_Price_List_94j-mT.xlsx, sheets "Products"
 * (71 colour lines across 8 ranges) and "Accessories & Charges" (21 priced
 * lines plus one unpriced charge line).
 *
 * Effective 25 September 2026 — current, per the owner. Prices are per m2,
 * ex-GST, and exact rather than rounded.
 *
 * NO BAILING CHARGE. The supplier's own sheet says so and the owner confirmed
 * it: $0, not unknown. It is recorded on the supplier, not as a product line.
 *
 * NO DELIVERY. Riverhill does not deliver to the Gold Coast warehouse — Terra
 * books its own carrier, so there is no freight figure anywhere in this file.
 */

/** Effective date the owner confirmed for this list. */
export const RIVERHILL_EFFECTIVE_FROM = "2026-09-25";
export const RIVERHILL_SOURCE =
  "Riverhill 2025 product price list (owner-supplied workbook), effective 25 September 2026, per m2 ex-GST";

/** Underlay and floor protection are bought as a 20 m2 roll and priced per m2. */
export const RIVERHILL_UNDERLAY_ROLL_M2 = 20;

export type RiverhillRow = {
  /** timber | hybrid */
  category: string;
  supplierCategory: string;
  range: string;
  /** Plank | Chevron | Herringbone — the laying pattern, which changes the waste factor. */
  productType: string;
  code: string;
  colour: string;
  /** As Riverhill prints it, e.g. "1820-2100x136x14/3". */
  size: string;
  /**
   * SHORTEST board in mm. On a fixed-length board this equals lengthMaxMm.
   * On the random-length range it is the only length safe to order off.
   */
  lengthMinMm: number;
  lengthMaxMm: number;
  widthMm: number;
  /** TOTAL board thickness. On hybrid this is core + wear layer added together. */
  thicknessMm: number;
  /** Oak veneer in mm off the "15/3" notation. Timber only. */
  veneerMm: number | null;
  /** Wear layer in mm off the "7.5+2" notation. Hybrid only. */
  wearLayerMm: number | null;
  /** The wear-layer cell verbatim. Blank on hybrid — it lives in the size string. */
  wearLayerText: string;
  /** Integer board count, derived and asserted whole. */
  boardsPerPack: number;
  /**
   * m2 in a pack of the SHORTEST boards. QUOTE OFF THIS ONE. Ordering off the
   * maximum under-orders a random-length job by up to 13%.
   */
  packM2Min: number;
  /** m2 in a pack of the LONGEST boards. Never used for ordering. */
  packM2Max: number;
  packM2PrintedMin: number;
  packM2PrintedMax: number;
  /** Per m2, ex-GST, standard cost. One price per range. */
  pricePerM2: number;
  /** true = pack size is a range, not a figure. Changes how a job is ordered. */
  randomLength: boolean;
  note: string;
};

export type RiverhillAccessory = {
  /** Profile (trim/nosing) | Accessory (underlay, floor protection) */
  group: string;
  /**
   * The floor range this fits, matched to a real product range. Empty string =
   * universal. A range absent from this list genuinely has no trim of that type.
   */
  fitsRange: string;
  /** The sheet's own shorthand for the range, kept for the audit trail. */
  fitsLabel: string;
  item: string;
  description: string;
  size: string;
  /** Ex-GST. Per piece on a profile, per m2 on underlay and floor protection. */
  price: number;
  /** each | m2 */
  unit: string;
  /** Purchase unit where it differs from the sell unit — a 20 m2 underlay roll. */
  rollM2: number | null;
  charge: string;
};

/** A charge line the sheet lists without an amount. Kept so it cannot be silently dropped. */
export type RiverhillUnpriced = { item: string; description: string; note: string };

export const RIVERHILL_ROWS: RiverhillRow[] = [
  {
    category: "timber",
    supplierCategory: "Engineered Timber",
    range: "iDesign Chevron",
    productType: "Chevron",
    code: "CVR15301",
    colour: "CASPER WHITE",
    size: "680x125x15/3",
    lengthMinMm: 680,
    lengthMaxMm: 680,
    widthMm: 125,
    thicknessMm: 15,
    veneerMm: 3,
    wearLayerMm: null,
    wearLayerText: "3mm",
    boardsPerPack: 16,
    packM2Min: 1.36,
    packM2Max: 1.36,
    packM2PrintedMin: 1.36,
    packM2PrintedMax: 1.36,
    pricePerM2: 75,
    randomLength: false,
    note: "",
  },
  {
    category: "timber",
    supplierCategory: "Engineered Timber",
    range: "iDesign Chevron",
    productType: "Chevron",
    code: "CVR15302",
    colour: "TINGE CLAY",
    size: "680x125x15/3",
    lengthMinMm: 680,
    lengthMaxMm: 680,
    widthMm: 125,
    thicknessMm: 15,
    veneerMm: 3,
    wearLayerMm: null,
    wearLayerText: "3mm",
    boardsPerPack: 16,
    packM2Min: 1.36,
    packM2Max: 1.36,
    packM2PrintedMin: 1.36,
    packM2PrintedMax: 1.36,
    pricePerM2: 75,
    randomLength: false,
    note: "",
  },
  {
    category: "timber",
    supplierCategory: "Engineered Timber",
    range: "iDesign Chevron",
    productType: "Chevron",
    code: "CVR15303",
    colour: "LIGHT NEUTRAL",
    size: "680x125x15/3",
    lengthMinMm: 680,
    lengthMaxMm: 680,
    widthMm: 125,
    thicknessMm: 15,
    veneerMm: 3,
    wearLayerMm: null,
    wearLayerText: "3mm",
    boardsPerPack: 16,
    packM2Min: 1.36,
    packM2Max: 1.36,
    packM2PrintedMin: 1.36,
    packM2PrintedMax: 1.36,
    pricePerM2: 75,
    randomLength: false,
    note: "",
  },
  {
    category: "timber",
    supplierCategory: "Engineered Timber",
    range: "iDesign Chevron",
    productType: "Chevron",
    code: "CVR15305",
    colour: "BEIGE ASH",
    size: "680x125x15/3",
    lengthMinMm: 680,
    lengthMaxMm: 680,
    widthMm: 125,
    thicknessMm: 15,
    veneerMm: 3,
    wearLayerMm: null,
    wearLayerText: "3mm",
    boardsPerPack: 16,
    packM2Min: 1.36,
    packM2Max: 1.36,
    packM2PrintedMin: 1.36,
    packM2PrintedMax: 1.36,
    pricePerM2: 75,
    randomLength: false,
    note: "",
  },
  {
    category: "timber",
    supplierCategory: "Engineered Timber",
    range: "iDesign Chevron",
    productType: "Chevron",
    code: "CVR15307",
    colour: "LIGHT MALT",
    size: "680x125x15/3",
    lengthMinMm: 680,
    lengthMaxMm: 680,
    widthMm: 125,
    thicknessMm: 15,
    veneerMm: 3,
    wearLayerMm: null,
    wearLayerText: "3mm",
    boardsPerPack: 16,
    packM2Min: 1.36,
    packM2Max: 1.36,
    packM2PrintedMin: 1.36,
    packM2PrintedMax: 1.36,
    pricePerM2: 75,
    randomLength: false,
    note: "",
  },
  {
    category: "timber",
    supplierCategory: "Engineered Timber",
    range: "iDesign Chevron",
    productType: "Chevron",
    code: "CVR15308",
    colour: "APOLO GREY",
    size: "680x125x15/3",
    lengthMinMm: 680,
    lengthMaxMm: 680,
    widthMm: 125,
    thicknessMm: 15,
    veneerMm: 3,
    wearLayerMm: null,
    wearLayerText: "3mm",
    boardsPerPack: 16,
    packM2Min: 1.36,
    packM2Max: 1.36,
    packM2PrintedMin: 1.36,
    packM2PrintedMax: 1.36,
    pricePerM2: 75,
    randomLength: false,
    note: "",
  },
  {
    category: "timber",
    supplierCategory: "Engineered Timber",
    range: "iDesign Chevron",
    productType: "Chevron",
    code: "CVR15309",
    colour: "CORAL SAND",
    size: "680x125x15/3",
    lengthMinMm: 680,
    lengthMaxMm: 680,
    widthMm: 125,
    thicknessMm: 15,
    veneerMm: 3,
    wearLayerMm: null,
    wearLayerText: "3mm",
    boardsPerPack: 16,
    packM2Min: 1.36,
    packM2Max: 1.36,
    packM2PrintedMin: 1.36,
    packM2PrintedMax: 1.36,
    pricePerM2: 75,
    randomLength: false,
    note: "",
  },
  {
    category: "timber",
    supplierCategory: "Engineered Timber",
    range: "iDesign Chevron",
    productType: "Chevron",
    code: "CVR15310",
    colour: "MIDNIGHT GREY",
    size: "680x125x15/3",
    lengthMinMm: 680,
    lengthMaxMm: 680,
    widthMm: 125,
    thicknessMm: 15,
    veneerMm: 3,
    wearLayerMm: null,
    wearLayerText: "3mm",
    boardsPerPack: 16,
    packM2Min: 1.36,
    packM2Max: 1.36,
    packM2PrintedMin: 1.36,
    packM2PrintedMax: 1.36,
    pricePerM2: 75,
    randomLength: false,
    note: "",
  },
  {
    category: "timber",
    supplierCategory: "Engineered Timber",
    range: "iDesign Herringbone",
    productType: "Herringbone",
    code: "HRB15301",
    colour: "CASPER WHITE",
    size: "600x125x15/3",
    lengthMinMm: 600,
    lengthMaxMm: 600,
    widthMm: 125,
    thicknessMm: 15,
    veneerMm: 3,
    wearLayerMm: null,
    wearLayerText: "3mm",
    boardsPerPack: 16,
    packM2Min: 1.2,
    packM2Max: 1.2,
    packM2PrintedMin: 1.2,
    packM2PrintedMax: 1.2,
    pricePerM2: 66,
    randomLength: false,
    note: "",
  },
  {
    category: "timber",
    supplierCategory: "Engineered Timber",
    range: "iDesign Herringbone",
    productType: "Herringbone",
    code: "HRB15302",
    colour: "TINGE CLAY",
    size: "600x125x15/3",
    lengthMinMm: 600,
    lengthMaxMm: 600,
    widthMm: 125,
    thicknessMm: 15,
    veneerMm: 3,
    wearLayerMm: null,
    wearLayerText: "3mm",
    boardsPerPack: 16,
    packM2Min: 1.2,
    packM2Max: 1.2,
    packM2PrintedMin: 1.2,
    packM2PrintedMax: 1.2,
    pricePerM2: 66,
    randomLength: false,
    note: "",
  },
  {
    category: "timber",
    supplierCategory: "Engineered Timber",
    range: "iDesign Herringbone",
    productType: "Herringbone",
    code: "HRB15303",
    colour: "LIGHT NEUTRAL",
    size: "600x125x15/3",
    lengthMinMm: 600,
    lengthMaxMm: 600,
    widthMm: 125,
    thicknessMm: 15,
    veneerMm: 3,
    wearLayerMm: null,
    wearLayerText: "3mm",
    boardsPerPack: 16,
    packM2Min: 1.2,
    packM2Max: 1.2,
    packM2PrintedMin: 1.2,
    packM2PrintedMax: 1.2,
    pricePerM2: 66,
    randomLength: false,
    note: "",
  },
  {
    category: "timber",
    supplierCategory: "Engineered Timber",
    range: "iDesign Herringbone",
    productType: "Herringbone",
    code: "HRB15304",
    colour: "NATURAL LIMED",
    size: "600x125x15/3",
    lengthMinMm: 600,
    lengthMaxMm: 600,
    widthMm: 125,
    thicknessMm: 15,
    veneerMm: 3,
    wearLayerMm: null,
    wearLayerText: "3mm",
    boardsPerPack: 16,
    packM2Min: 1.2,
    packM2Max: 1.2,
    packM2PrintedMin: 1.2,
    packM2PrintedMax: 1.2,
    pricePerM2: 66,
    randomLength: false,
    note: "",
  },
  {
    category: "timber",
    supplierCategory: "Engineered Timber",
    range: "iDesign Herringbone",
    productType: "Herringbone",
    code: "HRB15305",
    colour: "BEIGE ASH",
    size: "600x125x15/3",
    lengthMinMm: 600,
    lengthMaxMm: 600,
    widthMm: 125,
    thicknessMm: 15,
    veneerMm: 3,
    wearLayerMm: null,
    wearLayerText: "3mm",
    boardsPerPack: 16,
    packM2Min: 1.2,
    packM2Max: 1.2,
    packM2PrintedMin: 1.2,
    packM2PrintedMax: 1.2,
    pricePerM2: 66,
    randomLength: false,
    note: "",
  },
  {
    category: "timber",
    supplierCategory: "Engineered Timber",
    range: "iDesign Herringbone",
    productType: "Herringbone",
    code: "HRB15306",
    colour: "PALE OAK",
    size: "600x125x15/3",
    lengthMinMm: 600,
    lengthMaxMm: 600,
    widthMm: 125,
    thicknessMm: 15,
    veneerMm: 3,
    wearLayerMm: null,
    wearLayerText: "3mm",
    boardsPerPack: 16,
    packM2Min: 1.2,
    packM2Max: 1.2,
    packM2PrintedMin: 1.2,
    packM2PrintedMax: 1.2,
    pricePerM2: 66,
    randomLength: false,
    note: "",
  },
  {
    category: "timber",
    supplierCategory: "Engineered Timber",
    range: "iDesign Herringbone",
    productType: "Herringbone",
    code: "HRB15307",
    colour: "LIGHT MALT",
    size: "600x125x15/3",
    lengthMinMm: 600,
    lengthMaxMm: 600,
    widthMm: 125,
    thicknessMm: 15,
    veneerMm: 3,
    wearLayerMm: null,
    wearLayerText: "3mm",
    boardsPerPack: 16,
    packM2Min: 1.2,
    packM2Max: 1.2,
    packM2PrintedMin: 1.2,
    packM2PrintedMax: 1.2,
    pricePerM2: 66,
    randomLength: false,
    note: "",
  },
  {
    category: "timber",
    supplierCategory: "Engineered Timber",
    range: "iDesign Herringbone",
    productType: "Herringbone",
    code: "HRB15308",
    colour: "APOLO GREY",
    size: "600x125x15/3",
    lengthMinMm: 600,
    lengthMaxMm: 600,
    widthMm: 125,
    thicknessMm: 15,
    veneerMm: 3,
    wearLayerMm: null,
    wearLayerText: "3mm",
    boardsPerPack: 16,
    packM2Min: 1.2,
    packM2Max: 1.2,
    packM2PrintedMin: 1.2,
    packM2PrintedMax: 1.2,
    pricePerM2: 66,
    randomLength: false,
    note: "",
  },
  {
    category: "timber",
    supplierCategory: "Engineered Timber",
    range: "iDesign Herringbone",
    productType: "Herringbone",
    code: "HRB15309",
    colour: "CORAL SAND",
    size: "600x125x15/3",
    lengthMinMm: 600,
    lengthMaxMm: 600,
    widthMm: 125,
    thicknessMm: 15,
    veneerMm: 3,
    wearLayerMm: null,
    wearLayerText: "3mm",
    boardsPerPack: 16,
    packM2Min: 1.2,
    packM2Max: 1.2,
    packM2PrintedMin: 1.2,
    packM2PrintedMax: 1.2,
    pricePerM2: 66,
    randomLength: false,
    note: "",
  },
  {
    category: "timber",
    supplierCategory: "Engineered Timber",
    range: "iDesign Herringbone",
    productType: "Herringbone",
    code: "HRB15310",
    colour: "MIDNIGHT GREY",
    size: "600x125x15/3",
    lengthMinMm: 600,
    lengthMaxMm: 600,
    widthMm: 125,
    thicknessMm: 15,
    veneerMm: 3,
    wearLayerMm: null,
    wearLayerText: "3mm",
    boardsPerPack: 16,
    packM2Min: 1.2,
    packM2Max: 1.2,
    packM2PrintedMin: 1.2,
    packM2PrintedMax: 1.2,
    pricePerM2: 66,
    randomLength: false,
    note: "",
  },
  {
    category: "timber",
    supplierCategory: "Engineered Timber",
    range: "iDesign15 Oak",
    productType: "Plank",
    code: "PLK15301",
    colour: "CASPER WHITE",
    size: "1900x190x15/3",
    lengthMinMm: 1900,
    lengthMaxMm: 1900,
    widthMm: 190,
    thicknessMm: 15,
    veneerMm: 3,
    wearLayerMm: null,
    wearLayerText: "3mm",
    boardsPerPack: 8,
    packM2Min: 2.888,
    packM2Max: 2.888,
    packM2PrintedMin: 2.888,
    packM2PrintedMax: 2.888,
    pricePerM2: 59,
    randomLength: false,
    note: "",
  },
  {
    category: "timber",
    supplierCategory: "Engineered Timber",
    range: "iDesign15 Oak",
    productType: "Plank",
    code: "PLK15302",
    colour: "TINGE CLAY",
    size: "1900x190x15/3",
    lengthMinMm: 1900,
    lengthMaxMm: 1900,
    widthMm: 190,
    thicknessMm: 15,
    veneerMm: 3,
    wearLayerMm: null,
    wearLayerText: "3mm",
    boardsPerPack: 8,
    packM2Min: 2.888,
    packM2Max: 2.888,
    packM2PrintedMin: 2.888,
    packM2PrintedMax: 2.888,
    pricePerM2: 59,
    randomLength: false,
    note: "",
  },
  {
    category: "timber",
    supplierCategory: "Engineered Timber",
    range: "iDesign15 Oak",
    productType: "Plank",
    code: "PLK15303",
    colour: "LIGHT NEUTRAL",
    size: "1900x190x15/3",
    lengthMinMm: 1900,
    lengthMaxMm: 1900,
    widthMm: 190,
    thicknessMm: 15,
    veneerMm: 3,
    wearLayerMm: null,
    wearLayerText: "3mm",
    boardsPerPack: 8,
    packM2Min: 2.888,
    packM2Max: 2.888,
    packM2PrintedMin: 2.888,
    packM2PrintedMax: 2.888,
    pricePerM2: 59,
    randomLength: false,
    note: "",
  },
  {
    category: "timber",
    supplierCategory: "Engineered Timber",
    range: "iDesign15 Oak",
    productType: "Plank",
    code: "PLK15304",
    colour: "NATURAL LIMED",
    size: "1900x190x15/3",
    lengthMinMm: 1900,
    lengthMaxMm: 1900,
    widthMm: 190,
    thicknessMm: 15,
    veneerMm: 3,
    wearLayerMm: null,
    wearLayerText: "3mm",
    boardsPerPack: 8,
    packM2Min: 2.888,
    packM2Max: 2.888,
    packM2PrintedMin: 2.888,
    packM2PrintedMax: 2.888,
    pricePerM2: 59,
    randomLength: false,
    note: "",
  },
  {
    category: "timber",
    supplierCategory: "Engineered Timber",
    range: "iDesign15 Oak",
    productType: "Plank",
    code: "PLK15305",
    colour: "BEIGE ASH",
    size: "1900x190x15/3",
    lengthMinMm: 1900,
    lengthMaxMm: 1900,
    widthMm: 190,
    thicknessMm: 15,
    veneerMm: 3,
    wearLayerMm: null,
    wearLayerText: "3mm",
    boardsPerPack: 8,
    packM2Min: 2.888,
    packM2Max: 2.888,
    packM2PrintedMin: 2.888,
    packM2PrintedMax: 2.888,
    pricePerM2: 59,
    randomLength: false,
    note: "",
  },
  {
    category: "timber",
    supplierCategory: "Engineered Timber",
    range: "iDesign15 Oak",
    productType: "Plank",
    code: "PLK15306",
    colour: "PALE OAK",
    size: "1900x190x15/3",
    lengthMinMm: 1900,
    lengthMaxMm: 1900,
    widthMm: 190,
    thicknessMm: 15,
    veneerMm: 3,
    wearLayerMm: null,
    wearLayerText: "3mm",
    boardsPerPack: 8,
    packM2Min: 2.888,
    packM2Max: 2.888,
    packM2PrintedMin: 2.888,
    packM2PrintedMax: 2.888,
    pricePerM2: 59,
    randomLength: false,
    note: "",
  },
  {
    category: "timber",
    supplierCategory: "Engineered Timber",
    range: "iDesign15 Oak",
    productType: "Plank",
    code: "PLK15307",
    colour: "LIGHT MALT",
    size: "1900x190x15/3",
    lengthMinMm: 1900,
    lengthMaxMm: 1900,
    widthMm: 190,
    thicknessMm: 15,
    veneerMm: 3,
    wearLayerMm: null,
    wearLayerText: "3mm",
    boardsPerPack: 8,
    packM2Min: 2.888,
    packM2Max: 2.888,
    packM2PrintedMin: 2.888,
    packM2PrintedMax: 2.888,
    pricePerM2: 59,
    randomLength: false,
    note: "",
  },
  {
    category: "timber",
    supplierCategory: "Engineered Timber",
    range: "iDesign15 Oak",
    productType: "Plank",
    code: "PLK15308",
    colour: "APOLO GREY",
    size: "1900x190x15/3",
    lengthMinMm: 1900,
    lengthMaxMm: 1900,
    widthMm: 190,
    thicknessMm: 15,
    veneerMm: 3,
    wearLayerMm: null,
    wearLayerText: "3mm",
    boardsPerPack: 8,
    packM2Min: 2.888,
    packM2Max: 2.888,
    packM2PrintedMin: 2.888,
    packM2PrintedMax: 2.888,
    pricePerM2: 59,
    randomLength: false,
    note: "",
  },
  {
    category: "timber",
    supplierCategory: "Engineered Timber",
    range: "iDesign15 Oak",
    productType: "Plank",
    code: "PLK15309",
    colour: "CORAL SAND",
    size: "1900x190x15/3",
    lengthMinMm: 1900,
    lengthMaxMm: 1900,
    widthMm: 190,
    thicknessMm: 15,
    veneerMm: 3,
    wearLayerMm: null,
    wearLayerText: "3mm",
    boardsPerPack: 8,
    packM2Min: 2.888,
    packM2Max: 2.888,
    packM2PrintedMin: 2.888,
    packM2PrintedMax: 2.888,
    pricePerM2: 59,
    randomLength: false,
    note: "",
  },
  {
    category: "timber",
    supplierCategory: "Engineered Timber",
    range: "iDesign15 Oak",
    productType: "Plank",
    code: "PLK15310",
    colour: "MIDNIGHT GREY",
    size: "1900x190x15/3",
    lengthMinMm: 1900,
    lengthMaxMm: 1900,
    widthMm: 190,
    thicknessMm: 15,
    veneerMm: 3,
    wearLayerMm: null,
    wearLayerText: "3mm",
    boardsPerPack: 8,
    packM2Min: 2.888,
    packM2Max: 2.888,
    packM2PrintedMin: 2.888,
    packM2PrintedMax: 2.888,
    pricePerM2: 59,
    randomLength: false,
    note: "",
  },
  {
    category: "timber",
    supplierCategory: "Engineered Timber",
    range: "Classique Oak",
    productType: "Plank",
    code: "ENO14201",
    colour: "SEASHELL",
    size: "1900x190x14/2",
    lengthMinMm: 1900,
    lengthMaxMm: 1900,
    widthMm: 190,
    thicknessMm: 14,
    veneerMm: 2,
    wearLayerMm: null,
    wearLayerText: "2mm",
    boardsPerPack: 8,
    packM2Min: 2.888,
    packM2Max: 2.888,
    packM2PrintedMin: 2.888,
    packM2PrintedMax: 2.888,
    pricePerM2: 43,
    randomLength: false,
    note: "",
  },
  {
    category: "timber",
    supplierCategory: "Engineered Timber",
    range: "Classique Oak",
    productType: "Plank",
    code: "ENO14202",
    colour: "RAW WHITE",
    size: "1900x190x14/2",
    lengthMinMm: 1900,
    lengthMaxMm: 1900,
    widthMm: 190,
    thicknessMm: 14,
    veneerMm: 2,
    wearLayerMm: null,
    wearLayerText: "2mm",
    boardsPerPack: 8,
    packM2Min: 2.888,
    packM2Max: 2.888,
    packM2PrintedMin: 2.888,
    packM2PrintedMax: 2.888,
    pricePerM2: 43,
    randomLength: false,
    note: "",
  },
  {
    category: "timber",
    supplierCategory: "Engineered Timber",
    range: "Classique Oak",
    productType: "Plank",
    code: "ENO14203",
    colour: "NATURAL OAK",
    size: "1900x190x14/2",
    lengthMinMm: 1900,
    lengthMaxMm: 1900,
    widthMm: 190,
    thicknessMm: 14,
    veneerMm: 2,
    wearLayerMm: null,
    wearLayerText: "2mm",
    boardsPerPack: 8,
    packM2Min: 2.888,
    packM2Max: 2.888,
    packM2PrintedMin: 2.888,
    packM2PrintedMax: 2.888,
    pricePerM2: 43,
    randomLength: false,
    note: "",
  },
  {
    category: "timber",
    supplierCategory: "Engineered Timber",
    range: "Classique Oak",
    productType: "Plank",
    code: "ENO14204",
    colour: "NEUTRAL WHITE",
    size: "1900x190x14/2",
    lengthMinMm: 1900,
    lengthMaxMm: 1900,
    widthMm: 190,
    thicknessMm: 14,
    veneerMm: 2,
    wearLayerMm: null,
    wearLayerText: "2mm",
    boardsPerPack: 8,
    packM2Min: 2.888,
    packM2Max: 2.888,
    packM2PrintedMin: 2.888,
    packM2PrintedMax: 2.888,
    pricePerM2: 43,
    randomLength: false,
    note: "",
  },
  {
    category: "timber",
    supplierCategory: "Engineered Timber",
    range: "Classique Oak",
    productType: "Plank",
    code: "ENO14205",
    colour: "RAW NEUTRAL",
    size: "1900x190x14/2",
    lengthMinMm: 1900,
    lengthMaxMm: 1900,
    widthMm: 190,
    thicknessMm: 14,
    veneerMm: 2,
    wearLayerMm: null,
    wearLayerText: "2mm",
    boardsPerPack: 8,
    packM2Min: 2.888,
    packM2Max: 2.888,
    packM2PrintedMin: 2.888,
    packM2PrintedMax: 2.888,
    pricePerM2: 43,
    randomLength: false,
    note: "",
  },
  {
    category: "timber",
    supplierCategory: "Engineered Timber",
    range: "Classique Oak",
    productType: "Plank",
    code: "ENO14206",
    colour: "LIGHT TAN",
    size: "1900x190x14/2",
    lengthMinMm: 1900,
    lengthMaxMm: 1900,
    widthMm: 190,
    thicknessMm: 14,
    veneerMm: 2,
    wearLayerMm: null,
    wearLayerText: "2mm",
    boardsPerPack: 8,
    packM2Min: 2.888,
    packM2Max: 2.888,
    packM2PrintedMin: 2.888,
    packM2PrintedMax: 2.888,
    pricePerM2: 43,
    randomLength: false,
    note: "",
  },
  {
    category: "timber",
    supplierCategory: "Engineered Timber",
    range: "Classique Oak",
    productType: "Plank",
    code: "ENO14207",
    colour: "LATTE",
    size: "1900x190x14/2",
    lengthMinMm: 1900,
    lengthMaxMm: 1900,
    widthMm: 190,
    thicknessMm: 14,
    veneerMm: 2,
    wearLayerMm: null,
    wearLayerText: "2mm",
    boardsPerPack: 8,
    packM2Min: 2.888,
    packM2Max: 2.888,
    packM2PrintedMin: 2.888,
    packM2PrintedMax: 2.888,
    pricePerM2: 43,
    randomLength: false,
    note: "",
  },
  {
    category: "timber",
    supplierCategory: "Engineered Timber",
    range: "Classique Oak",
    productType: "Plank",
    code: "ENO14208",
    colour: "VINTAGE GREY",
    size: "1900x190x14/2",
    lengthMinMm: 1900,
    lengthMaxMm: 1900,
    widthMm: 190,
    thicknessMm: 14,
    veneerMm: 2,
    wearLayerMm: null,
    wearLayerText: "2mm",
    boardsPerPack: 8,
    packM2Min: 2.888,
    packM2Max: 2.888,
    packM2PrintedMin: 2.888,
    packM2PrintedMax: 2.888,
    pricePerM2: 43,
    randomLength: false,
    note: "",
  },
  {
    category: "timber",
    supplierCategory: "Engineered Timber",
    range: "Classique Oak",
    productType: "Plank",
    code: "ENO14209",
    colour: "SMOKE BROWN",
    size: "1900x190x14/2",
    lengthMinMm: 1900,
    lengthMaxMm: 1900,
    widthMm: 190,
    thicknessMm: 14,
    veneerMm: 2,
    wearLayerMm: null,
    wearLayerText: "2mm",
    boardsPerPack: 8,
    packM2Min: 2.888,
    packM2Max: 2.888,
    packM2PrintedMin: 2.888,
    packM2PrintedMax: 2.888,
    pricePerM2: 43,
    randomLength: false,
    note: "",
  },
  {
    category: "timber",
    supplierCategory: "Engineered Timber",
    range: "Classique Oak",
    productType: "Plank",
    code: "ENO14210",
    colour: "WALNUT",
    size: "1900x190x14/2",
    lengthMinMm: 1900,
    lengthMaxMm: 1900,
    widthMm: 190,
    thicknessMm: 14,
    veneerMm: 2,
    wearLayerMm: null,
    wearLayerText: "2mm",
    boardsPerPack: 8,
    packM2Min: 2.888,
    packM2Max: 2.888,
    packM2PrintedMin: 2.888,
    packM2PrintedMax: 2.888,
    pricePerM2: 43,
    randomLength: false,
    note: "",
  },
  {
    category: "hybrid",
    supplierCategory: "Hybrid",
    range: "Elegant SPC Hybrid 9.5mm",
    productType: "Plank",
    code: "HYB95001",
    colour: "NATURAL BLACKBUTT",
    size: "1820x228x7.5+2",
    lengthMinMm: 1820,
    lengthMaxMm: 1820,
    widthMm: 228,
    thicknessMm: 9.5,
    veneerMm: null,
    wearLayerMm: 2,
    wearLayerText: "",
    boardsPerPack: 4,
    packM2Min: 1.6598,
    packM2Max: 1.6598,
    packM2PrintedMin: 1.66,
    packM2PrintedMax: 1.66,
    pricePerM2: 32,
    randomLength: false,
    note: "",
  },
  {
    category: "hybrid",
    supplierCategory: "Hybrid",
    range: "Elegant SPC Hybrid 9.5mm",
    productType: "Plank",
    code: "HYB95002",
    colour: "NATURAL SPOTTED GUM",
    size: "1820x228x7.5+2",
    lengthMinMm: 1820,
    lengthMaxMm: 1820,
    widthMm: 228,
    thicknessMm: 9.5,
    veneerMm: null,
    wearLayerMm: 2,
    wearLayerText: "",
    boardsPerPack: 4,
    packM2Min: 1.6598,
    packM2Max: 1.6598,
    packM2PrintedMin: 1.66,
    packM2PrintedMax: 1.66,
    pricePerM2: 32,
    randomLength: false,
    note: "",
  },
  {
    category: "hybrid",
    supplierCategory: "Hybrid",
    range: "Elegant SPC Hybrid 9.5mm",
    productType: "Plank",
    code: "HYB95003",
    colour: "PACIFIC SPOTTED GUM",
    size: "1820x228x7.5+2",
    lengthMinMm: 1820,
    lengthMaxMm: 1820,
    widthMm: 228,
    thicknessMm: 9.5,
    veneerMm: null,
    wearLayerMm: 2,
    wearLayerText: "",
    boardsPerPack: 4,
    packM2Min: 1.6598,
    packM2Max: 1.6598,
    packM2PrintedMin: 1.66,
    packM2PrintedMax: 1.66,
    pricePerM2: 32,
    randomLength: false,
    note: "",
  },
  {
    category: "hybrid",
    supplierCategory: "Hybrid",
    range: "Elegant SPC Hybrid 9.5mm",
    productType: "Plank",
    code: "HYB95004",
    colour: "FRENCH OAK",
    size: "1820x228x7.5+2",
    lengthMinMm: 1820,
    lengthMaxMm: 1820,
    widthMm: 228,
    thicknessMm: 9.5,
    veneerMm: null,
    wearLayerMm: 2,
    wearLayerText: "",
    boardsPerPack: 4,
    packM2Min: 1.6598,
    packM2Max: 1.6598,
    packM2PrintedMin: 1.66,
    packM2PrintedMax: 1.66,
    pricePerM2: 32,
    randomLength: false,
    note: "",
  },
  {
    category: "hybrid",
    supplierCategory: "Hybrid",
    range: "Elegant SPC Hybrid 9.5mm",
    productType: "Plank",
    code: "HYB95005",
    colour: "SNOW GREY",
    size: "1820x228x7.5+2",
    lengthMinMm: 1820,
    lengthMaxMm: 1820,
    widthMm: 228,
    thicknessMm: 9.5,
    veneerMm: null,
    wearLayerMm: 2,
    wearLayerText: "",
    boardsPerPack: 4,
    packM2Min: 1.6598,
    packM2Max: 1.6598,
    packM2PrintedMin: 1.66,
    packM2PrintedMax: 1.66,
    pricePerM2: 32,
    randomLength: false,
    note: "",
  },
  {
    category: "hybrid",
    supplierCategory: "Hybrid",
    range: "Elegant SPC Hybrid 9.5mm",
    productType: "Plank",
    code: "HYB95006",
    colour: "LIME ASH",
    size: "1820x228x7.5+2",
    lengthMinMm: 1820,
    lengthMaxMm: 1820,
    widthMm: 228,
    thicknessMm: 9.5,
    veneerMm: null,
    wearLayerMm: 2,
    wearLayerText: "",
    boardsPerPack: 4,
    packM2Min: 1.6598,
    packM2Max: 1.6598,
    packM2PrintedMin: 1.66,
    packM2PrintedMax: 1.66,
    pricePerM2: 32,
    randomLength: false,
    note: "",
  },
  {
    category: "hybrid",
    supplierCategory: "Hybrid",
    range: "Elegant SPC Hybrid 9.5mm",
    productType: "Plank",
    code: "HYB95007",
    colour: "NEW ENGLAND BLACKBUTT",
    size: "1820x228x7.5+2",
    lengthMinMm: 1820,
    lengthMaxMm: 1820,
    widthMm: 228,
    thicknessMm: 9.5,
    veneerMm: null,
    wearLayerMm: 2,
    wearLayerText: "",
    boardsPerPack: 4,
    packM2Min: 1.6598,
    packM2Max: 1.6598,
    packM2PrintedMin: 1.66,
    packM2PrintedMax: 1.66,
    pricePerM2: 32,
    randomLength: false,
    note: "",
  },
  {
    category: "hybrid",
    supplierCategory: "Hybrid",
    range: "Elegant SPC Hybrid Herringbone 9.5mm",
    productType: "Herringbone",
    code: "HHB95001",
    colour: "NATURAL BLACKBUTT",
    size: "630x126x7.5+2",
    lengthMinMm: 630,
    lengthMaxMm: 630,
    widthMm: 126,
    thicknessMm: 9.5,
    veneerMm: null,
    wearLayerMm: 2,
    wearLayerText: "",
    boardsPerPack: 18,
    packM2Min: 1.4288,
    packM2Max: 1.4288,
    packM2PrintedMin: 1.43,
    packM2PrintedMax: 1.43,
    pricePerM2: 32,
    randomLength: false,
    note: "",
  },
  {
    category: "hybrid",
    supplierCategory: "Hybrid",
    range: "Elegant SPC Hybrid Herringbone 9.5mm",
    productType: "Herringbone",
    code: "HHB95002",
    colour: "NATURAL SPOTTED GUM",
    size: "630x126x7.5+2",
    lengthMinMm: 630,
    lengthMaxMm: 630,
    widthMm: 126,
    thicknessMm: 9.5,
    veneerMm: null,
    wearLayerMm: 2,
    wearLayerText: "",
    boardsPerPack: 18,
    packM2Min: 1.4288,
    packM2Max: 1.4288,
    packM2PrintedMin: 1.43,
    packM2PrintedMax: 1.43,
    pricePerM2: 32,
    randomLength: false,
    note: "",
  },
  {
    category: "hybrid",
    supplierCategory: "Hybrid",
    range: "Elegant SPC Hybrid Herringbone 9.5mm",
    productType: "Herringbone",
    code: "HHB95003",
    colour: "PACIFIC SPOTTED GUM",
    size: "630x126x7.5+2",
    lengthMinMm: 630,
    lengthMaxMm: 630,
    widthMm: 126,
    thicknessMm: 9.5,
    veneerMm: null,
    wearLayerMm: 2,
    wearLayerText: "",
    boardsPerPack: 18,
    packM2Min: 1.4288,
    packM2Max: 1.4288,
    packM2PrintedMin: 1.43,
    packM2PrintedMax: 1.43,
    pricePerM2: 32,
    randomLength: false,
    note: "",
  },
  {
    category: "hybrid",
    supplierCategory: "Hybrid",
    range: "Elegant SPC Hybrid Herringbone 9.5mm",
    productType: "Herringbone",
    code: "HHB95004",
    colour: "FRENCH OAK",
    size: "630x126x7.5+2",
    lengthMinMm: 630,
    lengthMaxMm: 630,
    widthMm: 126,
    thicknessMm: 9.5,
    veneerMm: null,
    wearLayerMm: 2,
    wearLayerText: "",
    boardsPerPack: 18,
    packM2Min: 1.4288,
    packM2Max: 1.4288,
    packM2PrintedMin: 1.43,
    packM2PrintedMax: 1.43,
    pricePerM2: 32,
    randomLength: false,
    note: "",
  },
  {
    category: "hybrid",
    supplierCategory: "Hybrid",
    range: "Elegant SPC Hybrid Herringbone 9.5mm",
    productType: "Herringbone",
    code: "HHB95005",
    colour: "SNOW GREY",
    size: "630x126x7.5+2",
    lengthMinMm: 630,
    lengthMaxMm: 630,
    widthMm: 126,
    thicknessMm: 9.5,
    veneerMm: null,
    wearLayerMm: 2,
    wearLayerText: "",
    boardsPerPack: 18,
    packM2Min: 1.4288,
    packM2Max: 1.4288,
    packM2PrintedMin: 1.43,
    packM2PrintedMax: 1.43,
    pricePerM2: 32,
    randomLength: false,
    note: "",
  },
  {
    category: "hybrid",
    supplierCategory: "Hybrid",
    range: "Elegant SPC Hybrid Herringbone 9.5mm",
    productType: "Herringbone",
    code: "HHB95006",
    colour: "LIME ASH",
    size: "630x126x7.5+2",
    lengthMinMm: 630,
    lengthMaxMm: 630,
    widthMm: 126,
    thicknessMm: 9.5,
    veneerMm: null,
    wearLayerMm: 2,
    wearLayerText: "",
    boardsPerPack: 18,
    packM2Min: 1.4288,
    packM2Max: 1.4288,
    packM2PrintedMin: 1.43,
    packM2PrintedMax: 1.43,
    pricePerM2: 32,
    randomLength: false,
    note: "",
  },
  {
    category: "hybrid",
    supplierCategory: "Hybrid",
    range: "Elegant SPC Hybrid 6.5mm",
    productType: "Plank",
    code: "HYB65001",
    colour: "COASTAL BLACKBUTT",
    size: "1540x182x5+1.5",
    lengthMinMm: 1540,
    lengthMaxMm: 1540,
    widthMm: 182,
    thicknessMm: 6.5,
    veneerMm: null,
    wearLayerMm: 1.5,
    wearLayerText: "",
    boardsPerPack: 8,
    packM2Min: 2.2422,
    packM2Max: 2.2422,
    packM2PrintedMin: 2.243,
    packM2PrintedMax: 2.243,
    pricePerM2: 24,
    randomLength: false,
    note: "",
  },
  {
    category: "hybrid",
    supplierCategory: "Hybrid",
    range: "Elegant SPC Hybrid 6.5mm",
    productType: "Plank",
    code: "HYB65002",
    colour: "QLD SPOTTED GUM",
    size: "1540x182x5+1.5",
    lengthMinMm: 1540,
    lengthMaxMm: 1540,
    widthMm: 182,
    thicknessMm: 6.5,
    veneerMm: null,
    wearLayerMm: 1.5,
    wearLayerText: "",
    boardsPerPack: 8,
    packM2Min: 2.2422,
    packM2Max: 2.2422,
    packM2PrintedMin: 2.243,
    packM2PrintedMax: 2.243,
    pricePerM2: 24,
    randomLength: false,
    note: "",
  },
  {
    category: "hybrid",
    supplierCategory: "Hybrid",
    range: "Elegant SPC Hybrid 6.5mm",
    productType: "Plank",
    code: "HYB65003",
    colour: "CHARCOAL",
    size: "1540x182x5+1.5",
    lengthMinMm: 1540,
    lengthMaxMm: 1540,
    widthMm: 182,
    thicknessMm: 6.5,
    veneerMm: null,
    wearLayerMm: 1.5,
    wearLayerText: "",
    boardsPerPack: 8,
    packM2Min: 2.2422,
    packM2Max: 2.2422,
    packM2PrintedMin: 2.243,
    packM2PrintedMax: 2.243,
    pricePerM2: 24,
    randomLength: false,
    note: "",
  },
  {
    category: "hybrid",
    supplierCategory: "Hybrid",
    range: "Elegant SPC Hybrid 6.5mm",
    productType: "Plank",
    code: "HYB65004",
    colour: "ASH CLIFF",
    size: "1540x182x5+1.5",
    lengthMinMm: 1540,
    lengthMaxMm: 1540,
    widthMm: 182,
    thicknessMm: 6.5,
    veneerMm: null,
    wearLayerMm: 1.5,
    wearLayerText: "",
    boardsPerPack: 8,
    packM2Min: 2.2422,
    packM2Max: 2.2422,
    packM2PrintedMin: 2.243,
    packM2PrintedMax: 2.243,
    pricePerM2: 24,
    randomLength: false,
    note: "",
  },
  {
    category: "hybrid",
    supplierCategory: "Hybrid",
    range: "Elegant SPC Hybrid 6.5mm",
    productType: "Plank",
    code: "HYB65005",
    colour: "IVORY BEIGE",
    size: "1540x182x5+1.5",
    lengthMinMm: 1540,
    lengthMaxMm: 1540,
    widthMm: 182,
    thicknessMm: 6.5,
    veneerMm: null,
    wearLayerMm: 1.5,
    wearLayerText: "",
    boardsPerPack: 8,
    packM2Min: 2.2422,
    packM2Max: 2.2422,
    packM2PrintedMin: 2.243,
    packM2PrintedMax: 2.243,
    pricePerM2: 24,
    randomLength: false,
    note: "",
  },
  {
    category: "hybrid",
    supplierCategory: "Hybrid",
    range: "Elegant SPC Hybrid 6.5mm",
    productType: "Plank",
    code: "HYB65006",
    colour: "PALE SAND",
    size: "1540x182x5+1.5",
    lengthMinMm: 1540,
    lengthMaxMm: 1540,
    widthMm: 182,
    thicknessMm: 6.5,
    veneerMm: null,
    wearLayerMm: 1.5,
    wearLayerText: "",
    boardsPerPack: 8,
    packM2Min: 2.2422,
    packM2Max: 2.2422,
    packM2PrintedMin: 2.243,
    packM2PrintedMax: 2.243,
    pricePerM2: 24,
    randomLength: false,
    note: "",
  },
  {
    category: "hybrid",
    supplierCategory: "Hybrid",
    range: "Elegant SPC Hybrid 6.5mm",
    productType: "Plank",
    code: "HYB65007",
    colour: "HARBOUR GREY",
    size: "1540x182x5+1.5",
    lengthMinMm: 1540,
    lengthMaxMm: 1540,
    widthMm: 182,
    thicknessMm: 6.5,
    veneerMm: null,
    wearLayerMm: 1.5,
    wearLayerText: "",
    boardsPerPack: 8,
    packM2Min: 2.2422,
    packM2Max: 2.2422,
    packM2PrintedMin: 2.243,
    packM2PrintedMax: 2.243,
    pricePerM2: 24,
    randomLength: false,
    note: "",
  },
  {
    category: "hybrid",
    supplierCategory: "Hybrid",
    range: "Elegant SPC Hybrid 6.5mm",
    productType: "Plank",
    code: "HYB65008",
    colour: "BEIGE SAND",
    size: "1540x182x5+1.5",
    lengthMinMm: 1540,
    lengthMaxMm: 1540,
    widthMm: 182,
    thicknessMm: 6.5,
    veneerMm: null,
    wearLayerMm: 1.5,
    wearLayerText: "",
    boardsPerPack: 8,
    packM2Min: 2.2422,
    packM2Max: 2.2422,
    packM2PrintedMin: 2.243,
    packM2PrintedMax: 2.243,
    pricePerM2: 24,
    randomLength: false,
    note: "",
  },
  {
    category: "hybrid",
    supplierCategory: "Hybrid",
    range: "Elegant SPC Hybrid 6.5mm",
    productType: "Plank",
    code: "HYB65009",
    colour: "KOALA GREY",
    size: "1540x182x5+1.5",
    lengthMinMm: 1540,
    lengthMaxMm: 1540,
    widthMm: 182,
    thicknessMm: 6.5,
    veneerMm: null,
    wearLayerMm: 1.5,
    wearLayerText: "",
    boardsPerPack: 8,
    packM2Min: 2.2422,
    packM2Max: 2.2422,
    packM2PrintedMin: 2.243,
    packM2PrintedMax: 2.243,
    pricePerM2: 24,
    randomLength: false,
    note: "",
  },
  {
    category: "hybrid",
    supplierCategory: "Hybrid",
    range: "Elegant SPC Hybrid 6.5mm",
    productType: "Plank",
    code: "HYB65010",
    colour: "NSW SPOTTED GUM",
    size: "1540x182x5+1.5",
    lengthMinMm: 1540,
    lengthMaxMm: 1540,
    widthMm: 182,
    thicknessMm: 6.5,
    veneerMm: null,
    wearLayerMm: 1.5,
    wearLayerText: "",
    boardsPerPack: 8,
    packM2Min: 2.2422,
    packM2Max: 2.2422,
    packM2PrintedMin: 2.243,
    packM2PrintedMax: 2.243,
    pricePerM2: 24,
    randomLength: false,
    note: "",
  },
  {
    category: "hybrid",
    supplierCategory: "Hybrid",
    range: "Elegant SPC Hybrid 6.5mm",
    productType: "Plank",
    code: "HYB65011",
    colour: "LIGHT GREY",
    size: "1540x182x5+1.5",
    lengthMinMm: 1540,
    lengthMaxMm: 1540,
    widthMm: 182,
    thicknessMm: 6.5,
    veneerMm: null,
    wearLayerMm: 1.5,
    wearLayerText: "",
    boardsPerPack: 8,
    packM2Min: 2.2422,
    packM2Max: 2.2422,
    packM2PrintedMin: 2.243,
    packM2PrintedMax: 2.243,
    pricePerM2: 24,
    randomLength: false,
    note: "",
  },
  {
    category: "hybrid",
    supplierCategory: "Hybrid",
    range: "Elegant SPC Hybrid 6.5mm",
    productType: "Plank",
    code: "HYB65012",
    colour: "RAW NEUTRAL",
    size: "1540x182x5+1.5",
    lengthMinMm: 1540,
    lengthMaxMm: 1540,
    widthMm: 182,
    thicknessMm: 6.5,
    veneerMm: null,
    wearLayerMm: 1.5,
    wearLayerText: "",
    boardsPerPack: 8,
    packM2Min: 2.2422,
    packM2Max: 2.2422,
    packM2PrintedMin: 2.243,
    packM2PrintedMax: 2.243,
    pricePerM2: 24,
    randomLength: false,
    note: "",
  },
  {
    category: "timber",
    supplierCategory: "Engineered Timber",
    range: "Engineered Australian Classic",
    productType: "Plank",
    code: "EAH143001",
    colour: "SPOTTED GUM",
    size: "1820-2100x136x14/3",
    lengthMinMm: 1820,
    lengthMaxMm: 2100,
    widthMm: 136,
    thicknessMm: 14,
    veneerMm: 3,
    wearLayerMm: null,
    wearLayerText: "3mm",
    boardsPerPack: 8,
    packM2Min: 1.9802,
    packM2Max: 2.2848,
    packM2PrintedMin: 1.981,
    packM2PrintedMax: 2.285,
    pricePerM2: 69,
    randomLength: true,
    note: "5G; stocking check advised before ordering",
  },
  {
    category: "timber",
    supplierCategory: "Engineered Timber",
    range: "Engineered Australian Classic",
    productType: "Plank",
    code: "EAH143002",
    colour: "BLACKBUTT",
    size: "1820-2100x136x14/3",
    lengthMinMm: 1820,
    lengthMaxMm: 2100,
    widthMm: 136,
    thicknessMm: 14,
    veneerMm: 3,
    wearLayerMm: null,
    wearLayerText: "3mm",
    boardsPerPack: 8,
    packM2Min: 1.9802,
    packM2Max: 2.2848,
    packM2PrintedMin: 1.981,
    packM2PrintedMax: 2.285,
    pricePerM2: 69,
    randomLength: true,
    note: "5G; stocking check advised before ordering",
  },
  {
    category: "timber",
    supplierCategory: "Engineered Timber",
    range: "Engineered Australian Classic",
    productType: "Plank",
    code: "EAH143003",
    colour: "SPOTTED GUM RUSTIC GRADE",
    size: "1820-2100x180x14/3",
    lengthMinMm: 1820,
    lengthMaxMm: 2100,
    widthMm: 180,
    thicknessMm: 14,
    veneerMm: 3,
    wearLayerMm: null,
    wearLayerText: "3mm",
    boardsPerPack: 8,
    packM2Min: 2.6208,
    packM2Max: 3.024,
    packM2PrintedMin: 2.621,
    packM2PrintedMax: 3.024,
    pricePerM2: 69,
    randomLength: true,
    note: "5G; stocking check advised before ordering",
  },
  {
    category: "timber",
    supplierCategory: "Engineered Timber",
    range: "Engineered Australian Classic",
    productType: "Plank",
    code: "EAH143004",
    colour: "BLACKBUTT RUSTIC GRADE",
    size: "1820-2100x180x14/3",
    lengthMinMm: 1820,
    lengthMaxMm: 2100,
    widthMm: 180,
    thicknessMm: 14,
    veneerMm: 3,
    wearLayerMm: null,
    wearLayerText: "3mm",
    boardsPerPack: 8,
    packM2Min: 2.6208,
    packM2Max: 3.024,
    packM2PrintedMin: 2.621,
    packM2PrintedMax: 3.024,
    pricePerM2: 69,
    randomLength: true,
    note: "5G; stocking check advised before ordering",
  },
  {
    category: "timber",
    supplierCategory: "Engineered Timber",
    range: "Engineered Australian Classic",
    productType: "Plank",
    code: "EAH143005",
    colour: "BLUEGUM",
    size: "1820-2100x136x14/3",
    lengthMinMm: 1820,
    lengthMaxMm: 2100,
    widthMm: 136,
    thicknessMm: 14,
    veneerMm: 3,
    wearLayerMm: null,
    wearLayerText: "3mm",
    boardsPerPack: 8,
    packM2Min: 1.9802,
    packM2Max: 2.2848,
    packM2PrintedMin: 1.981,
    packM2PrintedMax: 2.285,
    pricePerM2: 69,
    randomLength: true,
    note: "5G; stocking check advised before ordering",
  },
  {
    category: "timber",
    supplierCategory: "Engineered Timber",
    range: "Engineered Australian Classic",
    productType: "Plank",
    code: "EAH143006",
    colour: "GREY IRONBARK",
    size: "1820-2100x136x14/3",
    lengthMinMm: 1820,
    lengthMaxMm: 2100,
    widthMm: 136,
    thicknessMm: 14,
    veneerMm: 3,
    wearLayerMm: null,
    wearLayerText: "3mm",
    boardsPerPack: 8,
    packM2Min: 1.9802,
    packM2Max: 2.2848,
    packM2PrintedMin: 1.981,
    packM2PrintedMax: 2.285,
    pricePerM2: 69,
    randomLength: true,
    note: "5G; stocking check advised before ordering",
  },
  {
    category: "timber",
    supplierCategory: "Engineered Timber",
    range: "Engineered Australian Classic",
    productType: "Plank",
    code: "EAH143007",
    colour: "VICTORIA ASH",
    size: "1820-2100x190x14/3",
    lengthMinMm: 1820,
    lengthMaxMm: 2100,
    widthMm: 190,
    thicknessMm: 14,
    veneerMm: 3,
    wearLayerMm: null,
    wearLayerText: "3mm",
    boardsPerPack: 8,
    packM2Min: 2.7664,
    packM2Max: 3.192,
    packM2PrintedMin: 2.766,
    packM2PrintedMax: 3.192,
    pricePerM2: 69,
    randomLength: true,
    note: "5G; stocking check advised before ordering",
  },
  {
    category: "timber",
    supplierCategory: "Engineered Timber",
    range: "Engineered Australian Classic",
    productType: "Plank",
    code: "EAH143008",
    colour: "TALLOWOOD",
    size: "1820-2100x136x14/3",
    lengthMinMm: 1820,
    lengthMaxMm: 2100,
    widthMm: 136,
    thicknessMm: 14,
    veneerMm: 3,
    wearLayerMm: null,
    wearLayerText: "3mm",
    boardsPerPack: 8,
    packM2Min: 1.9802,
    packM2Max: 2.2848,
    packM2PrintedMin: 1.981,
    packM2PrintedMax: 2.285,
    pricePerM2: 69,
    randomLength: true,
    note: "5G; stocking check advised before ordering",
  },
];

export const RIVERHILL_ACCESSORIES: RiverhillAccessory[] = [
  {
    group: "Profile",
    fitsRange: "Elegant SPC Hybrid 6.5mm",
    fitsLabel: "Elegant Hybrid 6.5mm",
    item: "Scotia",
    description: "Elegant colours SPC Hybrid Range",
    size: "2400x28x15",
    price: 7,
    unit: "each",
    rollM2: null,
    charge: "",
  },
  {
    group: "Profile",
    fitsRange: "Elegant SPC Hybrid 6.5mm",
    fitsLabel: "Elegant Hybrid 6.5mm",
    item: "Reducer",
    description: "Elegant colours SPC Hybrid Range",
    size: "2400x43x10",
    price: 10,
    unit: "each",
    rollM2: null,
    charge: "",
  },
  {
    group: "Profile",
    fitsRange: "Elegant SPC Hybrid 6.5mm",
    fitsLabel: "Elegant Hybrid 6.5mm",
    item: "L-molding",
    description: "Elegant colours SPC Hybrid Range",
    size: "2400x25x7",
    price: 7,
    unit: "each",
    rollM2: null,
    charge: "",
  },
  {
    group: "Profile",
    fitsRange: "Elegant SPC Hybrid 6.5mm",
    fitsLabel: "Elegant Hybrid 6.5mm",
    item: "T-molding",
    description: "Elegant colours SPC Hybrid Range",
    size: "2400x45x7",
    price: 7,
    unit: "each",
    rollM2: null,
    charge: "",
  },
  {
    group: "Profile",
    fitsRange: "Elegant SPC Hybrid 6.5mm",
    fitsLabel: "Elegant Hybrid 6.5mm",
    item: "Stair-nosing",
    description: "Elegant colours SPC Hybrid Range",
    size: "1540x115x38",
    price: 30,
    unit: "each",
    rollM2: null,
    charge: "",
  },
  {
    group: "Profile",
    fitsRange: "Elegant SPC Hybrid 6.5mm",
    fitsLabel: "Elegant Hybrid 6.5mm",
    item: "Base Channel",
    description: "PVC Base Channel for Reducer and T-molding",
    size: "2400",
    price: 1.5,
    unit: "each",
    rollM2: null,
    charge: "",
  },
  {
    group: "Profile",
    fitsRange: "Elegant SPC Hybrid 9.5mm",
    fitsLabel: "Elegant Hybrid 9.5mm",
    item: "Scotia",
    description: "Elegant 9.5mm colours SPC Hybrid Range",
    size: "2400x28x15",
    price: 7,
    unit: "each",
    rollM2: null,
    charge: "",
  },
  {
    group: "Profile",
    fitsRange: "Elegant SPC Hybrid 9.5mm",
    fitsLabel: "Elegant Hybrid 9.5mm",
    item: "L-molding",
    description: "Elegant 9.5mm colours SPC Hybrid Range",
    size: "2400x30x10",
    price: 7,
    unit: "each",
    rollM2: null,
    charge: "",
  },
  {
    group: "Profile",
    fitsRange: "Elegant SPC Hybrid 9.5mm",
    fitsLabel: "Elegant Hybrid 9.5mm",
    item: "T-molding",
    description: "Elegant 9.5mm colours SPC Hybrid Range",
    size: "2400x30x10",
    price: 7,
    unit: "each",
    rollM2: null,
    charge: "",
  },
  {
    group: "Profile",
    fitsRange: "Elegant SPC Hybrid 9.5mm",
    fitsLabel: "Elegant Hybrid 9.5mm",
    item: "Stair-nosing",
    description: "Elegant 9.5mm colours SPC Hybrid Range",
    size: "1820x115x38",
    price: 36,
    unit: "each",
    rollM2: null,
    charge: "",
  },
  {
    group: "Accessory",
    fitsRange: "",
    fitsLabel: "Underlay",
    item: "HEL-20",
    description: "White Foam with Silver Foil 2mm",
    size: "20m²",
    price: 1.5,
    unit: "m2",
    rollM2: 20,
    charge: "per m²",
  },
  {
    group: "Accessory",
    fitsRange: "",
    fitsLabel: "Floor Protection",
    item: "HFP-20",
    description: "Flooring Protection 2mm",
    size: "20m²",
    price: 3,
    unit: "m2",
    rollM2: 20,
    charge: "per m²",
  },
  {
    group: "Profile",
    fitsRange: "Classique Oak",
    fitsLabel: "Classique Oak",
    item: "Stair-nosing",
    description: "Classique Oak colours ENO Range",
    size: "1900x90x28",
    price: 80,
    unit: "each",
    rollM2: null,
    charge: "",
  },
  {
    group: "Profile",
    fitsRange: "iDesign15 Oak",
    fitsLabel: "iDesign15 Oak",
    item: "Stair-nosing",
    description: "iDesign15 Oak colours PLK Range",
    size: "1900x90x28",
    price: 90,
    unit: "each",
    rollM2: null,
    charge: "",
  },
  {
    group: "Profile",
    fitsRange: "",
    fitsLabel: "Universal Aluminium",
    item: "UTC (A)",
    description: "Universal top cover silver/champagne/bronze/black",
    size: "3400 length",
    price: 21,
    unit: "each",
    rollM2: null,
    charge: "",
  },
  {
    group: "Profile",
    fitsRange: "",
    fitsLabel: "Universal Aluminium",
    item: "UTC PW",
    description: "Universal top cover premium wood grain wrapped",
    size: "3400 length",
    price: 30,
    unit: "each",
    rollM2: null,
    charge: "",
  },
  {
    group: "Profile",
    fitsRange: "",
    fitsLabel: "Universal Aluminium",
    item: "RCT(A)",
    description: "Ramp cover trim anodized silver/champagne/bronze/black",
    size: "3400 length",
    price: 23,
    unit: "each",
    rollM2: null,
    charge: "",
  },
  {
    group: "Profile",
    fitsRange: "",
    fitsLabel: "Universal Aluminium",
    item: "UBP",
    description: "Universal base plate incl. 3 inserts for 8-14mm flooring",
    size: "3400 length",
    price: 21,
    unit: "each",
    rollM2: null,
    charge: "",
  },
  {
    group: "Profile",
    fitsRange: "",
    fitsLabel: "Junior End Trim",
    item: "JE6PW",
    description: "Junior end trim premium wood colour 6.5mm",
    size: "3400x18x6.5",
    price: 30,
    unit: "each",
    rollM2: null,
    charge: "",
  },
  {
    group: "Profile",
    fitsRange: "",
    fitsLabel: "Junior End Trim",
    item: "JE8PW",
    description: "Junior end trim premium wood colour 8.4mm (cover 9.5mm)",
    size: "3400x18x8.4",
    price: 30,
    unit: "each",
    rollM2: null,
    charge: "",
  },
  {
    group: "Profile",
    fitsRange: "",
    fitsLabel: "Junior End Trim",
    item: "JE14PW",
    description: "Junior end trim premium wood colour 14mm",
    size: "3400x18x14/15",
    price: 30,
    unit: "each",
    rollM2: null,
    charge: "",
  },
];

export const RIVERHILL_UNPRICED: RiverhillUnpriced[] = [
  {
    item: "Bailing Charge",
    description: "No bailing charge stated in supplied 2025 price list",
    note: "Separate line item retained; no amount published",
  },
];
