// GENERATED by scripts/extract-victoriacarpets.py -- do not edit by hand.
//
// Victoria Carpets broadloom. 91 colours across 11 ranges, priced per
// LINEAL METRE ex GST. One price per range -- every colour in a range is the
// same money, asserted at parse time.
//
// THESE PRICES START 1 Oct 2026. Every row on the list carries that date and the
// list carries no other, so this is Victoria Carpets' NEXT price book, not
// their current one. What they charge before 1 Oct 2026 is not in the file.
// Quote October work off these numbers; do not check a September invoice
// against them.
//
// NO CUT PREMIUM. "Roll Price" and "Cut Length Price" are two separate columns
// holding the SAME number on all 91 rows. A part roll therefore costs the same
// per metre as a full one -- unlike Belgotex broadloom or Polyflor sheet vinyl.
// `cutPricePerLm` is carried anyway so the day they split, git shows it.
//
// BALING IS PER 40 lm STARTED, NOT PER ORDER. $35 per every 40 lineal metres and part thereof.
// TORENCO at $96.4/lm: ordering 40.1 lm instead of 40.0 lm buys
// $9.64 of carpet and triggers a second $35 block -- a 363.07% surcharge on
// the tenth of a metre that crossed the line. Measure to the boundary.
//
// THE APP CANNOT YET COMPUTE THAT FEE. The fee engine's bases are order /
// shipment / pallet / roll / week / percent_of_order; none of them is "per 40
// lm and part thereof". `VICTORIA_BALING_BLOCKS` below is the lookup the office
// reads off instead, and the supplier fee row is seeded NOT auto-applying so a
// quote can never quietly carry one $35 block when it owes three.
//
// ICONIC IS NOT ON VICTORIA CARPETS' OWN PRODUCTS INDEX. Its 8 colours come
// off a hosted specification sheet; the other 10 ranges are on the live site.
// It is priced, so it stays quotable -- but ring before promising it.
//
// NOT ON THE LIST, AND NOBODY SHOULD GUESS IT: roll WIDTH (so lm -> m2 cannot
// be done for any of these 91 lines), minimum order quantity, roll length,
// fibre, face weight, backing, whether Victoria Carpets deliver to the Gold
// Coast and what freight costs, and whether cut-length service has its own
// charge on top of baling. Open questions for the supplier.

export type VictoriaCarpetsRow = {
  /** Victoria Carpets' own SKU, "{productCode}/{colourCode}". */
  sku: string;
  productCode: string;
  range: string;
  colourCode: string;
  colour: string;
  /** Roll price ex GST per lineal metre. Effective 1 Oct 2026. */
  pricePerLm: number;
  /** Equals `pricePerLm` on every row today -- no cut premium published. */
  cutPricePerLm: number;
  websiteStatus: string;
  /** Range is absent from the supplier's Products index; colours off a spec sheet. */
  specSheetOnly: boolean;
  variantKey: string;
};

export const VICTORIA_SOURCE = "Victoria_Carpets_Oct_2026_Colours_and_Charges_ONLY_rRYK1a.xlsx";
/** Printed on every row. 5 days after this file was parsed -- a FUTURE price book. */
export const VICTORIA_EFFECTIVE_FROM = "2026-10-01";
export const VICTORIA_EFFECTIVE_PRINTED = "1 Oct 2026";
/** True on every row: roll price === cut length price, so no part-roll premium. */
export const VICTORIA_NO_CUT_PREMIUM = true;
export const VICTORIA_SPEC_ONLY_RANGE = "ICONIC";

export const VICTORIA_BALING = {
  amount: 35.0,
  blockLm: 40.0,
  rule: "$35 per every 40 lineal metres and part thereof",
};

/** ceil(lm / 40) x $35. The office reads this; the fee engine cannot do it. */
export const VICTORIA_BALING_BLOCKS: { lm: number; blocks: number; baling: number }[] = [
  {"lm": 10, "blocks": 1, "baling": 35.0},
  {"lm": 20, "blocks": 1, "baling": 35.0},
  {"lm": 30, "blocks": 1, "baling": 35.0},
  {"lm": 40, "blocks": 1, "baling": 35.0},
  {"lm": 40.1, "blocks": 2, "baling": 70.0},
  {"lm": 50, "blocks": 2, "baling": 70.0},
  {"lm": 60, "blocks": 2, "baling": 70.0},
  {"lm": 80, "blocks": 2, "baling": 70.0},
  {"lm": 80.1, "blocks": 3, "baling": 105.0},
  {"lm": 100, "blocks": 3, "baling": 105.0},
  {"lm": 120, "blocks": 3, "baling": 105.0},
  {"lm": 160, "blocks": 4, "baling": 140.0},
  {"lm": 200, "blocks": 5, "baling": 175.0},
];

/** One row per range, cheapest first. `balingPctOfBlock` = $35 over 40 lm of goods. */
export const VICTORIA_RANGES: {
  range: string;
  productCode: string;
  colours: number;
  pricePerLm: number;
  goodsPerBlock: number;
  balingPctOfBlock: number;
  specSheetOnly: boolean;
}[] = [
  {"range": "TORENCO", "productCode": "1406", "colours": 9, "pricePerLm": 96.4, "goodsPerBlock": 3856.0, "balingPctOfBlock": 0.91, "specSheetOnly": false},
  {"range": "CORTINO", "productCode": "1408", "colours": 9, "pricePerLm": 102.7, "goodsPerBlock": 4108.0, "balingPctOfBlock": 0.85, "specSheetOnly": false},
  {"range": "TAKONA", "productCode": "2556", "colours": 7, "pricePerLm": 131.4, "goodsPerBlock": 5256.0, "balingPctOfBlock": 0.67, "specSheetOnly": false},
  {"range": "ICONIC", "productCode": "2833", "colours": 8, "pricePerLm": 142.7, "goodsPerBlock": 5708.0, "balingPctOfBlock": 0.61, "specSheetOnly": true},
  {"range": "TUDOR TWIST SUPREME", "productCode": "2869", "colours": 10, "pricePerLm": 143.3, "goodsPerBlock": 5732.0, "balingPctOfBlock": 0.61, "specSheetOnly": false},
  {"range": "BEECHFORD", "productCode": "8218", "colours": 9, "pricePerLm": 162.0, "goodsPerBlock": 6480.0, "balingPctOfBlock": 0.54, "specSheetOnly": false},
  {"range": "APPLETON", "productCode": "2402", "colours": 8, "pricePerLm": 164.8, "goodsPerBlock": 6592.0, "balingPctOfBlock": 0.53, "specSheetOnly": false},
  {"range": "ELMVIEW", "productCode": "1403", "colours": 7, "pricePerLm": 166.4, "goodsPerBlock": 6656.0, "balingPctOfBlock": 0.53, "specSheetOnly": false},
  {"range": "TORRIDON", "productCode": "2541", "colours": 8, "pricePerLm": 173.2, "goodsPerBlock": 6928.0, "balingPctOfBlock": 0.51, "specSheetOnly": false},
  {"range": "SONNING", "productCode": "8050", "colours": 9, "pricePerLm": 183.0, "goodsPerBlock": 7320.0, "balingPctOfBlock": 0.48, "specSheetOnly": false},
  {"range": "MACARTHUR", "productCode": "2552", "colours": 7, "pricePerLm": 183.4, "goodsPerBlock": 7336.0, "balingPctOfBlock": 0.48, "specSheetOnly": false},
];

export const VICTORIA_BROADLOOM: VictoriaCarpetsRow[] = [
  {"sku": "2402/33", "productCode": "2402", "range": "APPLETON", "colourCode": "33", "colour": "Desert Skies", "pricePerLm": 164.8, "cutPricePerLm": 164.8, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|appleton|desert-skies|2402/33"},
  {"sku": "2402/34", "productCode": "2402", "range": "APPLETON", "colourCode": "34", "colour": "White Sage", "pricePerLm": 164.8, "cutPricePerLm": 164.8, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|appleton|white-sage|2402/34"},
  {"sku": "2402/39", "productCode": "2402", "range": "APPLETON", "colourCode": "39", "colour": "Deep Creek", "pricePerLm": 164.8, "cutPricePerLm": 164.8, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|appleton|deep-creek|2402/39"},
  {"sku": "2402/50", "productCode": "2402", "range": "APPLETON", "colourCode": "50", "colour": "Graytint", "pricePerLm": 164.8, "cutPricePerLm": 164.8, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|appleton|graytint|2402/50"},
  {"sku": "2402/51", "productCode": "2402", "range": "APPLETON", "colourCode": "51", "colour": "Cinder", "pricePerLm": 164.8, "cutPricePerLm": 164.8, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|appleton|cinder|2402/51"},
  {"sku": "2402/52", "productCode": "2402", "range": "APPLETON", "colourCode": "52", "colour": "Heron", "pricePerLm": 164.8, "cutPricePerLm": 164.8, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|appleton|heron|2402/52"},
  {"sku": "2402/53", "productCode": "2402", "range": "APPLETON", "colourCode": "53", "colour": "Winter Peak", "pricePerLm": 164.8, "cutPricePerLm": 164.8, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|appleton|winter-peak|2402/53"},
  {"sku": "2402/55", "productCode": "2402", "range": "APPLETON", "colourCode": "55", "colour": "Silver Fox", "pricePerLm": 164.8, "cutPricePerLm": 164.8, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|appleton|silver-fox|2402/55"},
  {"sku": "8218/12", "productCode": "8218", "range": "BEECHFORD", "colourCode": "12", "colour": "Dandelion", "pricePerLm": 162.0, "cutPricePerLm": 162.0, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|beechford|dandelion|8218/12"},
  {"sku": "8218/15", "productCode": "8218", "range": "BEECHFORD", "colourCode": "15", "colour": "Wholemeal", "pricePerLm": 162.0, "cutPricePerLm": 162.0, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|beechford|wholemeal|8218/15"},
  {"sku": "8218/33", "productCode": "8218", "range": "BEECHFORD", "colourCode": "33", "colour": "Parchment", "pricePerLm": 162.0, "cutPricePerLm": 162.0, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|beechford|parchment|8218/33"},
  {"sku": "8218/37", "productCode": "8218", "range": "BEECHFORD", "colourCode": "37", "colour": "Bonfire", "pricePerLm": 162.0, "cutPricePerLm": 162.0, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|beechford|bonfire|8218/37"},
  {"sku": "8218/50", "productCode": "8218", "range": "BEECHFORD", "colourCode": "50", "colour": "Delicate Mist", "pricePerLm": 162.0, "cutPricePerLm": 162.0, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|beechford|delicate-mist|8218/50"},
  {"sku": "8218/51", "productCode": "8218", "range": "BEECHFORD", "colourCode": "51", "colour": "Maelstrom", "pricePerLm": 162.0, "cutPricePerLm": 162.0, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|beechford|maelstrom|8218/51"},
  {"sku": "8218/53", "productCode": "8218", "range": "BEECHFORD", "colourCode": "53", "colour": "Alpine Wind", "pricePerLm": 162.0, "cutPricePerLm": 162.0, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|beechford|alpine-wind|8218/53"},
  {"sku": "8218/54", "productCode": "8218", "range": "BEECHFORD", "colourCode": "54", "colour": "Plateau", "pricePerLm": 162.0, "cutPricePerLm": 162.0, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|beechford|plateau|8218/54"},
  {"sku": "8218/72", "productCode": "8218", "range": "BEECHFORD", "colourCode": "72", "colour": "Ivy", "pricePerLm": 162.0, "cutPricePerLm": 162.0, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|beechford|ivy|8218/72"},
  {"sku": "1408/10", "productCode": "1408", "range": "CORTINO", "colourCode": "10", "colour": "Winter Moon", "pricePerLm": 102.7, "cutPricePerLm": 102.7, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|cortino|winter-moon|1408/10"},
  {"sku": "1408/11", "productCode": "1408", "range": "CORTINO", "colourCode": "11", "colour": "Stone Pillar", "pricePerLm": 102.7, "cutPricePerLm": 102.7, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|cortino|stone-pillar|1408/11"},
  {"sku": "1408/15", "productCode": "1408", "range": "CORTINO", "colourCode": "15", "colour": "Custard Cream", "pricePerLm": 102.7, "cutPricePerLm": 102.7, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|cortino|custard-cream|1408/15"},
  {"sku": "1408/33", "productCode": "1408", "range": "CORTINO", "colourCode": "33", "colour": "Hayloft", "pricePerLm": 102.7, "cutPricePerLm": 102.7, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|cortino|hayloft|1408/33"},
  {"sku": "1408/39", "productCode": "1408", "range": "CORTINO", "colourCode": "39", "colour": "Woodcrest", "pricePerLm": 102.7, "cutPricePerLm": 102.7, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|cortino|woodcrest|1408/39"},
  {"sku": "1408/50", "productCode": "1408", "range": "CORTINO", "colourCode": "50", "colour": "Misty Glade", "pricePerLm": 102.7, "cutPricePerLm": 102.7, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|cortino|misty-glade|1408/50"},
  {"sku": "1408/51", "productCode": "1408", "range": "CORTINO", "colourCode": "51", "colour": "Dragonfly", "pricePerLm": 102.7, "cutPricePerLm": 102.7, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|cortino|dragonfly|1408/51"},
  {"sku": "1408/52", "productCode": "1408", "range": "CORTINO", "colourCode": "52", "colour": "Mountaineer", "pricePerLm": 102.7, "cutPricePerLm": 102.7, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|cortino|mountaineer|1408/52"},
  {"sku": "1408/55", "productCode": "1408", "range": "CORTINO", "colourCode": "55", "colour": "Odyssey", "pricePerLm": 102.7, "cutPricePerLm": 102.7, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|cortino|odyssey|1408/55"},
  {"sku": "1403/15", "productCode": "1403", "range": "ELMVIEW", "colourCode": "15", "colour": "Nougat Cream", "pricePerLm": 166.4, "cutPricePerLm": 166.4, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|elmview|nougat-cream|1403/15"},
  {"sku": "1403/33", "productCode": "1403", "range": "ELMVIEW", "colourCode": "33", "colour": "Earl Grey", "pricePerLm": 166.4, "cutPricePerLm": 166.4, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|elmview|earl-grey|1403/33"},
  {"sku": "1403/39", "productCode": "1403", "range": "ELMVIEW", "colourCode": "39", "colour": "Eagle", "pricePerLm": 166.4, "cutPricePerLm": 166.4, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|elmview|eagle|1403/39"},
  {"sku": "1403/50", "productCode": "1403", "range": "ELMVIEW", "colourCode": "50", "colour": "Neptune", "pricePerLm": 166.4, "cutPricePerLm": 166.4, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|elmview|neptune|1403/50"},
  {"sku": "1403/51", "productCode": "1403", "range": "ELMVIEW", "colourCode": "51", "colour": "Murry Grey", "pricePerLm": 166.4, "cutPricePerLm": 166.4, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|elmview|murry-grey|1403/51"},
  {"sku": "1403/52", "productCode": "1403", "range": "ELMVIEW", "colourCode": "52", "colour": "Iron Mountain", "pricePerLm": 166.4, "cutPricePerLm": 166.4, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|elmview|iron-mountain|1403/52"},
  {"sku": "1403/55", "productCode": "1403", "range": "ELMVIEW", "colourCode": "55", "colour": "Northern Sky", "pricePerLm": 166.4, "cutPricePerLm": 166.4, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|elmview|northern-sky|1403/55"},
  {"sku": "2833/35", "productCode": "2833", "range": "ICONIC", "colourCode": "35", "colour": "Graphite", "pricePerLm": 142.7, "cutPricePerLm": 142.7, "websiteStatus": "Colour names from Victoria Carpets hosted specification; product not shown on current Products index", "specSheetOnly": true, "variantKey": "victoriacarpets|iconic|graphite|2833/35"},
  {"sku": "2833/38", "productCode": "2833", "range": "ICONIC", "colourCode": "38", "colour": "Boulder", "pricePerLm": 142.7, "cutPricePerLm": 142.7, "websiteStatus": "Colour names from Victoria Carpets hosted specification; product not shown on current Products index", "specSheetOnly": true, "variantKey": "victoriacarpets|iconic|boulder|2833/38"},
  {"sku": "2833/50", "productCode": "2833", "range": "ICONIC", "colourCode": "50", "colour": "Silver Shadow", "pricePerLm": 142.7, "cutPricePerLm": 142.7, "websiteStatus": "Colour names from Victoria Carpets hosted specification; product not shown on current Products index", "specSheetOnly": true, "variantKey": "victoriacarpets|iconic|silver-shadow|2833/50"},
  {"sku": "2833/51", "productCode": "2833", "range": "ICONIC", "colourCode": "51", "colour": "Storm", "pricePerLm": 142.7, "cutPricePerLm": 142.7, "websiteStatus": "Colour names from Victoria Carpets hosted specification; product not shown on current Products index", "specSheetOnly": true, "variantKey": "victoriacarpets|iconic|storm|2833/51"},
  {"sku": "2833/54", "productCode": "2833", "range": "ICONIC", "colourCode": "54", "colour": "Pearl Grey", "pricePerLm": 142.7, "cutPricePerLm": 142.7, "websiteStatus": "Colour names from Victoria Carpets hosted specification; product not shown on current Products index", "specSheetOnly": true, "variantKey": "victoriacarpets|iconic|pearl-grey|2833/54"},
  {"sku": "2833/55", "productCode": "2833", "range": "ICONIC", "colourCode": "55", "colour": "Grey Nuance", "pricePerLm": 142.7, "cutPricePerLm": 142.7, "websiteStatus": "Colour names from Victoria Carpets hosted specification; product not shown on current Products index", "specSheetOnly": true, "variantKey": "victoriacarpets|iconic|grey-nuance|2833/55"},
  {"sku": "2833/92", "productCode": "2833", "range": "ICONIC", "colourCode": "92", "colour": "Slate", "pricePerLm": 142.7, "cutPricePerLm": 142.7, "websiteStatus": "Colour names from Victoria Carpets hosted specification; product not shown on current Products index", "specSheetOnly": true, "variantKey": "victoriacarpets|iconic|slate|2833/92"},
  {"sku": "2833/93", "productCode": "2833", "range": "ICONIC", "colourCode": "93", "colour": "Volcanic", "pricePerLm": 142.7, "cutPricePerLm": 142.7, "websiteStatus": "Colour names from Victoria Carpets hosted specification; product not shown on current Products index", "specSheetOnly": true, "variantKey": "victoriacarpets|iconic|volcanic|2833/93"},
  {"sku": "2552/11", "productCode": "2552", "range": "MACARTHUR", "colourCode": "11", "colour": "Banks", "pricePerLm": 183.4, "cutPricePerLm": 183.4, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|macarthur|banks|2552/11"},
  {"sku": "2552/17", "productCode": "2552", "range": "MACARTHUR", "colourCode": "17", "colour": "King", "pricePerLm": 183.4, "cutPricePerLm": 183.4, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|macarthur|king|2552/17"},
  {"sku": "2552/33", "productCode": "2552", "range": "MACARTHUR", "colourCode": "33", "colour": "Lachlan", "pricePerLm": 183.4, "cutPricePerLm": 183.4, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|macarthur|lachlan|2552/33"},
  {"sku": "2552/34", "productCode": "2552", "range": "MACARTHUR", "colourCode": "34", "colour": "Hunter", "pricePerLm": 183.4, "cutPricePerLm": 183.4, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|macarthur|hunter|2552/34"},
  {"sku": "2552/37", "productCode": "2552", "range": "MACARTHUR", "colourCode": "37", "colour": "Camden", "pricePerLm": 183.4, "cutPricePerLm": 183.4, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|macarthur|camden|2552/37"},
  {"sku": "2552/52", "productCode": "2552", "range": "MACARTHUR", "colourCode": "52", "colour": "Picton", "pricePerLm": 183.4, "cutPricePerLm": 183.4, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|macarthur|picton|2552/52"},
  {"sku": "2552/55", "productCode": "2552", "range": "MACARTHUR", "colourCode": "55", "colour": "Marsden", "pricePerLm": 183.4, "cutPricePerLm": 183.4, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|macarthur|marsden|2552/55"},
  {"sku": "8050/12", "productCode": "8050", "range": "SONNING", "colourCode": "12", "colour": "Wisp", "pricePerLm": 183.0, "cutPricePerLm": 183.0, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|sonning|wisp|8050/12"},
  {"sku": "8050/15", "productCode": "8050", "range": "SONNING", "colourCode": "15", "colour": "Country Roads", "pricePerLm": 183.0, "cutPricePerLm": 183.0, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|sonning|country-roads|8050/15"},
  {"sku": "8050/33", "productCode": "8050", "range": "SONNING", "colourCode": "33", "colour": "Honey Joy", "pricePerLm": 183.0, "cutPricePerLm": 183.0, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|sonning|honey-joy|8050/33"},
  {"sku": "8050/37", "productCode": "8050", "range": "SONNING", "colourCode": "37", "colour": "Brambles", "pricePerLm": 183.0, "cutPricePerLm": 183.0, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|sonning|brambles|8050/37"},
  {"sku": "8050/50", "productCode": "8050", "range": "SONNING", "colourCode": "50", "colour": "Ashwood", "pricePerLm": 183.0, "cutPricePerLm": 183.0, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|sonning|ashwood|8050/50"},
  {"sku": "8050/51", "productCode": "8050", "range": "SONNING", "colourCode": "51", "colour": "Warren", "pricePerLm": 183.0, "cutPricePerLm": 183.0, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|sonning|warren|8050/51"},
  {"sku": "8050/53", "productCode": "8050", "range": "SONNING", "colourCode": "53", "colour": "Magnolia", "pricePerLm": 183.0, "cutPricePerLm": 183.0, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|sonning|magnolia|8050/53"},
  {"sku": "8050/54", "productCode": "8050", "range": "SONNING", "colourCode": "54", "colour": "Frosted", "pricePerLm": 183.0, "cutPricePerLm": 183.0, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|sonning|frosted|8050/54"},
  {"sku": "8050/72", "productCode": "8050", "range": "SONNING", "colourCode": "72", "colour": "Clover", "pricePerLm": 183.0, "cutPricePerLm": 183.0, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|sonning|clover|8050/72"},
  {"sku": "2556/12", "productCode": "2556", "range": "TAKONA", "colourCode": "12", "colour": "Light Breeze", "pricePerLm": 131.4, "cutPricePerLm": 131.4, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|takona|light-breeze|2556/12"},
  {"sku": "2556/19", "productCode": "2556", "range": "TAKONA", "colourCode": "19", "colour": "Shoreline", "pricePerLm": 131.4, "cutPricePerLm": 131.4, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|takona|shoreline|2556/19"},
  {"sku": "2556/29", "productCode": "2556", "range": "TAKONA", "colourCode": "29", "colour": "Eagle Rock", "pricePerLm": 131.4, "cutPricePerLm": 131.4, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|takona|eagle-rock|2556/29"},
  {"sku": "2556/51", "productCode": "2556", "range": "TAKONA", "colourCode": "51", "colour": "Silver Wing", "pricePerLm": 131.4, "cutPricePerLm": 131.4, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|takona|silver-wing|2556/51"},
  {"sku": "2556/55", "productCode": "2556", "range": "TAKONA", "colourCode": "55", "colour": "Stormy Skies", "pricePerLm": 131.4, "cutPricePerLm": 131.4, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|takona|stormy-skies|2556/55"},
  {"sku": "2556/58", "productCode": "2556", "range": "TAKONA", "colourCode": "58", "colour": "Monsoon", "pricePerLm": 131.4, "cutPricePerLm": 131.4, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|takona|monsoon|2556/58"},
  {"sku": "2556/90", "productCode": "2556", "range": "TAKONA", "colourCode": "90", "colour": "Mist", "pricePerLm": 131.4, "cutPricePerLm": 131.4, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|takona|mist|2556/90"},
  {"sku": "1406/10", "productCode": "1406", "range": "TORENCO", "colourCode": "10", "colour": "Daylight", "pricePerLm": 96.4, "cutPricePerLm": 96.4, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|torenco|daylight|1406/10"},
  {"sku": "1406/11", "productCode": "1406", "range": "TORENCO", "colourCode": "11", "colour": "Dream Haze", "pricePerLm": 96.4, "cutPricePerLm": 96.4, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|torenco|dream-haze|1406/11"},
  {"sku": "1406/15", "productCode": "1406", "range": "TORENCO", "colourCode": "15", "colour": "Concord Ivory", "pricePerLm": 96.4, "cutPricePerLm": 96.4, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|torenco|concord-ivory|1406/15"},
  {"sku": "1406/33", "productCode": "1406", "range": "TORENCO", "colourCode": "33", "colour": "Pecan", "pricePerLm": 96.4, "cutPricePerLm": 96.4, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|torenco|pecan|1406/33"},
  {"sku": "1406/39", "productCode": "1406", "range": "TORENCO", "colourCode": "39", "colour": "Java", "pricePerLm": 96.4, "cutPricePerLm": 96.4, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|torenco|java|1406/39"},
  {"sku": "1406/50", "productCode": "1406", "range": "TORENCO", "colourCode": "50", "colour": "Stardust", "pricePerLm": 96.4, "cutPricePerLm": 96.4, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|torenco|stardust|1406/50"},
  {"sku": "1406/51", "productCode": "1406", "range": "TORENCO", "colourCode": "51", "colour": "Elephant Grey", "pricePerLm": 96.4, "cutPricePerLm": 96.4, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|torenco|elephant-grey|1406/51"},
  {"sku": "1406/52", "productCode": "1406", "range": "TORENCO", "colourCode": "52", "colour": "Anchor", "pricePerLm": 96.4, "cutPricePerLm": 96.4, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|torenco|anchor|1406/52"},
  {"sku": "1406/55", "productCode": "1406", "range": "TORENCO", "colourCode": "55", "colour": "Raven", "pricePerLm": 96.4, "cutPricePerLm": 96.4, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|torenco|raven|1406/55"},
  {"sku": "2541/13", "productCode": "2541", "range": "TORRIDON", "colourCode": "13", "colour": "Bufftone", "pricePerLm": 173.2, "cutPricePerLm": 173.2, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|torridon|bufftone|2541/13"},
  {"sku": "2541/33", "productCode": "2541", "range": "TORRIDON", "colourCode": "33", "colour": "Chill", "pricePerLm": 173.2, "cutPricePerLm": 173.2, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|torridon|chill|2541/33"},
  {"sku": "2541/39", "productCode": "2541", "range": "TORRIDON", "colourCode": "39", "colour": "Rainy Fall", "pricePerLm": 173.2, "cutPricePerLm": 173.2, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|torridon|rainy-fall|2541/39"},
  {"sku": "2541/53", "productCode": "2541", "range": "TORRIDON", "colourCode": "53", "colour": "Moonbeam", "pricePerLm": 173.2, "cutPricePerLm": 173.2, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|torridon|moonbeam|2541/53"},
  {"sku": "2541/54", "productCode": "2541", "range": "TORRIDON", "colourCode": "54", "colour": "Mallard", "pricePerLm": 173.2, "cutPricePerLm": 173.2, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|torridon|mallard|2541/54"},
  {"sku": "2541/56", "productCode": "2541", "range": "TORRIDON", "colourCode": "56", "colour": "Intrigue", "pricePerLm": 173.2, "cutPricePerLm": 173.2, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|torridon|intrigue|2541/56"},
  {"sku": "2541/57", "productCode": "2541", "range": "TORRIDON", "colourCode": "57", "colour": "Picador", "pricePerLm": 173.2, "cutPricePerLm": 173.2, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|torridon|picador|2541/57"},
  {"sku": "2541/90", "productCode": "2541", "range": "TORRIDON", "colourCode": "90", "colour": "Tavern", "pricePerLm": 173.2, "cutPricePerLm": 173.2, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|torridon|tavern|2541/90"},
  {"sku": "2869/14", "productCode": "2869", "range": "TUDOR TWIST SUPREME", "colourCode": "14", "colour": "Alabaster", "pricePerLm": 143.3, "cutPricePerLm": 143.3, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|tudor-twist-supreme|alabaster|2869/14"},
  {"sku": "2869/18", "productCode": "2869", "range": "TUDOR TWIST SUPREME", "colourCode": "18", "colour": "Coronet", "pricePerLm": 143.3, "cutPricePerLm": 143.3, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|tudor-twist-supreme|coronet|2869/18"},
  {"sku": "2869/20", "productCode": "2869", "range": "TUDOR TWIST SUPREME", "colourCode": "20", "colour": "Dominion", "pricePerLm": 143.3, "cutPricePerLm": 143.3, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|tudor-twist-supreme|dominion|2869/20"},
  {"sku": "2869/31", "productCode": "2869", "range": "TUDOR TWIST SUPREME", "colourCode": "31", "colour": "Aristocrat", "pricePerLm": 143.3, "cutPricePerLm": 143.3, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|tudor-twist-supreme|aristocrat|2869/31"},
  {"sku": "2869/32", "productCode": "2869", "range": "TUDOR TWIST SUPREME", "colourCode": "32", "colour": "Pageant", "pricePerLm": 143.3, "cutPricePerLm": 143.3, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|tudor-twist-supreme|pageant|2869/32"},
  {"sku": "2869/37", "productCode": "2869", "range": "TUDOR TWIST SUPREME", "colourCode": "37", "colour": "Castle Wall", "pricePerLm": 143.3, "cutPricePerLm": 143.3, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|tudor-twist-supreme|castle-wall|2869/37"},
  {"sku": "2869/52", "productCode": "2869", "range": "TUDOR TWIST SUPREME", "colourCode": "52", "colour": "Knight", "pricePerLm": 143.3, "cutPricePerLm": 143.3, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|tudor-twist-supreme|knight|2869/52"},
  {"sku": "2869/53", "productCode": "2869", "range": "TUDOR TWIST SUPREME", "colourCode": "53", "colour": "Throne Room", "pricePerLm": 143.3, "cutPricePerLm": 143.3, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|tudor-twist-supreme|throne-room|2869/53"},
  {"sku": "2869/54", "productCode": "2869", "range": "TUDOR TWIST SUPREME", "colourCode": "54", "colour": "Lionheart", "pricePerLm": 143.3, "cutPricePerLm": 143.3, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|tudor-twist-supreme|lionheart|2869/54"},
  {"sku": "2869/75", "productCode": "2869", "range": "TUDOR TWIST SUPREME", "colourCode": "75", "colour": "Wizard", "pricePerLm": 143.3, "cutPricePerLm": 143.3, "websiteStatus": "Current Victoria Carpets website", "specSheetOnly": false, "variantKey": "victoriacarpets|tudor-twist-supreme|wizard|2869/75"},
];
